AX58400-CM7: CAN Application Profile over EtherCAT
CAN Application Profile over EtherCAT
Modules
SDO Error Codes
SDO Header and Data
SDO Services
SDO Abort Codes
SDO Pending Response
Segmented SDO
Files
file coeappl.c
Implementation This file contains an example for CoE services and the CoE object dictionary.
file coeappl.h
file ecatcoe.c
Implementation This file contains the CoE mailbox interface.
file ecatcoe.h
file objdef.c
Implementation This file contains the object dictionary access functions.
file objdef.h
CAN application profile over EtherCAT object dictionary.
file sdoserv.c
Implementation The SDO server handles all sdo and sdo information services.
file sdoserv.h
SDO Service definitions.
Data Structures
struct OBJ_STRUCT_PACKED_START
Data structure to handle the axis specific object data.
struct MBX_STRUCT_PACKED_START
CoE Mailbox header.
struct OBJ_ENTRY
Object dictionary entry structure.
Macros
#define _COEAPPL_ 1
#define _OBJD_
#define CHECK_DC_OVERRUN_IN_MS 4000
cycle time in ms to check the DC system time for overrun
#define PROTO extern
#define _ECATCOE_ 1
#define ECATCOE 0x4300
#define ECATCOEMAX 0x02
#define ERROR_COEINVALIDSERVICE 0x01
Invalid SDO service.
#define ERROR_COENOTSUPPORTED 0x02
Not supported service.
#define COESERVICE_EMERGENCY 0x01
CoE Emergency.
#define COESERVICE_SDOREQUEST 0x02
CoE SDO request.
#define COESERVICE_SDORESPONSE 0x03
CoE SDO response.
#define COESERVICE_TXPDO 0x04
CoE TxPDO.
#define COESERVICE_RXPDO 0x05
CoE RxPDO.
#define COESERVICE_TXPDOREMREQ 0x06
CoE TxPDO map request.
#define COESERVICE_RXPDOREMREQ 0x07
CoE RxPDO map request.
#define COESERVICE_SDOINFO 0x08
CoE SDO Info.
#define COEHEADER_COESERVICESHIFT 12
CoE service shift (within CoE header)
#define COEHEADER_COESERVICEMASK 0xF000
CoE service mask (within CoE header)
#define COE_HEADER_SIZE 2
CoE header size.
#define PROTO extern
#define OBJDEF 0x4000
#define OBJDEFMAX 0x0A
#define _OBJDEF_ 1
#define DEFTYPE_NULL 0x0000
Null.
#define DEFTYPE_BOOLEAN 0x0001
BOOLEAN.
#define DEFTYPE_INTEGER8 0x0002
INTEGER8.
#define DEFTYPE_INTEGER16 0x0003
INTEGER16.
#define DEFTYPE_INTEGER24 0x0010
INTEGER24.
#define DEFTYPE_INTEGER24 0x0010
INTEGER24.
#define DEFTYPE_INTEGER32 0x0004
INTEGER32.
#define DEFTYPE_INTEGER40 0x0012
INTEGER40.
#define DEFTYPE_INTEGER40 0x0012
INTEGER40.
#define DEFTYPE_INTEGER48 0x0013
INTEGER48.
#define DEFTYPE_INTEGER48 0x0013
INTEGER48.
#define DEFTYPE_INTEGER56 0x0014
INTEGER56.
#define DEFTYPE_INTEGER56 0x0014
INTEGER56.
#define DEFTYPE_UNSIGNED8 0x0005
UNSIGNED8.
#define DEFTYPE_UNSIGNED16 0x0006
UNSIGNED16.
#define DEFTYPE_UNSIGNED24 0x0016
UNSIGNED24.
#define DEFTYPE_UNSIGNED24 0x0016
UNSIGNED24.
#define DEFTYPE_UNSIGNED32 0x0007
UNSIGNED32.
#define DEFTYPE_REAL32 0x0008
REAL32.
#define DEFTYPE_VISIBLESTRING 0x0009
VISIBLE_STRING.
#define DEFTYPE_OCTETSTRING 0x000A
OCTET_STRING.
#define DEFTYPE_UNICODE_STRING 0x000B
UNICODE_STRING.
#define DEFTYPE_TIME_OF_DAY 0x000C
TIME_OF_DAY.
#define DEFTYPE_TIME_DIFFERENCE 0x000D
TIME_DIFFERENCE.
#define DEFTYPE_REAL64 0x0011
REAL64.
#define DEFTYPE_INTEGER64 0x0015
INTEGER64.
#define DEFTYPE_UNSIGNED40 0x0018
UNSIGNED40.
#define DEFTYPE_UNSIGNED48 0x0019
UNSIGNED48.
#define DEFTYPE_UNSIGNED56 0x001A
UNSIGNED56.
#define DEFTYPE_UNSIGNED64 0x001B
UNSIGNED64.
#define DEFTYPE_GUID 0x001D
DEFTYPE_GUID.
#define DEFTYPE_BYTE 0x001E
DEFTYPE_BYTE.
#define DEFTYPE_WORD 0x001F
DEFTYPE_WORD.
#define DEFTYPE_DWORD 0x0020
DEFTYPE_DWORD.
#define DEFTYPE_PDOMAPPING 0x0021
PDO_MAPPING.
#define DEFTYPE_IDENTITY 0x0023
IDENTITY.
#define DEFTYPE_COMMAND 0x0025
COMMAND_PAR.
#define DEFTYPE_PDOCOMPAR 0x0027
PDO_PARAMETER.
#define DEFTYPE_ENUM 0x0028
DEFTYPE_ENUM.
#define DEFTYPE_SMPAR 0x0029
SM_SYNCHRONISATION.
#define DEFTYPE_RECORD 0x002A
DEFTYPE_RECORD.
#define DEFTYPE_BACKUP 0x002B
BACKUP_PARAMETER.
#define DEFTYPE_MDP 0x002C
MODULAR_DEVICE_PROFILE.
#define DEFTYPE_BITARR8 0x002D
BITARR8.
#define DEFTYPE_BITARR16 0x002E
BITARR16.
#define DEFTYPE_BITARR32 0x002F
BITARR32.
#define DEFTYPE_BIT1 0x0030
BIT1.
#define DEFTYPE_BIT2 0x0031
BIT2.
#define DEFTYPE_BIT3 0x0032
BIT3.
#define DEFTYPE_BIT4 0x0033
BIT4.
#define DEFTYPE_BIT5 0x0034
BIT5.
#define DEFTYPE_BIT6 0x0035
BIT6.
#define DEFTYPE_BIT7 0x0036
BIT7.
#define DEFTYPE_BIT8 0x0037
BIT8.
#define DEFTYPE_ARRAY_OF_INT 0x0260
DEFTYPE_ARRAY_OF_INT.
#define DEFTYPE_ARRAY_OF_SINT 0x0261
DEFTYPE_ARRAY_OF_SINT.
#define DEFTYPE_ARRAY_OF_DINT 0x0262
DEFTYPE_ARRAY_OF_DINT.
#define DEFTYPE_ARRAY_OF_UDINT 0x0263
DEFTYPE_ARRAY_OF_UDINT.
#define DEFTYPE_ERRORHANDLING 0x0281
DEFTYPE_ERRORHANDLING.
#define DEFTYPE_DIAGHISTORY 0x0282
DEFTYPE_DIAGHISTORY.
#define DEFTYPE_SYNCSTATUS 0x0283
DEFTYPE_SYNCSTATUS.
#define DEFTYPE_SYNCSETTINGS 0x0284
DEFTYPE_SYNCSETTINGS.
#define DEFTYPE_FSOEFRAME 0x0285
DEFTYPE_FSOEFRAME.
#define DEFTYPE_FSOECOMMPAR 0x0286
DEFTYPE_FSOECOMMPAR.
#define SYNCTYPE_FREERUNSUPP 0x0001
FreeRun supported.
#define SYNCTYPE_SYNCHRONSUPP 0x0002
SyncManager synchron supported.
#define SYNCTYPE_DCSYNC0SUPP 0x0004
Sync0 synchron supported.
#define SYNCTYPE_DCSYNC1SUPP 0x0008
Sync1 synchron supported.
#define SYNCTYPE_SUBCYCLESUPP 0x0010
Subordinated Application with fixed Sync0 supported.
#define SYNCTYPE_LOCALSHIFTSUPP 0x0020
Event shift with local timer supported. Output shift : 0x1C32.4 ; Input shift : 0x1C33.4 (not supported by the default SSC)
#define SYNCTYPE_SHIFTBYSYNC1SUPP 0x0040
Event shift with Sync1 event supported. Output shift : 0x1C32.4 ; Input shift : 0x1C33.4.
#define SYNCTYPE_MEASURE_DELAYSUPP 0x0200
Delay times should be measured (not supported by the default SSC, only the cycle time can be measured (1ms resolution)
#define SYNCTYPE_FIXED_DELAYSUPP 0x0400
Delay times are fixed.
#define SYNCTYPE_TIMESVARIABLE 0x4000
Dynamic Cycle Times supported.
#define IS_PDO_ASSIGN(x) ((x >= 0x1C10) && (x <= 0x1C2F))
Marco to check if object index is SyncManager assign object.
#define IS_RX_PDO(x) (((x) >= 0x1600) && ((x) <= 0x17FF))
Marco to check if object index RxPDO mapping object.
#define IS_TX_PDO(x) (((x) >= 0x1A00) && ((x) <= 0x1BFF))
Marco to check if object index TxPDO mapping object.
#define PROTO extern
#define _SDOSERV_ 1
#define PROTO extern
Typedefs
typedef struct OBJ_STRUCT_PACKED_START TOBJ1018
0x1018 (Identity) object structure
typedef struct OBJ_STRUCT_PACKED_START TOBJ1C00
0x1C00 (Sync manager type) object structure
typedef UINT16 TCOEHEADER
CoE header.
typedef struct MBX_STRUCT_PACKED_START TCOEMBX
CoE Mailbox header.
typedef struct OBJ_ENTRY TOBJECT
Object dictionary entry structure.
typedef struct OBJ_STRUCT_PACKED_START TSYNCMANPAR
typedef struct OBJ_STRUCT_PACKED_START TCYCLEDIAG
typedef struct OBJ_STRUCT_PACKED_START TOBJ10F1
Functions
UINT8 Read0x10F8 (UINT16 index, UINT8 subindex, UINT32 dataSize, UINT16 MBXMEM *pData, UINT8 bCompleteAccess)
This function reads the object 0x10F8.
void COE_SyncTimeStamp (void)
This function updates the local timestamp object (0x10F8) and has to be called at least every 4.2sec to detect an 32Bit DC unit overrun. Called from the Timer handler.
OBJCONST TOBJECT OBJMEM * COE_GetObjectDictionary (void)
returns the pointer to the object dictionary
void COE_UpdateSyncErrorStatus (void)
Update the Sync Error Indication.
void COE_ObjInit (void)
This function initialize the several objects.
UINT16 COE_AddObjectToDic (TOBJECT OBJMEM *pNewObjEntry)
This function adds an object to the object dictionary.
void COE_RemoveDicEntry (UINT16 index)
This function removes an object to the object dictionary.
void COE_ClearObjDictionary (void)
This function clear the object dictionary.
UINT16 AddObjectsToObjDictionary (TOBJECT OBJMEM *pObjEntry)
UINT16 COE_ObjDictionaryInit (void)
This function initialize the object dictionary.
void COE_Main (void)
is called for background calculations which should not influence the ECAT_Application in synchronous modes
void COE_Init (void)
This function intialize the CoE Interface.
UINT8 COE_ServiceInd (TCOEMBX MBXMEM *pCoeMbx)
This function is called when a CoE (CAN application layer over EtherCAT) service is received from the master.
UINT8 COE_ContinueInd (TMBX MBXMEM *pMbx)
This function is called when a CoE service to be sent is stored and can.
OBJCONST TSDOINFOENTRYDESC OBJMEM * OBJ_GetEntryDesc (OBJCONST TOBJECT OBJMEM *pObjEntry, UINT8 Subindex)
The function returns the Entry-Desc of a subindex to allow the application to define the object dictionary independent of the sdoserv-files.
OBJCONST TOBJECT OBJMEM * OBJ_GetObjectHandle (UINT16 index)
The function looks in all objects of the dictionary after the indicated index and returns a handle if found.
UINT32 OBJ_GetObjectLength (UINT16 index, UINT8 subindex, OBJCONST TOBJECT OBJMEM *pObjEntry, UINT8 bCompleteAccess)
This function returns the size of the requested entry. If bCompleteaccess is set the size of the complete object is returned (the returned size is byte packed, gaps based on the used platform/compiler are not taken into account)
void OBJ_CopyNumberToString (UCHAR MBXMEM *pStr, UINT8 Number)
The function copies the Number in the string pStr, which shall be initialized with 000.
UINT16 OBJ_GetNoOfObjects (UINT8 listType)
The function counts the number of objects of the requested list type.
UINT16 OBJ_GetObjectList (UINT16 listType, UINT16 *pIndex, UINT16 size, UINT16 MBXMEM *pData, UINT8 *pAbort)
The function copies (the part of) the object list in the mailbox buffer.
UINT16 OBJ_GetDesc (UINT16 index, UINT8 subindex, OBJCONST TOBJECT OBJMEM *pObjEntry, UINT16 MBXMEM *pData)
The function returns size and description string of the requested entry.
OBJCONST TSDOINFOOBJDESC OBJMEM * OBJ_GetObjDesc (OBJCONST TOBJECT OBJMEM *pObjEntry)
The function returns the Obj-Desc of an object to allow the application to define the object dictionary independent of the sdoserv-files.
UINT16 OBJ_GetEntryOffset (UINT8 subindex, OBJCONST TOBJECT OBJMEM *pObjEntry)
This function calculates the bit offset of the entry in the object's variable.
UINT8 CheckSyncTypeValue (UINT16 index, UINT16 NewSyncType)
Checks if the new Sync type value is valid.
UINT8 OBJ_Read (UINT16 index, UINT8 subindex, UINT32 objSize, OBJCONST TOBJECT OBJMEM *pObjEntry, UINT16 MBXMEM *pData, UINT8 bCompleteAccess)
This function reads the requested object.
UINT8 OBJ_Write (UINT16 index, UINT8 subindex, UINT32 dataSize, OBJCONST TOBJECT OBJMEM *pObjEntry, UINT16 MBXMEM *pData, UINT8 bCompleteAccess)
This function writes the requested object.
PROTO void COE_WriteBackupEntry (UINT8 subindex, OBJCONST TOBJECT OBJMEM *pObjEntry)
void SdoRes (UINT8 abort, UINT8 command, UINT8 completeAccess, UINT16 dataSize, UINT32 objLength, TINITSDOMBX MBXMEM *pSdoRes)
This function is called when a SDO response shall be sent.
UINT8 SDOS_SdoInd (TINITSDOMBX MBXMEM *pSdoInd)
This function is called when a SDO request service is received from the master and calls depending from the command the concerning function.
void SDOS_SdoRes (UINT8 abort, UINT32 objLength, UINT16 MBXMEM *pData)
This function is called when a SDO response shall be sent.
void SODS_ClearPendingResponse ()
Clear the variables handling a pending SDO Response This function shall be called before the other mailbox data pointer are set to NULL.
UINT8 SDOS_SdoInfoInd (TSDOINFORMATION MBXMEM *pSdoInfoInd)
This function is called when a SDO-Info request service is received from the master and calls depending from the opcode the concerning function.
Variables
UINT32 u32Devicetype = (DEVICE_PROFILE_TYPE)
0x1000 (Device type) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1000 = {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READ}
0x1000 (Device type) entry description
OBJCONST UCHAR OBJMEM aName0x1000 [] = "Device type"
0x1000 (Device type) object name
UINT16 u16ErrorRegister = 0x0
0x1001 (Error Register) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1001 = {DEFTYPE_UNSIGNED8, 0x08, ACCESS_READ}
0x1001 (Error Register) entry description
OBJCONST UCHAR OBJMEM aName0x1001 [] = "Error register"
0x1001 (Error Register) object name
CHAR acDevicename [] = DEVICE_NAME
0x1008 (Device name) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1008 = {DEFTYPE_VISIBLESTRING, BYTE2BIT(DEVICE_NAME_LEN), ACCESS_READ}
0x1008 (Device name) entry description
OBJCONST UCHAR OBJMEM aName0x1008 [] = "Device name"
0x1008 (Device name) object name
CHAR acHardwareversion [] = DEVICE_HW_VERSION
0x1009 (Hardware version) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1009 = {DEFTYPE_VISIBLESTRING,BYTE2BIT(DEVICE_HW_VERSION_LEN), ACCESS_READ}
0x1009 (Hardware version) entry description
OBJCONST UCHAR OBJMEM aName0x1009 [] = "Hardware version"
0x1009 (Hardware version) object name
CHAR acSoftwareversion [] = DEVICE_SW_VERSION
0x100A (Software version) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x100A = {DEFTYPE_VISIBLESTRING,BYTE2BIT(DEVICE_SW_VERSION_LEN), ACCESS_READ}
0x1009 (Hardware version) entry description
OBJCONST UCHAR OBJMEM aName0x100A [] = "Software version"
0x1009 (Hardware version) object name
TOBJ1018 sIdentity = {4, (VENDOR_ID), (PRODUCT_CODE), (REVISION_NUMBER), (SERIAL_NUMBER)}
0x1018 (Identity) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x1018 []
0x1018 (Identity) entry descriptions
OBJCONST UCHAR OBJMEM aName0x1018 [] = "Identity\000Vendor ID\000Product code\000Revision\000Serial number\000\377"
0x1018 (Identity) object and entry names
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x10F1 []
0x10F1 (Error settings) entry description Subindex 000 SubIndex 001: Local Error Reaction SubIndex 002: Sync Error Counter Limit
OBJCONST UCHAR OBJMEM aName0x10F1 [] = "Error Settings\000Local Error Reaction\000Sync Error Counter Limit\000\377"
0x10F1 (Error settings) object and entry names
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x10F8 = { DEFTYPE_UNSIGNED64, 0x40, ACCESS_READWRITE | OBJACCESS_TXPDOMAPPING }
0x10F8 (Timestamp object) entry description
OBJCONST UCHAR OBJMEM aName0x10F8 [] = "Timestamp Object\000\377"
0x10F8 (Timestamp object) object name
TOBJ1C00 sSyncmanagertype = {0x04, {0x0201, 0x0403}}
0x1C00 (Sync manager type) variable to handle the object data
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x1C00 []
0x1C00 (Sync manager type) entry descriptions
OBJCONST UCHAR OBJMEM aName0x1C00 [] = "Sync manager type"
0x1C00 (Sync manager type) object name
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x1C3x []
0x1C3x (SyncManager parameter) entry description
OBJCONST UCHAR OBJMEM aName0x1C32 [] = "SM output parameter\000Synchronization Type\000Cycle Time\000\000Synchronization Types supported\000Minimum Cycle Time\000Calc and Copy Time\000\000Get Cycle Time\000Delay Time\000Sync0 Cycle Time\000SM-Event Missed\000Cycle Time Too Small\000Shift Time Too Short\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000Sync Error\000\377"
0x1C32 (SyncManager 2 parameter) object and entry names
OBJCONST UCHAR OBJMEM aName0x1C33 [] = "SM input parameter\000Synchronization Type\000Cycle Time\000\000Synchronization Types supported\000Minimum Cycle Time\000Calc and Copy Time\000\000Get Cycle Time\000Delay Time\000Sync0 Cycle Time\000SM-Event Missed\000Cycle Time Too Small\000Shift Time Too Short\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000Sync Error\000\377"
0x1C33 (SyncManager 3 parameter) object and entry names
TOBJECT OBJMEM * ObjDicList = NULL
Object dictionary pointer.
TOBJECT OBJMEM GenObjDic []
List of generic application independent objects.
PROTO UINT64 u64Timestamp
PROTO UINT32 u32LastDc32Value
PROTO UINT32 u32CheckForDcOverrunCnt
PROTO TMBX MBXMEM *VARMEM pCoeSendStored
OBJCONST TOBJECT OBJMEM * pSdoInfoObjEntry
const UINT16 cBitMask [16] = {0x0000,0x0001,0x0003,0x0007,0x000F,0x001F,0x003F,0x007F,0x00FF,0x01FF,0x03FF,0x07FF,0x0FFF,0x1FFF,0x3FFF,0x7FFF}
PROTO BOOL bSyncSetByUser
PROTO TCYCLEDIAG sCycleDiag
Cycle diagnosis variable.
PROTO TSYNCMANPAR MBXMEM sSyncManOutPar
Object 0x1C32 (SyncManager 2 Parameter) object variable.
PROTO TSYNCMANPAR MBXMEM sSyncManInPar
Object 0x1C33 (SyncManager 3 Parameter) object variable.
PROTO TOBJ10F1 sErrorSettings
Object 0x10F1 (Error Settings) object variable.
PROTO CHAR OBJMEM aSubindexDesc [13]
Default entry name "SubIndex 000".
OBJCONST TOBJECT OBJMEM asObjDef []
const UINT32 MBXMEM cAbortCode []
UINT16 VARMEM nSdoInfoIndex
OBJCONST TOBJECT OBJMEM *VARMEM pSdoInfoObjEntry
TINITSDOMBX MBXMEM *VARMEM pSdoResStored
BOOL VARMEM bSdoInWork = FALSE
UINT8 VARMEM nSdoSegService
UINT8 VARMEM bSdoSegFollows
UINT8 VARMEM bSdoSegAccess
UINT16 VARMEM nSdoSegIndex
UINT8 VARMEM nSdoSegSubindex
UINT32 VARMEM nSdoSegBytesToHandle
UINT8 VARMEM bSdoSegLastToggle
UINT32 VARMEM nSdoSegCompleteSize
OBJCONST TOBJECT OBJMEM *VARMEM pSdoSegObjEntry
PROTO MEM_ADDR VARMEM aSdoInfoHeader [GET_MEM_SIZE(SDO_INFO_HEADER_BYTE_SIZE)]
SDO Info buffer.
Detailed Description
Macro Definition Documentation
_COEAPPL_
#define _COEAPPL_ 1
Definition at line 116 of file coeappl.c.
_ECATCOE_
#define _ECATCOE_ 1
Definition at line 42 of file ecatcoe.c.
_OBJD_
#define _OBJD_
Definition at line 121 of file coeappl.c.
_OBJDEF_
#define _OBJDEF_ 1
Definition at line 130 of file objdef.c.
_SDOSERV_
#define _SDOSERV_ 1
Definition at line 113 of file sdoserv.c.
CHECK_DC_OVERRUN_IN_MS
#define CHECK_DC_OVERRUN_IN_MS 4000
cycle time in ms to check the DC system time for overrun
Definition at line 77 of file coeappl.h.
COE_HEADER_SIZE
#define COE_HEADER_SIZE 2
CoE header size.
Definition at line 67 of file ecatcoe.h.
COEHEADER_COESERVICEMASK
#define COEHEADER_COESERVICEMASK 0xF000
CoE service mask (within CoE header)
Definition at line 65 of file ecatcoe.h.
COEHEADER_COESERVICESHIFT
#define COEHEADER_COESERVICESHIFT 12
CoE service shift (within CoE header)
Definition at line 64 of file ecatcoe.h.
COESERVICE_EMERGENCY
#define COESERVICE_EMERGENCY 0x01
CoE Emergency.
Definition at line 50 of file ecatcoe.h.
COESERVICE_RXPDO
#define COESERVICE_RXPDO 0x05
CoE RxPDO.
Definition at line 54 of file ecatcoe.h.
COESERVICE_RXPDOREMREQ
#define COESERVICE_RXPDOREMREQ 0x07
CoE RxPDO map request.
Definition at line 56 of file ecatcoe.h.
COESERVICE_SDOINFO
#define COESERVICE_SDOINFO 0x08
CoE SDO Info.
Definition at line 57 of file ecatcoe.h.
COESERVICE_SDOREQUEST
#define COESERVICE_SDOREQUEST 0x02
CoE SDO request.
Definition at line 51 of file ecatcoe.h.
COESERVICE_SDORESPONSE
#define COESERVICE_SDORESPONSE 0x03
CoE SDO response.
Definition at line 52 of file ecatcoe.h.
COESERVICE_TXPDO
#define COESERVICE_TXPDO 0x04
CoE TxPDO.
Definition at line 53 of file ecatcoe.h.
COESERVICE_TXPDOREMREQ
#define COESERVICE_TXPDOREMREQ 0x06
CoE TxPDO map request.
Definition at line 55 of file ecatcoe.h.
DEFTYPE_ARRAY_OF_DINT
#define DEFTYPE_ARRAY_OF_DINT 0x0262
DEFTYPE_ARRAY_OF_DINT.
Definition at line 111 of file objdef.h.
DEFTYPE_ARRAY_OF_INT
#define DEFTYPE_ARRAY_OF_INT 0x0260
DEFTYPE_ARRAY_OF_INT.
Definition at line 109 of file objdef.h.
DEFTYPE_ARRAY_OF_SINT
#define DEFTYPE_ARRAY_OF_SINT 0x0261
DEFTYPE_ARRAY_OF_SINT.
Definition at line 110 of file objdef.h.
DEFTYPE_ARRAY_OF_UDINT
#define DEFTYPE_ARRAY_OF_UDINT 0x0263
DEFTYPE_ARRAY_OF_UDINT.
Definition at line 112 of file objdef.h.
DEFTYPE_BACKUP
#define DEFTYPE_BACKUP 0x002B
BACKUP_PARAMETER.
Definition at line 96 of file objdef.h.
DEFTYPE_BIT1
#define DEFTYPE_BIT1 0x0030
BIT1.
Definition at line 101 of file objdef.h.
DEFTYPE_BIT2
#define DEFTYPE_BIT2 0x0031
BIT2.
Definition at line 102 of file objdef.h.
DEFTYPE_BIT3
#define DEFTYPE_BIT3 0x0032
BIT3.
Definition at line 103 of file objdef.h.
DEFTYPE_BIT4
#define DEFTYPE_BIT4 0x0033
BIT4.
Definition at line 104 of file objdef.h.
DEFTYPE_BIT5
#define DEFTYPE_BIT5 0x0034
BIT5.
Definition at line 105 of file objdef.h.
DEFTYPE_BIT6
#define DEFTYPE_BIT6 0x0035
BIT6.
Definition at line 106 of file objdef.h.
DEFTYPE_BIT7
#define DEFTYPE_BIT7 0x0036
BIT7.
Definition at line 107 of file objdef.h.
DEFTYPE_BIT8
#define DEFTYPE_BIT8 0x0037
BIT8.
Definition at line 108 of file objdef.h.
DEFTYPE_BITARR16
#define DEFTYPE_BITARR16 0x002E
BITARR16.
Definition at line 99 of file objdef.h.
DEFTYPE_BITARR32
#define DEFTYPE_BITARR32 0x002F
BITARR32.
Definition at line 100 of file objdef.h.
DEFTYPE_BITARR8
#define DEFTYPE_BITARR8 0x002D
BITARR8.
Definition at line 98 of file objdef.h.
DEFTYPE_BOOLEAN
#define DEFTYPE_BOOLEAN 0x0001
BOOLEAN.
Definition at line 56 of file objdef.h.
DEFTYPE_BYTE
#define DEFTYPE_BYTE 0x001E
DEFTYPE_BYTE.
Definition at line 86 of file objdef.h.
DEFTYPE_COMMAND
#define DEFTYPE_COMMAND 0x0025
COMMAND_PAR.
Definition at line 91 of file objdef.h.
DEFTYPE_DIAGHISTORY
#define DEFTYPE_DIAGHISTORY 0x0282
DEFTYPE_DIAGHISTORY.
Definition at line 114 of file objdef.h.
DEFTYPE_DWORD
#define DEFTYPE_DWORD 0x0020
DEFTYPE_DWORD.
Definition at line 88 of file objdef.h.
DEFTYPE_ENUM
#define DEFTYPE_ENUM 0x0028
DEFTYPE_ENUM.
Definition at line 93 of file objdef.h.
DEFTYPE_ERRORHANDLING
#define DEFTYPE_ERRORHANDLING 0x0281
DEFTYPE_ERRORHANDLING.
Definition at line 113 of file objdef.h.
DEFTYPE_FSOECOMMPAR
#define DEFTYPE_FSOECOMMPAR 0x0286
DEFTYPE_FSOECOMMPAR.
Definition at line 118 of file objdef.h.
DEFTYPE_FSOEFRAME
#define DEFTYPE_FSOEFRAME 0x0285
DEFTYPE_FSOEFRAME.
Definition at line 117 of file objdef.h.
DEFTYPE_GUID
#define DEFTYPE_GUID 0x001D
DEFTYPE_GUID.
Definition at line 85 of file objdef.h.
DEFTYPE_IDENTITY
#define DEFTYPE_IDENTITY 0x0023
IDENTITY.
Definition at line 90 of file objdef.h.
DEFTYPE_INTEGER16
#define DEFTYPE_INTEGER16 0x0003
INTEGER16.
Definition at line 58 of file objdef.h.
DEFTYPE_INTEGER24 [1/2]
#define DEFTYPE_INTEGER24 0x0010
INTEGER24.
Definition at line 74 of file objdef.h.
DEFTYPE_INTEGER24 [2/2]
#define DEFTYPE_INTEGER24 0x0010
INTEGER24.
Definition at line 74 of file objdef.h.
DEFTYPE_INTEGER32
#define DEFTYPE_INTEGER32 0x0004
INTEGER32.
Definition at line 60 of file objdef.h.
DEFTYPE_INTEGER40 [1/2]
#define DEFTYPE_INTEGER40 0x0012
INTEGER40.
Definition at line 76 of file objdef.h.
DEFTYPE_INTEGER40 [2/2]
#define DEFTYPE_INTEGER40 0x0012
INTEGER40.
Definition at line 76 of file objdef.h.
DEFTYPE_INTEGER48 [1/2]
#define DEFTYPE_INTEGER48 0x0013
INTEGER48.
Definition at line 77 of file objdef.h.
DEFTYPE_INTEGER48 [2/2]
#define DEFTYPE_INTEGER48 0x0013
INTEGER48.
Definition at line 77 of file objdef.h.
DEFTYPE_INTEGER56 [1/2]
#define DEFTYPE_INTEGER56 0x0014
INTEGER56.
Definition at line 78 of file objdef.h.
DEFTYPE_INTEGER56 [2/2]
#define DEFTYPE_INTEGER56 0x0014
INTEGER56.
Definition at line 78 of file objdef.h.
DEFTYPE_INTEGER64
#define DEFTYPE_INTEGER64 0x0015
INTEGER64.
Definition at line 79 of file objdef.h.
DEFTYPE_INTEGER8
#define DEFTYPE_INTEGER8 0x0002
INTEGER8.
Definition at line 57 of file objdef.h.
DEFTYPE_MDP
#define DEFTYPE_MDP 0x002C
MODULAR_DEVICE_PROFILE.
Definition at line 97 of file objdef.h.
DEFTYPE_NULL
#define DEFTYPE_NULL 0x0000
Null.
Definition at line 55 of file objdef.h.
DEFTYPE_OCTETSTRING
#define DEFTYPE_OCTETSTRING 0x000A
OCTET_STRING.
Definition at line 70 of file objdef.h.
DEFTYPE_PDOCOMPAR
#define DEFTYPE_PDOCOMPAR 0x0027
PDO_PARAMETER.
Definition at line 92 of file objdef.h.
DEFTYPE_PDOMAPPING
#define DEFTYPE_PDOMAPPING 0x0021
PDO_MAPPING.
Definition at line 89 of file objdef.h.
DEFTYPE_REAL32
#define DEFTYPE_REAL32 0x0008
REAL32.
Definition at line 68 of file objdef.h.
DEFTYPE_REAL64
#define DEFTYPE_REAL64 0x0011
REAL64.
Definition at line 75 of file objdef.h.
DEFTYPE_RECORD
#define DEFTYPE_RECORD 0x002A
DEFTYPE_RECORD.
Definition at line 95 of file objdef.h.
DEFTYPE_SMPAR
#define DEFTYPE_SMPAR 0x0029
SM_SYNCHRONISATION.
Definition at line 94 of file objdef.h.
DEFTYPE_SYNCSETTINGS
#define DEFTYPE_SYNCSETTINGS 0x0284
DEFTYPE_SYNCSETTINGS.
Definition at line 116 of file objdef.h.
DEFTYPE_SYNCSTATUS
#define DEFTYPE_SYNCSTATUS 0x0283
DEFTYPE_SYNCSTATUS.
Definition at line 115 of file objdef.h.
DEFTYPE_TIME_DIFFERENCE
#define DEFTYPE_TIME_DIFFERENCE 0x000D
TIME_DIFFERENCE.
Definition at line 73 of file objdef.h.
DEFTYPE_TIME_OF_DAY
#define DEFTYPE_TIME_OF_DAY 0x000C
TIME_OF_DAY.
Definition at line 72 of file objdef.h.
DEFTYPE_UNICODE_STRING
#define DEFTYPE_UNICODE_STRING 0x000B
UNICODE_STRING.
Definition at line 71 of file objdef.h.
DEFTYPE_UNSIGNED16
#define DEFTYPE_UNSIGNED16 0x0006
UNSIGNED16.
Definition at line 65 of file objdef.h.
DEFTYPE_UNSIGNED24 [1/2]
#define DEFTYPE_UNSIGNED24 0x0016
UNSIGNED24.
Definition at line 80 of file objdef.h.
DEFTYPE_UNSIGNED24 [2/2]
#define DEFTYPE_UNSIGNED24 0x0016
UNSIGNED24.
Definition at line 80 of file objdef.h.
DEFTYPE_UNSIGNED32
#define DEFTYPE_UNSIGNED32 0x0007
UNSIGNED32.
Definition at line 67 of file objdef.h.
DEFTYPE_UNSIGNED40
#define DEFTYPE_UNSIGNED40 0x0018
UNSIGNED40.
Definition at line 81 of file objdef.h.
DEFTYPE_UNSIGNED48
#define DEFTYPE_UNSIGNED48 0x0019
UNSIGNED48.
Definition at line 82 of file objdef.h.
DEFTYPE_UNSIGNED56
#define DEFTYPE_UNSIGNED56 0x001A
UNSIGNED56.
Definition at line 83 of file objdef.h.
DEFTYPE_UNSIGNED64
#define DEFTYPE_UNSIGNED64 0x001B
UNSIGNED64.
Definition at line 84 of file objdef.h.
DEFTYPE_UNSIGNED8
#define DEFTYPE_UNSIGNED8 0x0005
UNSIGNED8.
Definition at line 64 of file objdef.h.
DEFTYPE_VISIBLESTRING
#define DEFTYPE_VISIBLESTRING 0x0009
VISIBLE_STRING.
Definition at line 69 of file objdef.h.
DEFTYPE_WORD
#define DEFTYPE_WORD 0x001F
DEFTYPE_WORD.
Definition at line 87 of file objdef.h.
ECATCOE
#define ECATCOE 0x4300
Definition at line 56 of file ecatcoe.c.
ECATCOEMAX
#define ECATCOEMAX 0x02
Definition at line 57 of file ecatcoe.c.
ERROR_COEINVALIDSERVICE
#define ERROR_COEINVALIDSERVICE 0x01
Invalid SDO service.
Definition at line 43 of file ecatcoe.h.
ERROR_COENOTSUPPORTED
#define ERROR_COENOTSUPPORTED 0x02
Not supported service.
Definition at line 44 of file ecatcoe.h.
IS_PDO_ASSIGN
#define IS_PDO_ASSIGN (x) ((x >= 0x1C10) && (x <= 0x1C2F))
Marco to check if object index is SyncManager assign object.
Definition at line 137 of file objdef.h.
IS_RX_PDO
#define IS_RX_PDO (x) (((x) >= 0x1600) && ((x) <= 0x17FF))
Marco to check if object index RxPDO mapping object.
Definition at line 138 of file objdef.h.
IS_TX_PDO
#define IS_TX_PDO (x) (((x) >= 0x1A00) && ((x) <= 0x1BFF))
Marco to check if object index TxPDO mapping object.
Definition at line 139 of file objdef.h.
OBJDEF
#define OBJDEF 0x4000
Definition at line 114 of file objdef.c.
OBJDEFMAX
#define OBJDEFMAX 0x0A
Definition at line 115 of file objdef.c.
PROTO [1/4]
#define PROTO extern
Definition at line 84 of file coeappl.h.
PROTO [2/4]
#define PROTO extern
Definition at line 89 of file ecatcoe.h.
PROTO [3/4]
#define PROTO extern
Definition at line 221 of file objdef.h.
PROTO [4/4]
#define PROTO extern
Definition at line 608 of file sdoserv.h.
SYNCTYPE_DCSYNC0SUPP
#define SYNCTYPE_DCSYNC0SUPP 0x0004
Sync0 synchron supported.
Definition at line 127 of file objdef.h.
SYNCTYPE_DCSYNC1SUPP
#define SYNCTYPE_DCSYNC1SUPP 0x0008
Sync1 synchron supported.
Definition at line 128 of file objdef.h.
SYNCTYPE_FIXED_DELAYSUPP
#define SYNCTYPE_FIXED_DELAYSUPP 0x0400
Delay times are fixed.
Definition at line 133 of file objdef.h.
SYNCTYPE_FREERUNSUPP
#define SYNCTYPE_FREERUNSUPP 0x0001
FreeRun supported.
Definition at line 125 of file objdef.h.
SYNCTYPE_LOCALSHIFTSUPP
#define SYNCTYPE_LOCALSHIFTSUPP 0x0020
Event shift with local timer supported. Output shift : 0x1C32.4 ; Input shift : 0x1C33.4 (not supported by the default SSC)
Definition at line 130 of file objdef.h.
SYNCTYPE_MEASURE_DELAYSUPP
#define SYNCTYPE_MEASURE_DELAYSUPP 0x0200
Delay times should be measured (not supported by the default SSC, only the cycle time can be measured (1ms resolution)
Definition at line 132 of file objdef.h.
SYNCTYPE_SHIFTBYSYNC1SUPP
#define SYNCTYPE_SHIFTBYSYNC1SUPP 0x0040
Event shift with Sync1 event supported. Output shift : 0x1C32.4 ; Input shift : 0x1C33.4.
Definition at line 131 of file objdef.h.
SYNCTYPE_SUBCYCLESUPP
#define SYNCTYPE_SUBCYCLESUPP 0x0010
Subordinated Application with fixed Sync0 supported.
Definition at line 129 of file objdef.h.
SYNCTYPE_SYNCHRONSUPP
#define SYNCTYPE_SYNCHRONSUPP 0x0002
SyncManager synchron supported.
Definition at line 126 of file objdef.h.
SYNCTYPE_TIMESVARIABLE
#define SYNCTYPE_TIMESVARIABLE 0x4000
Dynamic Cycle Times supported.
Definition at line 134 of file objdef.h.
Typedef Documentation
TCOEHEADER
typedef UINT16 TCOEHEADER
CoE header.
Definition at line 69 of file ecatcoe.h.
TCYCLEDIAG
typedef struct OBJ_STRUCT_PACKED_START TCYCLEDIAG
Cycle diagnosis
TOBJ10F1
typedef struct OBJ_STRUCT_PACKED_START TOBJ10F1
Object 0x10F1 (Error Settings Object) data structure
TSYNCMANPAR
typedef struct OBJ_STRUCT_PACKED_START TSYNCMANPAR
Object 0x1C3x (SyncManager Parameter) data structure
Function Documentation
AddObjectsToObjDictionary()
UINT16 AddObjectsToObjDictionary (TOBJECT OBJMEM * pObjEntry)
Definition at line 843 of file coeappl.c.
CheckSyncTypeValue()
PROTO UINT8 CheckSyncTypeValue (UINT16 index, UINT16 NewSyncType)
Checks if the new Sync type value is valid.
Parameters
index index of the SyncManager Parameter object
NewSyncType New value for the Sync Type (SubIndex 1)
Returns
result Result of the value validation
Definition at line 765 of file objdef.c.
References ABORTIDX_VALUE_EXCEEDED, nPdInputSize, nPdOutputSize, sSyncManInPar, sSyncManOutPar, SYNCTYPE_DCSYNC0, SYNCTYPE_DCSYNC0SUPP, SYNCTYPE_DCSYNC1, SYNCTYPE_DCSYNC1SUPP, SYNCTYPE_FREERUN, SYNCTYPE_SM2_SYNCHRON, SYNCTYPE_SM_SYNCHRON, SYNCTYPE_SYNCHRONSUPP, and OBJ_STRUCT_PACKED_START::u16SyncTypesSupported.
Referenced by OBJ_Write().
COE_AddObjectToDic()
PROTO UINT16 COE_AddObjectToDic (TOBJECT OBJMEM * pNewObjEntry)
This function adds an object to the object dictionary.
Returns
0 object successful added to object dictionary ALSTATUSCODE_XX add object failed
Definition at line 722 of file coeappl.c.
References ALSTATUSCODE_UNSPECIFIEDERROR, OBJ_ENTRY::Index, ObjDicList, OBJ_ENTRY::pNext, and OBJ_ENTRY::pPrev.
Referenced by APPL_GenerateMapping().
COE_ClearObjDictionary()
PROTO void COE_ClearObjDictionary (void)
This function clear the object dictionary.
Definition at line 827 of file coeappl.c.
References COE_RemoveDicEntry(), and ObjDicList.
Referenced by COE_ObjInit().
COE_ContinueInd()
PROTO UINT8 COE_ContinueInd (TMBX MBXMEM * pMbx)
This function is called when a CoE service to be sent is stored and can.
Parameters
pMbx Pointer to the free mailbox to sent.
Returns
result of the operation (0 (success)
be put in the send mailbox.
Definition at line 147 of file ecatcoe.c.
References aSdoInfoHeader, MBX_MailboxSendReq(), MBXERR_NOMOREMEMORY, SDO_INFO_HEADER_BYTE_SIZE, and SDOS_SdoInfoInd().
Referenced by MBX_MailboxReadInd().
COE_GetObjectDictionary()
PROTO OBJCONST TOBJECT OBJMEM * COE_GetObjectDictionary (void)
returns the pointer to the object dictionary
Definition at line 535 of file coeappl.c.
References ObjDicList.
Referenced by OBJ_GetNoOfObjects(), OBJ_GetObjectHandle(), and OBJ_GetObjectList().
COE_Init()
PROTO void COE_Init (void)
This function intialize the CoE Interface.
if the mailbox service could not be sent (or stored), the CoE service will be stored in this variable and will be sent automatically from the mailbox handler (COE_ContinueInd) when the send mailbox will be read the next time from the master
Definition at line 83 of file ecatcoe.c.
References nSdoInfoFragmentsLeft.
Referenced by ECAT_Init().
COE_Main()
PROTO void COE_Main (void)
is called for background calculations which should not influence the ECAT_Application in synchronous modes
Definition at line 902 of file coeappl.c.
References ABORTIDX_WORKING, bStoreCompleteAccess, pSdoPendFunc, pSdoSegData, pStoreData, SDO_PENDING_READ, SDO_PENDING_SEG_READ, SDO_PENDING_SEG_WRITE, SDO_PENDING_WRITE, SDOS_SdoRes(), u16StoreIndex, u32StoreDataSize, u8PendingSdo, and u8StoreSubindex.
Referenced by MainLoop().
COE_ObjDictionaryInit()
PROTO UINT16 COE_ObjDictionaryInit (void)
This function initialize the object dictionary.
Returns
0 object dictionary created successful ALSTATUSCODE_XX create object dictionary failed
Definition at line 870 of file coeappl.c.
References GenObjDic, and ObjDicList.
Referenced by COE_ObjInit().
COE_ObjInit()
PROTO void COE_ObjInit (void)
This function initialize the several objects.
Definition at line 575 of file coeappl.c.
References bStoreCompleteAccess, bSyncSetByUser, CHECK_DC_OVERRUN_IN_MS, COE_ClearObjDictionary(), COE_ObjDictionaryInit(), ESC_DC_32BIT_MASK, ESC_FEATURES_OFFSET, ESC_SYSTEMTIME_OFFSET, pSdoPendFunc, pSdoSegData, pStoreData, sSyncManInPar, sSyncManOutPar, OBJ_STRUCT_PACKED_START::subindex0, SWAPDWORD, SYNCTYPE_DCSYNC0SUPP, SYNCTYPE_DCSYNC1SUPP, SYNCTYPE_FREERUN, SYNCTYPE_FREERUNSUPP, SYNCTYPE_SUBCYCLESUPP, SYNCTYPE_SYNCHRONSUPP, SYNCTYPE_TIMESVARIABLE, OBJ_STRUCT_PACKED_START::u16CycleExceededCounter, OBJ_STRUCT_PACKED_START::u16GetCycleTime, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, u16StoreIndex, OBJ_STRUCT_PACKED_START::u16SyncType, OBJ_STRUCT_PACKED_START::u16SyncTypesSupported, OBJ_STRUCT_PACKED_START::u32CalcAndCopyTime, OBJ_STRUCT_PACKED_START::u32CycleTime, OBJ_STRUCT_PACKED_START::u32DelayTime, OBJ_STRUCT_PACKED_START::u32MinCycleTime, u32StoreDataSize, u8PendingSdo, u8StoreSubindex, and OBJ_STRUCT_PACKED_START::u8SyncError.
Referenced by MainInit().
COE_RemoveDicEntry()
PROTO void COE_RemoveDicEntry (UINT16 index)
This function removes an object to the object dictionary.
Definition at line 788 of file coeappl.c.
References OBJ_ENTRY::Index, ObjDicList, and OBJ_ENTRY::pNext.
Referenced by APPL_GenerateMapping(), CiA402_DeallocateAxis(), and COE_ClearObjDictionary().
COE_ServiceInd()
PROTO UINT8 COE_ServiceInd (TCOEMBX MBXMEM * pCoeMbx)
This function is called when a CoE (CAN application layer over EtherCAT) service is received from the master.
Parameters
pCoeMbx Pointer to the received mailbox data from the master.
Returns
result of the operation (0 (success) or mailbox error code (MBXERR_.... defined in mailbox.h))
Definition at line 100 of file ecatcoe.c.
References COEHEADER_COESERVICEMASK, COEHEADER_COESERVICESHIFT, COESERVICE_EMERGENCY, COESERVICE_RXPDO, COESERVICE_RXPDOREMREQ, COESERVICE_SDOINFO, COESERVICE_SDOREQUEST, COESERVICE_SDORESPONSE, COESERVICE_TXPDO, COESERVICE_TXPDOREMREQ, MBXERR_INVALIDHEADER, MBXERR_SERVICENOTSUPPORTED, SDOS_SdoInd(), and SDOS_SdoInfoInd().
Referenced by MailboxServiceInd().
COE_SyncTimeStamp()
PROTO void COE_SyncTimeStamp (void)
This function updates the local timestamp object (0x10F8) and has to be called at least every 4.2sec to detect an 32Bit DC unit overrun. Called from the Timer handler.
Definition at line 360 of file coeappl.c.
References ESC_SYSTEMTIME_OFFSET.
Referenced by MainLoop(), and Read0x10F8().
COE_UpdateSyncErrorStatus()
PROTO void COE_UpdateSyncErrorStatus (void)
Update the Sync Error Indication.
Definition at line 546 of file coeappl.c.
References sErrorSettings, sSyncManInPar, sSyncManOutPar, OBJ_STRUCT_PACKED_START::u16CycleExceededCounter, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, OBJ_STRUCT_PACKED_START::u16SyncErrorCounterLimit, and OBJ_STRUCT_PACKED_START::u8SyncError.
OBJ_CopyNumberToString()
void OBJ_CopyNumberToString (UCHAR MBXMEM * pStr, UINT8 Number)
The function copies the Number in the string pStr, which shall be initialized with 000.
Parameters
pStr Pointer to a string
Number Number to be included in the string
Definition at line 317 of file objdef.c.
Referenced by OBJ_GetDesc().
OBJ_GetDesc()
UINT16 OBJ_GetDesc (UINT16 index, UINT8 subindex, OBJCONST TOBJECT OBJMEM * pObjEntry, UINT16 MBXMEM * pData)
The function returns size and description string of the requested entry.
Parameters
index Indicates the index of the dictionary object.
subindex Indicates the subindex of the dictionary object. Subindex 0xff returns the description of the whole object (the name of the object). Subindex 0x00 returns the description of the subindex 0 and so on.
pObjEntry Is a handle to the dictionary object (for faster access) or NULL.
pData Is the memory field for the description string or NULL (if the size of string is unknown):
Returns
The size in bytes of the description string (without null termination byte). 0 will be returned if a description for the indicated entry was not found.
       Its possible to define all description strings of one entry ( including the name
       of the object ) in one structure:        <br>
       {                                                    <br>
           name_of_object with index,              <br>
           description_of_subindex0,                <br>
           .                                                <br>
           description_of_subindexN,                <br>
           0xFF                                            <br>
       }
Definition at line 505 of file objdef.c.
References aSubindexDesc, OBJ_CopyNumberToString(), OBJCODE_REC, OBJCODE_VAR, OBJFLAGS_OBJCODEMASK, OBJFLAGS_OBJCODESHIFT, and OBJGETNEXTSTR.
Referenced by SDOS_SdoInfoInd().
OBJ_GetEntryDesc()
OBJCONST TSDOINFOENTRYDESC OBJMEM * OBJ_GetEntryDesc (OBJCONST TOBJECT OBJMEM * pObjEntry, UINT8 Subindex)
The function returns the Entry-Desc of a subindex to allow the application to define the object dictionary independent of the sdoserv-files.
Parameters
pObjEntry handle to the dictionary object returned by OBJ_GetObjectHandle which was called before
Subindex subindex of the requested object.
Returns
Pointer to the EntryDesc of the Subindex
Definition at line 594 of file objdef.c.
References OBJCODE_ARR, OBJFLAGS_OBJCODEMASK, and OBJFLAGS_OBJCODESHIFT.
Referenced by OBJ_GetNoOfObjects(), OBJ_GetObjectList(), OBJ_Read(), OBJ_Write(), and SDOS_SdoInfoInd().
OBJ_GetEntryOffset()
PROTO UINT16 OBJ_GetEntryOffset (UINT8 subindex, OBJCONST TOBJECT OBJMEM * pObjEntry)
This function calculates the bit offset of the entry in the object's variable.
Parameters
subindex subindex of the entry
pObjEntry handle to the dictionary object returned by OBJ_GetObjectHandle which was called before
Returns
bit offset of the entry in the variable
Definition at line 653 of file objdef.c.
References DEFTYPE_ARRAY_OF_DINT, DEFTYPE_ARRAY_OF_INT, DEFTYPE_ARRAY_OF_UDINT, DEFTYPE_BITARR16, DEFTYPE_BITARR32, DEFTYPE_DWORD, DEFTYPE_INTEGER16, DEFTYPE_INTEGER32, DEFTYPE_REAL32, DEFTYPE_UNICODE_STRING, DEFTYPE_UNSIGNED16, DEFTYPE_UNSIGNED32, DEFTYPE_WORD, OBJCODE_ARR, OBJCODE_VAR, OBJFLAGS_OBJCODEMASK, and OBJFLAGS_OBJCODESHIFT.
Referenced by OBJ_Read(), and OBJ_Write().
OBJ_GetNoOfObjects()
PROTO UINT16 OBJ_GetNoOfObjects (UINT8 listType)
The function counts the number of objects of the requested list type.
Parameters
listType requested listType (0=all objects, 1=RxPDO mappable objects, 2=TxPDO mappable objects, 3=backup objects, 4=setting objects)
Returns
Number of objects of the requested list type
Definition at line 339 of file objdef.c.
References COE_GetObjectDictionary(), OBJ_GetEntryDesc(), OBJFLAGS_MAXSUBINDEXMASK, and OBJFLAGS_MAXSUBINDEXSHIFT.
Referenced by SDOS_SdoInfoInd().
OBJ_GetObjDesc()
OBJCONST TSDOINFOOBJDESC OBJMEM * OBJ_GetObjDesc (OBJCONST TOBJECT OBJMEM * pObjEntry)
The function returns the Obj-Desc of an object to allow the application to define the object dictionary independent of the sdoserv-files.
Parameters
pObjEntry handle to the dictionary object returned by OBJ_GetObjectHandle which was called before
Returns
Pointer to the ObjDesc of the Object
Definition at line 637 of file objdef.c.
Referenced by SDOS_SdoInfoInd().
OBJ_GetObjectHandle()
PROTO OBJCONST TOBJECT OBJMEM * OBJ_GetObjectHandle (UINT16 index)
The function looks in all objects of the dictionary after the indicated index and returns a handle if found.
Parameters
index Indicates the index of the dictionary object.
Returns
A handle to an object of the requested index or NULL if not found.
Definition at line 181 of file objdef.c.
References COE_GetObjectDictionary(), and OBJ_ENTRY::pNext.
Referenced by SDOS_SdoInd(), and SDOS_SdoInfoInd().
OBJ_GetObjectLength()
PROTO UINT32 OBJ_GetObjectLength (UINT16 index, UINT8 subindex, OBJCONST TOBJECT OBJMEM * pObjEntry, UINT8 bCompleteAccess)
This function returns the size of the requested entry. If bCompleteaccess is set the size of the complete object is returned (the returned size is byte packed, gaps based on the used platform/compiler are not taken into account)
Parameters
index Index of the requested object.
subindex Subindex of the requested object.
pObjEntry Handle to the dictionary object returned by OBJ_GetObjectHandle which was called before
bCompleteAccess Indicates if a complete read of all subindices of the object shall be done or not
Returns
The size of the object entry in bytes (!).
Definition at line 211 of file objdef.c.
References BIT2BYTE, OBJCODE_ARR, OBJCODE_VAR, OBJFLAGS_MAXSUBINDEXMASK, OBJFLAGS_MAXSUBINDEXSHIFT, OBJFLAGS_OBJCODEMASK, and OBJFLAGS_OBJCODESHIFT.
Referenced by SDOS_SdoInd().
OBJ_GetObjectList()
PROTO UINT16 OBJ_GetObjectList (UINT16 listType, UINT16 * pIndex, UINT16 size, UINT16 MBXMEM * pData, UINT8 * pAbort)
The function copies (the part of) the object list in the mailbox buffer.
Parameters
listType Requested listType (0=all objects, 1=RxPDO mappable objects, 2=TxPDO mappable objects, 3=backup objects, 4=setting objects)
pIndex Pointer to the next Index of the object list to copied in the mailbox buffer, has to adapted at the end of the function
size Size of the available mailbox buffer
pData Pointer to the mailbox buffer where (the part of) the object list requested listType (0=all objects, 1=RxPDO mappable objects,
pAbort Pointer to abortCode
Returns
Size of the available mailbox buffer which was not copied to
Definition at line 400 of file objdef.c.
References ABORTIDX_NO_OBJECT_DICTIONARY_IS_PRESENT, COE_GetObjectDictionary(), OBJ_GetEntryDesc(), MBX_STRUCT_PACKED_START::ObjAccess, OBJFLAGS_MAXSUBINDEXMASK, OBJFLAGS_MAXSUBINDEXSHIFT, and SWAPWORD.
Referenced by SDOS_SdoInfoInd().
OBJ_Read()
PROTO UINT8 OBJ_Read (UINT16 index, UINT8 subindex, UINT32 objSize, OBJCONST TOBJECT OBJMEM * pObjEntry, UINT16 MBXMEM * pData, UINT8 bCompleteAccess)
This function reads the requested object.
Parameters
index index of the requested object.
subindex subindex of the requested object.
objSize Size of the object, returned by the function OBJ_GetObjectLength which was called before
pObjEntry handle to the dictionary object returned by OBJ_GetObjectHandle which was called before
pData Pointer to the buffer where the read data shall be copied to
bCompleteAccess Indicates if a complete read of all subindices of the object shall be done or not
Returns
result of the read operation (0 (success) or an abort code (ABORTIDX_.... defined in sdosrv.h))
Definition at line 847 of file objdef.c.
References ABORTIDX_DATA_CANNOT_BE_READ_OR_STORED, ABORTIDX_IN_THIS_STATE_DATA_CANNOT_BE_READ_OR_STORED, ABORTIDX_SUBINDEX_NOT_EXISTING, ABORTIDX_UNSUPPORTED_ACCESS, ABORTIDX_WRITE_ONLY_ENTRY, ACCESS_READ, BIT2BYTE, BIT2WORD, DEFTYPE_ARRAY_OF_DINT, DEFTYPE_ARRAY_OF_INT, DEFTYPE_ARRAY_OF_SINT, DEFTYPE_ARRAY_OF_UDINT, DEFTYPE_BIT1, DEFTYPE_BIT2, DEFTYPE_BIT3, DEFTYPE_BIT4, DEFTYPE_BIT5, DEFTYPE_BIT6, DEFTYPE_BIT7, DEFTYPE_BIT8, DEFTYPE_BITARR16, DEFTYPE_BITARR32, DEFTYPE_BITARR8, DEFTYPE_BOOLEAN, DEFTYPE_BYTE, DEFTYPE_DWORD, DEFTYPE_INTEGER16, DEFTYPE_INTEGER32, DEFTYPE_INTEGER64, DEFTYPE_INTEGER8, DEFTYPE_NULL, DEFTYPE_OCTETSTRING, DEFTYPE_REAL32, DEFTYPE_REAL64, DEFTYPE_UNICODE_STRING, DEFTYPE_UNSIGNED16, DEFTYPE_UNSIGNED32, DEFTYPE_UNSIGNED64, DEFTYPE_UNSIGNED8, DEFTYPE_VISIBLESTRING, DEFTYPE_WORD, nAlStatus, OBJ_GetEntryDesc(), OBJ_GetEntryOffset(), OBJCODE_VAR, OBJFLAGS_MAXSUBINDEXMASK, OBJFLAGS_MAXSUBINDEXSHIFT, OBJFLAGS_OBJCODEMASK, OBJFLAGS_OBJCODESHIFT, STATE_MASK, and SWAPWORD.
Referenced by SDOS_SdoInd().
OBJ_Write()
PROTO UINT8 OBJ_Write (UINT16 index, UINT8 subindex, UINT32 dataSize, OBJCONST TOBJECT OBJMEM * pObjEntry, UINT16 MBXMEM * pData, UINT8 bCompleteAccess)
This function writes the requested object.
Parameters
index index of the requested object.
subindex subindex of the requested object.
dataSize received data size of the SDO Download
pObjEntry handle to the dictionary object returned by OBJ_GetObjectHandle which was called before
pData Pointer to the buffer where the written data can be copied from
bCompleteAccess Indicates if a complete write of all subindices of the object shall be done or not
Returns
result of the write operation (0 (success) or an abort code (ABORTIDX_.... defined in sdosrv.h))
Definition at line 1301 of file objdef.c.
References ABORTIDX_DATA_CANNOT_BE_READ_OR_STORED, ABORTIDX_ENTRY_CANT_BE_WRITTEN_SI0_NOT_0, ABORTIDX_IN_THIS_STATE_DATA_CANNOT_BE_READ_OR_STORED, ABORTIDX_READ_ONLY_ENTRY, ABORTIDX_SUBINDEX_NOT_EXISTING, ABORTIDX_UNSUPPORTED_ACCESS, ABORTIDX_VALUE_EXCEEDED, ABORTIDX_VALUE_TOO_GREAT, ACCESS_WRITE, BIT2BYTE, BIT2WORD, bSyncSetByUser, CheckSyncTypeValue(), DEFTYPE_ARRAY_OF_DINT, DEFTYPE_ARRAY_OF_INT, DEFTYPE_ARRAY_OF_SINT, DEFTYPE_ARRAY_OF_UDINT, DEFTYPE_BIT1, DEFTYPE_BIT2, DEFTYPE_BIT3, DEFTYPE_BIT4, DEFTYPE_BIT5, DEFTYPE_BIT6, DEFTYPE_BIT7, DEFTYPE_BIT8, DEFTYPE_BITARR16, DEFTYPE_BITARR32, DEFTYPE_BITARR8, DEFTYPE_BOOLEAN, DEFTYPE_BYTE, DEFTYPE_DWORD, DEFTYPE_INTEGER16, DEFTYPE_INTEGER32, DEFTYPE_INTEGER64, DEFTYPE_INTEGER8, DEFTYPE_NULL, DEFTYPE_OCTETSTRING, DEFTYPE_REAL32, DEFTYPE_REAL64, DEFTYPE_UNICODE_STRING, DEFTYPE_UNSIGNED16, DEFTYPE_UNSIGNED32, DEFTYPE_UNSIGNED64, DEFTYPE_UNSIGNED8, DEFTYPE_VISIBLESTRING, DEFTYPE_WORD, IS_PDO_ASSIGN, IS_RX_PDO, IS_TX_PDO, nAlStatus, OBJ_GetEntryDesc(), OBJ_GetEntryOffset(), OBJCODE_VAR, OBJFLAGS_MAXSUBINDEXMASK, OBJFLAGS_MAXSUBINDEXSHIFT, OBJFLAGS_OBJCODEMASK, OBJFLAGS_OBJCODESHIFT, sSyncManInPar, sSyncManOutPar, STATE_MASK, SWAPWORD, OBJ_STRUCT_PACKED_START::u16CycleExceededCounter, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, OBJ_STRUCT_PACKED_START::u32CalcAndCopyTime, OBJ_STRUCT_PACKED_START::u32CycleTime, OBJ_STRUCT_PACKED_START::u32MinCycleTime, and OBJ_STRUCT_PACKED_START::u8SyncError.
Referenced by SDOS_SdoInd().
Read0x10F8()
UINT8 Read0x10F8 (UINT16 index, UINT8 subindex, UINT32 dataSize, UINT16 MBXMEM * pData, UINT8 bCompleteAccess)
This function reads the object 0x10F8.
Parameters
index index of the requested object.
subindex subindex of the requested object.
dataSize received data size of the SDO Download
pData Pointer to the buffer where the written data can be copied from
bCompleteAccess Indicates if a complete write of all subindices of the object shall be done or not
Returns
result of the write operation (0 (success) or an abort code (ABORTIDX_.... defined in sdosrv.h))
Definition at line 323 of file coeappl.c.
References ABORTIDX_PARAM_IS_INCOMPATIBLE, ABORTIDX_PARAM_LENGTH_TOO_LONG, ABORTIDX_SUBINDEX_NOT_EXISTING, ABORTIDX_UNSUPPORTED_ACCESS, and COE_SyncTimeStamp().
SdoRes()
void SdoRes (UINT8 abort, UINT8 command, UINT8 completeAccess, UINT16 dataSize, UINT32 objLength, TINITSDOMBX MBXMEM * pSdoRes)
This function is called when a SDO response shall be sent.
Parameters
abort Result of the SDO access
command SDO command index
completeAccess Indicates if complete access was requested
dataSize Available data buffer in the response
objLength Complete size of the object
pSdoRes Pointer to the mailbox buffer
Definition at line 542 of file sdoserv.c.
References ABORT_NORM_RES_SIZE, COE_SERVICE, COEHEADER_COESERVICESHIFT, COESERVICE_SDOREQUEST, COESERVICE_SDORESPONSE, DOWNLOAD_NORM_RES_SIZE, EXPEDITED_FRAME_SIZE, MAX_EXPEDITED_DATA, MBX_MailboxSendReq(), SDOHEADER_COMMANDOFFSET, SDOHEADER_SIZEINDICATOR, SDOHEADER_TRANSFERTYPE, SDOHEADERSHIFT_DATASETSIZE, SDOSERVICE_ABORTTRANSFER, SDOSERVICE_DOWNLOADSEGMENTREQ, SDOSERVICE_DOWNLOADSEGMENTRES, SDOSERVICE_INITIATEDOWNLOADRES, SDOSERVICE_INITIATEUPLOADREQ, SDOSERVICE_INITIATEUPLOADRES, SDOSERVICE_UPLOADSEGMENTREQ, SWAPDWORD, SWAPWORD, and UPLOAD_NORM_RES_SIZE.
Referenced by SDOS_SdoInd(), and SDOS_SdoRes().
SDOS_SdoInd()
PROTO UINT8 SDOS_SdoInd (TINITSDOMBX MBXMEM * pSdoInd)
This function is called when a SDO request service is received from the master and calls depending from the command the concerning function.
Parameters
pSdoInd Pointer to the received mailbox data from the master.
Returns
Indicates if an error occurred while the operation (good = 0).
Definition at line 643 of file sdoserv.c.
References ABORTIDX_COMMAND_SPECIFIER_UNKNOWN, ABORTIDX_OBJECT_NOT_EXISTING, ABORTIDX_OUT_OF_MEMORY, ABORTIDX_SUBINDEX_NOT_EXISTING, ABORTIDX_UNSUPPORTED_ACCESS, ABORTIDX_WORKING, bStoreCompleteAccess, DOWNLOAD_NORM_REQ_SIZE, EXPEDITED_FRAME_SIZE, MAX_EXPEDITED_DATA, MBX_HEADER_SIZE, MBXERR_INVALIDSIZE, MBXERR_SERVICEINWORK, OBJ_GetObjectHandle(), OBJ_GetObjectLength(), OBJ_Read(), OBJ_Write(), OBJFLAGS_MAXSUBINDEXMASK, OBJFLAGS_MAXSUBINDEXSHIFT, pSdoPendFunc, pSdoSegData, pStoreData, ROUNDUPBYTE2WORD, MBX_STRUCT_PACKED_START::Sdo, SDO_PENDING_READ, SDO_PENDING_SEG_READ, SDO_PENDING_WRITE, MBX_STRUCT_PACKED_START::SdoHeader, SDOHEADER_COMMAND, SDOHEADER_COMMANDMASK, SDOHEADER_COMMANDOFFSET, SDOHEADER_COMPLETEACCESS, SDOHEADER_DATASETSIZE, SDOHEADER_INDEXHIMASK, SDOHEADER_INDEXHIOFFSET, SDOHEADER_INDEXLOOFFSET, SDOHEADER_INDEXLOSHIFT, SDOHEADER_SUBINDEXMASK, SDOHEADER_SUBINDEXOFFSET, SDOHEADER_SUBINDEXSHIFT, SDOHEADER_TRANSFERTYPE, SDOHEADERSHIFT_DATASETSIZE, SdoRes(), SDOSERVICE_DOWNLOADSEGMENTREQ, SDOSERVICE_INITIATEDOWNLOADREQ, SDOSERVICE_INITIATEUPLOADREQ, SDOSERVICE_UPLOADSEGMENTREQ, SWAPWORD, u16ReceiveMbxSize, u16SendMbxSize, u16StoreIndex, u32StoreDataSize, u8PendingSdo, u8StoreSubindex, and UPLOAD_NORM_RES_SIZE.
Referenced by COE_ServiceInd().
SDOS_SdoInfoInd()
PROTO UINT8 SDOS_SdoInfoInd (TSDOINFORMATION MBXMEM * pSdoInfoInd)
This function is called when a SDO-Info request service is received from the master and calls depending from the opcode the concerning function.
Parameters
pSdoInfoInd Pointer to the received mailbox data from the master.
Returns
Indicates if an error occurred while the operation (good = 0).
Definition at line 1132 of file sdoserv.c.
References ABORTIDX_COMMAND_SPECIFIER_UNKNOWN, ABORTIDX_OBJECT_NOT_EXISTING, ABORTIDX_SUBINDEX_NOT_EXISTING, ABORTIDX_UNSUPPORTED_ACCESS, aSdoInfoHeader, aSubindexDesc, COE_SERVICE, ENTRY_MASK_SUBINDEX, ENTRY_SUBINDEX_SHIFT, FRAGMENTS_FOLLOW, INFO_LIST_TYPE_MAX, INFOHEAD_OPCODE_MASK, INFOHEAD_OPCODE_SHIFT, MBX_HEADER_SIZE, MBX_MailboxSendReq(), MBXERR_SIZETOOSHORT, nSdoInfoFragmentsLeft, OBJ_GetDesc(), OBJ_GetEntryDesc(), OBJ_GetNoOfObjects(), OBJ_GetObjDesc(), OBJ_GetObjectHandle(), OBJ_GetObjectList(), OBJCODE_ARR, OBJCODE_REC, MBX_STRUCT_PACKED_START::ObjFlags, OBJFLAGS_MAXSUBINDEXMASK, OBJFLAGS_MAXSUBINDEXSHIFT, OBJFLAGS_OBJCODEMASK, OBJFLAGS_OBJCODESHIFT, SDO_INFO_HEADER_BYTE_SIZE, SDO_INFO_OBJ_DESC_SIZE, SDOINFOSERVICE_ENTRYDESCRIPTION_Q, SDOINFOSERVICE_ERROR_Q, SDOINFOSERVICE_INCOMPLETE, SDOINFOSERVICE_OBJDESCRIPTION_Q, SDOINFOSERVICE_OBJDICTIONARYLIST_Q, SDOINFOSERVICE_OBJDICTIONARYLIST_S, SIZEOF_SDOINFO, SIZEOF_SDOINFOENTRYREQSTRUCT, SIZEOF_SDOINFOERRORSTRUCT, SIZEOF_SDOINFOLISTSTRUCT, SIZEOF_SDOINFOOBJSTRUCT, SWAPDWORD, SWAPWORD, and u16SendMbxSize.
Referenced by COE_ContinueInd(), and COE_ServiceInd().
SDOS_SdoRes()
PROTO void SDOS_SdoRes (UINT8 abort, UINT32 objLength, UINT16 MBXMEM * pData)
This function is called when a SDO response shall be sent.
Parameters
abort Result of the SDO access
objLength Complete size of the object
pData Pointer to the mailbox buffer
Definition at line 1025 of file sdoserv.c.
References MBX_HEADER_SIZE, pSdoSegData, MBX_STRUCT_PACKED_START::Sdo, MBX_STRUCT_PACKED_START::SdoHeader, SDOHEADER_COMMAND, SDOHEADER_COMMANDOFFSET, SDOHEADER_COMPLETEACCESS, SdoRes(), SDOSERVICE_INITIATEUPLOADREQ, SDOSERVICE_UPLOADSEGMENTREQ, u16SendMbxSize, and UPLOAD_NORM_RES_SIZE.
Referenced by COE_Main().
SODS_ClearPendingResponse()
PROTO void SODS_ClearPendingResponse ()
Clear the variables handling a pending SDO Response This function shall be called before the other mailbox data pointer are set to NULL.
Definition at line 1092 of file sdoserv.c.
References bStoreCompleteAccess, pSdoPendFunc, pSdoSegData, psRepeatMbx, psStoreMbx, pStoreData, u16StoreIndex, u32StoreDataSize, u8PendingSdo, and u8StoreSubindex.
Referenced by MBX_StopMailboxHandler().
Variable Documentation
acDevicename
CHAR acDevicename[] = DEVICE_NAME
0x1008 (Device name) variable to handle the object data
Definition at line 185 of file coeappl.c.
acHardwareversion
CHAR acHardwareversion[] = DEVICE_HW_VERSION
0x1009 (Hardware version) variable to handle the object data
Definition at line 204 of file coeappl.c.
acSoftwareversion
CHAR acSoftwareversion[] = DEVICE_SW_VERSION
0x100A (Software version) variable to handle the object data
Definition at line 223 of file coeappl.c.
aName0x1000
OBJCONST UCHAR OBJMEM aName0x1000[] = "Device type"
0x1000 (Device type) object name
Definition at line 157 of file coeappl.c.
aName0x1001
OBJCONST UCHAR OBJMEM aName0x1001[] = "Error register"
0x1001 (Error Register) object name
Definition at line 176 of file coeappl.c.
aName0x1008
OBJCONST UCHAR OBJMEM aName0x1008[] = "Device name"
0x1008 (Device name) object name
Definition at line 195 of file coeappl.c.
aName0x1009
OBJCONST UCHAR OBJMEM aName0x1009[] = "Hardware version"
0x1009 (Hardware version) object name
Definition at line 214 of file coeappl.c.
aName0x100A
OBJCONST UCHAR OBJMEM aName0x100A[] = "Software version"
0x1009 (Hardware version) object name
Definition at line 233 of file coeappl.c.
aName0x1018
OBJCONST UCHAR OBJMEM aName0x1018[] = "Identity\000Vendor ID\000Product code\000Revision\000Serial number\000\377"
0x1018 (Identity) object and entry names
Definition at line 266 of file coeappl.c.
aName0x10F1
OBJCONST UCHAR OBJMEM aName0x10F1[] = "Error Settings\000Local Error Reaction\000Sync Error Counter Limit\000\377"
0x10F1 (Error settings) object and entry names
Definition at line 287 of file coeappl.c.
aName0x10F8
OBJCONST UCHAR OBJMEM aName0x10F8[] = "Timestamp Object\000\377"
0x10F8 (Timestamp object) object name
Definition at line 305 of file coeappl.c.
aName0x1C00
OBJCONST UCHAR OBJMEM aName0x1C00[] = "Sync manager type"
0x1C00 (Sync manager type) object name
Definition at line 427 of file coeappl.c.
aName0x1C32
OBJCONST UCHAR OBJMEM aName0x1C32[] = "SM output parameter\000Synchronization Type\000Cycle Time\000\000Synchronization Types supported\000Minimum Cycle Time\000Calc and Copy Time\000\000Get Cycle Time\000Delay Time\000Sync0 Cycle Time\000SM-Event Missed\000Cycle Time Too Small\000Shift Time Too Short\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000Sync Error\000\377"
0x1C32 (SyncManager 2 parameter) object and entry names
Definition at line 476 of file coeappl.c.
aName0x1C33
OBJCONST UCHAR OBJMEM aName0x1C33[] = "SM input parameter\000Synchronization Type\000Cycle Time\000\000Synchronization Types supported\000Minimum Cycle Time\000Calc and Copy Time\000\000Get Cycle Time\000Delay Time\000Sync0 Cycle Time\000SM-Event Missed\000Cycle Time Too Small\000Shift Time Too Short\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000Sync Error\000\377"
0x1C33 (SyncManager 3 parameter) object and entry names
Definition at line 481 of file coeappl.c.
aSdoInfoHeader
PROTO MEM_ADDR VARMEM aSdoInfoHeader[GET_MEM_SIZE(SDO_INFO_HEADER_BYTE_SIZE)]
SDO Info buffer.
Definition at line 625 of file sdoserv.h.
Referenced by COE_ContinueInd(), and SDOS_SdoInfoInd().
asEntryDesc0x1018
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x1018[]
Initial value:
= {
   {DEFTYPE_UNSIGNED8, 0x8, ACCESS_READ },
   {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READ},
   {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READ},
   {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READ},
   {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READ}}
0x1018 (Identity) entry descriptions
Subindex 000 SubIndex 001: Vendor ID SubIndex 002: Product code SubIndex 003: Revision SubIndex 004: Serial number
Definition at line 256 of file coeappl.c.
asEntryDesc0x10F1
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x10F1[]
Initial value:
= {
   {DEFTYPE_UNSIGNED8, 0x8, ACCESS_READ },
   {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READWRITE},
   {DEFTYPE_UNSIGNED16, 0x10, ACCESS_READWRITE}}
0x10F1 (Error settings) entry description Subindex 000 SubIndex 001: Local Error Reaction SubIndex 002: Sync Error Counter Limit
Definition at line 279 of file coeappl.c.
asEntryDesc0x1C00
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x1C00[]
Initial value:
= {
   {DEFTYPE_UNSIGNED8, 0x08, ACCESS_READ},
   {DEFTYPE_UNSIGNED8, 0x08, ACCESS_READ}}
0x1C00 (Sync manager type) entry descriptions
The object is an array so only the first entry is described (which is used for all entries).
Definition at line 420 of file coeappl.c.
asEntryDesc0x1C3x
OBJCONST TSDOINFOENTRYDESC OBJMEM asEntryDesc0x1C3x[]
0x1C3x (SyncManager parameter) entry description
The entry descriptions are used for 0x1C32 and 0x1C33
Definition at line 438 of file coeappl.c.
aSubindexDesc
PROTO CHAR OBJMEM aSubindexDesc[13]
Default entry name "SubIndex 000".
Definition at line 265 of file objdef.h.
Referenced by OBJ_GetDesc(), and SDOS_SdoInfoInd().
bSdoInWork
BOOL VARMEM bSdoInWork = FALSE
Definition at line 171 of file sdoserv.c.
bSdoSegAccess
UINT8 VARMEM bSdoSegAccess
Definition at line 175 of file sdoserv.c.
bSdoSegFollows
UINT8 VARMEM bSdoSegFollows
Definition at line 174 of file sdoserv.c.
bSdoSegLastToggle
UINT8 VARMEM bSdoSegLastToggle
Definition at line 179 of file sdoserv.c.
bSyncSetByUser
PROTO BOOL bSyncSetByUser
Indicates if the synchronisation was written by the user on startup (by writing 0x1C3x.1). If it was not written the sync mode will be set based on the DC registers 0x980:0x981
Definition at line 228 of file objdef.h.
Referenced by BackToInitTransition(), COE_ObjInit(), OBJ_Write(), StartInputHandler(), and StopInputHandler().
cAbortCode
const UINT32 MBXMEM cAbortCode[]
Definition at line 133 of file sdoserv.c.
cBitMask
const UINT16 cBitMask[16] = {0x0000,0x0001,0x0003,0x0007,0x000F,0x001F,0x003F,0x007F,0x00FF,0x01FF,0x03FF,0x07FF,0x0FFF,0x1FFF,0x3FFF,0x7FFF}
Definition at line 162 of file objdef.c.
GenObjDic
TOBJECT OBJMEM GenObjDic[]
Initial value:
= {
   {NULL,NULL,  0x1000, {DEFTYPE_UNSIGNED32, 0 | (OBJCODE_VAR << 8)}, &sEntryDesc0x1000, aName0x1000, &u32Devicetype, NULL, NULL, 0x0000 },
   {NULL,NULL,  0x1001, {DEFTYPE_UNSIGNED8, 0 | (OBJCODE_VAR << 8)}, &sEntryDesc0x1001, aName0x1001, &u16ErrorRegister, NULL, NULL, 0x0000 },
   {NULL,NULL,  0x1008, {DEFTYPE_VISIBLESTRING, 0 | (OBJCODE_VAR << 8)}, &sEntryDesc0x1008, aName0x1008, acDevicename, NULL, NULL, 0x0000 },
   {NULL,NULL,  0x1009, {DEFTYPE_VISIBLESTRING, 0 | (OBJCODE_VAR << 8)}, &sEntryDesc0x1009, aName0x1009, acHardwareversion, NULL, NULL, 0x0000 },
   {NULL,NULL,  0x100A, {DEFTYPE_VISIBLESTRING, 0 | (OBJCODE_VAR << 8)}, &sEntryDesc0x100A, aName0x100A, acSoftwareversion, NULL, NULL, 0x0000 },
   {NULL,NULL,  0x1018, {DEFTYPE_IDENTITY, 4 | (OBJCODE_REC << 8)}, asEntryDesc0x1018, aName0x1018, &sIdentity, NULL, NULL, 0x0000 },
   {NULL,NULL,  0x10F1, {DEFTYPE_RECORD, 2 | (OBJCODE_REC << 8)}, asEntryDesc0x10F1, aName0x10F1, &sErrorSettings, NULL, NULL, 0x0000 },
   { NULL,NULL,  0x10F8,{ DEFTYPE_UNSIGNED64, 0 | (OBJCODE_VAR << 8) }, &sEntryDesc0x10F8, aName0x10F8, &u64Timestamp, Read0x10F8, NULL , 0x0000 },
   {NULL,NULL, 0x1C00, {DEFTYPE_UNSIGNED8, 4 | (OBJCODE_ARR << 8)}, asEntryDesc0x1C00, aName0x1C00, &sSyncmanagertype, NULL, NULL, 0x0000 },
   {NULL,NULL, 0x1C32, {DEFTYPE_SMPAR, 32 | (OBJCODE_REC << 8)}, asEntryDesc0x1C3x, aName0x1C32, &sSyncManOutPar, NULL, NULL, 0x0000 },
   {NULL,NULL, 0x1C33, {DEFTYPE_SMPAR, 32 | (OBJCODE_REC << 8)}, asEntryDesc0x1C3x, aName0x1C33, &sSyncManInPar, NULL, NULL, 0x0000 },
  {NULL,NULL, 0xFFFF, {0, 0}, NULL, NULL, NULL, NULL, NULL, 0x000}}
List of generic application independent objects.
Definition at line 494 of file coeappl.c.
Referenced by COE_ObjDictionaryInit().
nSdoInfoIndex
UINT16 VARMEM nSdoInfoIndex
Definition at line 167 of file sdoserv.c.
nSdoSegBytesToHandle
UINT32 VARMEM nSdoSegBytesToHandle
Definition at line 178 of file sdoserv.c.
nSdoSegCompleteSize
UINT32 VARMEM nSdoSegCompleteSize
Definition at line 180 of file sdoserv.c.
nSdoSegIndex
UINT16 VARMEM nSdoSegIndex
Definition at line 176 of file sdoserv.c.
nSdoSegService
UINT8 VARMEM nSdoSegService
Definition at line 173 of file sdoserv.c.
nSdoSegSubindex
UINT8 VARMEM nSdoSegSubindex
Definition at line 177 of file sdoserv.c.
ObjDicList
TOBJECT OBJMEM* ObjDicList = NULL
Object dictionary pointer.
Definition at line 489 of file coeappl.c.
Referenced by COE_AddObjectToDic(), COE_ClearObjDictionary(), COE_GetObjectDictionary(), COE_ObjDictionaryInit(), and COE_RemoveDicEntry().
pCoeSendStored
PROTO TMBX MBXMEM* VARMEM pCoeSendStored
Definition at line 97 of file ecatcoe.h.
pSdoInfoObjEntry [1/2]
OBJCONST TOBJECT OBJMEM* pSdoInfoObjEntry extern
Definition at line 168 of file sdoserv.c.
pSdoInfoObjEntry [2/2]
OBJCONST TOBJECT OBJMEM* VARMEM pSdoInfoObjEntry
Definition at line 168 of file sdoserv.c.
pSdoResStored
TINITSDOMBX MBXMEM* VARMEM pSdoResStored
Definition at line 170 of file sdoserv.c.
pSdoSegObjEntry
OBJCONST TOBJECT OBJMEM* VARMEM pSdoSegObjEntry
Definition at line 181 of file sdoserv.c.
sCycleDiag
PROTO TCYCLEDIAG sCycleDiag
Cycle diagnosis variable.
Definition at line 233 of file objdef.h.
Referenced by StartInputHandler().
sEntryDesc0x1000
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1000 = {DEFTYPE_UNSIGNED32, 0x20, ACCESS_READ}
0x1000 (Device type) entry description
Definition at line 152 of file coeappl.c.
sEntryDesc0x1001
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1001 = {DEFTYPE_UNSIGNED8, 0x08, ACCESS_READ}
0x1001 (Error Register) entry description
Definition at line 171 of file coeappl.c.
sEntryDesc0x1008
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1008 = {DEFTYPE_VISIBLESTRING, BYTE2BIT(DEVICE_NAME_LEN), ACCESS_READ}
0x1008 (Device name) entry description
Definition at line 190 of file coeappl.c.
sEntryDesc0x1009
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x1009 = {DEFTYPE_VISIBLESTRING,BYTE2BIT(DEVICE_HW_VERSION_LEN), ACCESS_READ}
0x1009 (Hardware version) entry description
Definition at line 209 of file coeappl.c.
sEntryDesc0x100A
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x100A = {DEFTYPE_VISIBLESTRING,BYTE2BIT(DEVICE_SW_VERSION_LEN), ACCESS_READ}
0x1009 (Hardware version) entry description
Definition at line 228 of file coeappl.c.
sEntryDesc0x10F8
OBJCONST TSDOINFOENTRYDESC OBJMEM sEntryDesc0x10F8 = { DEFTYPE_UNSIGNED64, 0x40, ACCESS_READWRITE | OBJACCESS_TXPDOMAPPING }
0x10F8 (Timestamp object) entry description
Definition at line 300 of file coeappl.c.
sErrorSettings
PROTO TOBJ10F1 sErrorSettings
Object 0x10F1 (Error Settings) object variable.
SubIndex0 : 2 Local error reaction : 1 Sync error counter limit : MAX_SM_EVENT_MISSED
Definition at line 255 of file objdef.h.
Referenced by COE_UpdateSyncErrorStatus(), and DC_CheckWatchdog().
sIdentity
TOBJ1018 sIdentity = {4, (VENDOR_ID), (PRODUCT_CODE), (REVISION_NUMBER), (SERIAL_NUMBER)}
0x1018 (Identity) variable to handle the object data
Definition at line 245 of file coeappl.c.
sSyncmanagertype
TOBJ1C00 sSyncmanagertype = {0x04, {0x0201, 0x0403}}
0x1C00 (Sync manager type) variable to handle the object data
SI 0 : 4 (4 SyncManagers available) SI1 (SM0): Mailbox Out (0x1) SI2 (SM1): Mailbox In (0x2) SI3 (SM2): Process data Out (0x3) SI4 (SM3): Process data In (0x4)
Definition at line 410 of file coeappl.c.
sSyncManInPar
PROTO TSYNCMANPAR MBXMEM sSyncManInPar
Object 0x1C33 (SyncManager 3 Parameter) object variable.
Definition at line 245 of file objdef.h.
Referenced by CheckSyncTypeValue(), COE_ObjInit(), COE_UpdateSyncErrorStatus(), ECAT_Application(), HandleCycleTimeMeasurement(), OBJ_Write(), PDO_InputMapping(), StartInputHandler(), StartOutputHandler(), and StopInputHandler().
sSyncManOutPar
PROTO TSYNCMANPAR MBXMEM sSyncManOutPar
Object 0x1C32 (SyncManager 2 Parameter) object variable.
Definition at line 239 of file objdef.h.
Referenced by CheckSyncTypeValue(), COE_ObjInit(), COE_UpdateSyncErrorStatus(), DC_CheckWatchdog(), ECAT_Application(), HandleCycleTimeMeasurement(), OBJ_Write(), PDO_InputMapping(), PDO_OutputMapping(), StartInputHandler(), StartOutputHandler(), and StopInputHandler().
u16ErrorRegister
UINT16 u16ErrorRegister = 0x0
0x1001 (Error Register) variable to handle the object data
Definition at line 166 of file coeappl.c.
u32CheckForDcOverrunCnt
PROTO UINT32 u32CheckForDcOverrunCnt
Definition at line 102 of file coeappl.h.
u32Devicetype
UINT32 u32Devicetype = (DEVICE_PROFILE_TYPE)
0x1000 (Device type) variable to handle the object data
Definition at line 147 of file coeappl.c.
u32LastDc32Value
PROTO UINT32 u32LastDc32Value
Definition at line 101 of file coeappl.h.
u64Timestamp
PROTO UINT64 u64Timestamp
Definition at line 94 of file coeappl.h.