AX58400-CM7: EtherCAT State Machine
EtherCAT State Machine
Files
file bootmode.c
Implementation.
file bootmode.h
Function prototypes for the Boot state.
file ecatslv.c
Implementation This file contains the EtherCAT State Machine.
file ecatslv.h
Data Structures
struct _UPGRADE_RUNTIME_HEADER
struct _UPGRADE_FIRMWARE
Macros
#define _BOOTMODE_ 1
#define FIRMWARE_UPDATE_MAX_PAGE_NUMBER 4
#define FIRMWARE_UPDATE_MAX_FILE_SIZE 0x80000
#define SIGNATURE_STR "ASIX"
#define FIRMWARE_UPDATE_ENABLE 1
#define H2NL(x) ((x >> 24 & 0x000000FF) | (x >> 8 & 0x0000FF00) | (x << 24 & 0xFF000000) | (x << 8 & 0x00FF0000))
#define H2NS(x) ((x>>8 & 0x00FF) | (x<<8 & 0xFF00))
#define TIMEOUT_FOR_REBOOT 1000
#define PROTO extern
#define _ECATSLV_ 1
#define OBJGETNEXTSTR(p) ((OBJCONST CHAR OBJMEM *)(&((p)[OBJSTRLEN((OBJCONST CHAR OBJMEM *) (p)) + 1])))
Macro to get next name within the objetc name string.
#define LO_BYTE 0
LowByte within an WORD.
#define HI_BYTE 1
HighByte within an WORD.
#define LOLO_BYTE 0
LowLowByte within an DWORD.
#define LOHI_BYTE 1
LowHighByte within an DWORD.
#define HILO_BYTE 2
HighLowByte within an DWORD.
#define HIHI_BYTE 3
HighHighByte within an DWORD.
#define LO_WORD 0
LowWord within an DWORD.
#define HI_WORD 1
HighWord within an DWORD.
#define SWAPWORD(x) (x)
Macro to swap a WORD.
#define SWAPDWORD(x) (x)
Macro to swap a DWORD.
#define LOBYTE(x) ((x)&0xFF)
LowByte mask.
#define HIBYTE(x) (((x)&0xFF00)>>8)
HighwByte mask.
#define LOLOBYTE(x) ((x)&0xFF)
LowLowByte mask.
#define LOHIBYTE(x) (((x)&0xFF00)>>8)
LowHighByte mask.
#define HILOBYTE(x) (((x)&0xFF0000)>>16)
HighLowByte mask.
#define HIHIBYTE(x) (((x)&0xFF000000)>>24)
HighHighByte mask.
#define LOWORD(x) ((x)&0xFFFF)
LowWord mask.
#define HIWORD(x) (((x)&0xFFFF0000)>>16)
HighByte mask.
#define BIT2BYTE(x) (((x)+7)>>3)
Marco to convert Bit size to Byte size (round up)
#define BYTE2BIT(x) ((x)<<3)
Marco to convert Byte size to Bit size.
#define BIT2WORD(x) (((x)+15)>>4)
Marco to convert Bit size to Word size (round up)
#define BYTE2WORD(x) (((x)+1)>>1)
Marco to convert Bytes size to Word size (round up)
#define ROUNDUPBYTE2WORD(x) ((((x)+1)>>1)<<1)
Round up Byte size to even number of Words.
#define STATE_INIT ((UINT8) 0x01)
State INIT.
#define STATE_PREOP ((UINT8) 0x02)
State PreOP.
#define STATE_BOOT ((UINT8) 0x03)
State BOOT.
#define STATE_SAFEOP ((UINT8) 0x04)
State SafeOP.
#define STATE_OP ((UINT8) 0x08)
State OP.
#define STATE_MASK ((UINT8) 0x0F)
State mask.
#define STATE_CHANGE ((UINT8) 0x10)
State change (Error indication/acknowledge) mask and value.
#define STATE_DEVID ((UINT8) 0x20)
Request/response Explicit device ID.
#define BOOT_2_INIT ((UINT8)((STATE_BOOT) << 4) | (STATE_INIT))
State transition BOOT to INIT.
#define BOOT_2_PREOP ((UINT8)((STATE_BOOT) << 4) | (STATE_PREOP))
State transition BOOT to INIT.
#define BOOT_2_SAFEOP ((UINT8)((STATE_BOOT) << 4) | (STATE_SAFEOP))
State transition BOOT to INIT.
#define BOOT_2_OP ((UINT8)((STATE_BOOT) << 4) | (STATE_OP))
State transition BOOT to INIT.
#define INIT_2_BOOT ((UINT8)((STATE_INIT) << 4) | (STATE_BOOT))
State transition INIT to BOOT.
#define PREOP_2_BOOT ((UINT8)((STATE_PREOP) << 4) | (STATE_BOOT))
State transition PREOP to BOOT.
#define SAFEOP_2_BOOT ((UINT8)((STATE_SAFEOP) << 4) | (STATE_BOOT))
State transition SAFEOP to BOOT.
#define OP_2_BOOT ((UINT8)((STATE_OP) << 4) | (STATE_BOOT))
State transition OP to BOOT.
#define INIT_2_INIT ((UINT8)((STATE_INIT) << 4) | (STATE_INIT))
State transition INIT to INIT.
#define INIT_2_PREOP ((UINT8)((STATE_INIT) << 4) | (STATE_PREOP))
State transition INIT to PREOP.
#define INIT_2_SAFEOP ((UINT8)((STATE_INIT) << 4) | (STATE_SAFEOP))
State transition INIT to SAFEOP.
#define INIT_2_OP ((UINT8)((STATE_INIT) << 4) | (STATE_OP))
State transition INIT to OP.
#define PREOP_2_INIT ((UINT8)((STATE_PREOP) << 4) | (STATE_INIT))
State transition PREOP to INIT.
#define PREOP_2_PREOP ((UINT8)((STATE_PREOP) << 4) | (STATE_PREOP))
State transition PREOP to PREOP.
#define PREOP_2_SAFEOP ((UINT8)((STATE_PREOP) << 4) | (STATE_SAFEOP))
State transition PREOP to SAFEOP.
#define PREOP_2_OP ((UINT8)((STATE_PREOP) << 4) | (STATE_OP))
State transition PREOP to OP.
#define SAFEOP_2_INIT ((UINT8)((STATE_SAFEOP) << 4) | (STATE_INIT))
State transition SAFEOP to INIT.
#define SAFEOP_2_PREOP ((UINT8)((STATE_SAFEOP) << 4) | (STATE_PREOP))
State transition SAFEOP to PREOP.
#define SAFEOP_2_SAFEOP ((UINT8)((STATE_SAFEOP) << 4) | (STATE_SAFEOP))
State transition SAFEOP to SAFEOP.
#define SAFEOP_2_OP ((UINT8)((STATE_SAFEOP) << 4) |(STATE_OP))
State transition SAFEOP to OP.
#define OP_2_INIT ((UINT8)((STATE_OP) << 4) | (STATE_INIT))
State transition OP to INIT.
#define OP_2_PREOP ((UINT8)((STATE_OP) << 4) | (STATE_PREOP))
State transition OP to PREOP.
#define OP_2_SAFEOP ((UINT8)((STATE_OP) << 4) | (STATE_SAFEOP))
State transition OP to SAFEOP.
#define OP_2_OP ((UINT8)((STATE_OP) << 4) | (STATE_OP))
State transition OP to OP.
#define SYNCMANCHODDADDRESS 0x00
Emergency and Diagnosis code for an odd SyncManager address.
#define SYNCMANCHADDRESS 0x01
Emergency and Diagnosis code for an invalid SyncManager address.
#define SYNCMANCHSIZE 0x02
Emergency and Diagnosis code for an invalid SyncManager size.
#define SYNCMANCHSETTINGS 0x03
Emergency and Diagnosis code for an invalid SyncManager settings.
#define ERROR_SYNCMANCH(code, channel) ((code)+((channel)<<2))
Marco to add SyncManager channel.
#define ERROR_SYNCMANCHODDADDRESS(channel) ((SYNCMANCHODDADDRESS)+((channel)<<2))
Marco to add SyncManager channel.
#define ERROR_SYNCMANCHADDRESS(channel) ((SYNCMANCHADDRESS)+((channel)<<2))
Marco to add SyncManager channel.
#define ERROR_SYNCMANCHSIZE(channel) ((SYNCMANCHSIZE)+((channel)<<2))
Marco to add SyncManager channel.
#define ERROR_SYNCMANCHSETTINGS(channel) ((SYNCMANCHSETTINGS)+((channel)<<2))
Marco to add SyncManager channel.
#define ERROR_SYNCTYPES 0x80
Emergency and Diagnosis code for an invalid Sync types.
#define ERROR_DCSYNCCONTROL 0x81
Emergency and Diagnosis code for an invalid DC Sync control.
#define ERROR_DCSYNC0CYCLETIME 0x82
Emergency and Diagnosis code for an invalid Sync0 cycle time.
#define ERROR_DCSYNC1CYCLETIME 0x83
Emergency and Diagnosis code for an invalid Sync1 cycle time.
#define ERROR_DCCYCLEPARAMETER 0x84
Emergency and Diagnosis code for an invalid Cycle parameter.
#define ERROR_DCLATCHCONTROL 0x85
Emergency and Diagnosis code for an invalid Latch control.
#define ERROR_INVALIDSTATE 0xF0
Emergency and Diagnosis code for an invalid State.
#define ERROR_NOMEMORY 0xF1
Emergency and Diagnosis code for no memory.
#define ERROR_OBJECTDICTIONARY 0xF2
Emergency and Diagnosis code for generic object dictionary error.
#define ERROR_NOSYNCMANACCESS 0xF3
Emergency and Diagnosis code for no SyncManager access.
#define ERROR_NOOFRXPDOS 0xF4
Emergency and Diagnosis code for no RxPDOs.
#define ERROR_NOOFTXPDOS 0xF5
Emergency and Diagnosis code for no TxPDOs.
#define ERROR_STATECHANGE 0xF6
Emergency and Diagnosis code state change error.
#define NOERROR_NOSTATECHANGE 0xFE
Indicates no state change.
#define NOERROR_INWORK 0xFF
Indication for no error but operation is pending.
#define EMCY_SM_ERRORCODE 0xA000
Emergency and Diagnosis code for an SyncManager error.
#define EMCY_SM_DEVICESPECIFIC 0xFF00
Emergency and Diagnosis code for a device specific error.
#define ALSTATUSCODE_NOERROR 0x0000
No error.
#define ALSTATUSCODE_UNSPECIFIEDERROR 0x0001
Unspecified error.
#define ALSTATUSCODE_NOMEMORY 0x0002
No Memory.
#define ALSTATUSCODE_INVALID_REVISION 0x0004
Output/Input mapping is not valid for this hardware or software revision (0x1018:03)
#define ALSTATUSCODE_FW_SII_NOT_MATCH 0x0006
Firmware and EEPROM do not match. Slave needs BOOT-INIT transition.
#define ALSTATUSCODE_FW_UPDATE_FAILED 0x0007
Firmware update not successful. Old firmware still running.
#define ALSTATUSCODE_INVALIDALCONTROL 0x0011
Invalid requested state change.
#define ALSTATUSCODE_UNKNOWNALCONTROL 0x0012
Unknown requested state.
#define ALSTATUSCODE_BOOTNOTSUPP 0x0013
Bootstrap not supported.
#define ALSTATUSCODE_NOVALIDFIRMWARE 0x0014
No valid firmware.
#define ALSTATUSCODE_INVALIDMBXCFGINBOOT 0x0015
Invalid mailbox configuration (BOOT state)
#define ALSTATUSCODE_INVALIDMBXCFGINPREOP 0x0016
Invalid mailbox configuration (PreOP state)
#define ALSTATUSCODE_INVALIDSMCFG 0x0017
Invalid sync manager configuration.
#define ALSTATUSCODE_NOVALIDINPUTS 0x0018
No valid inputs available.
#define ALSTATUSCODE_NOVALIDOUTPUTS 0x0019
No valid outputs.
#define ALSTATUSCODE_SYNCERROR 0x001A
Synchronization error.
#define ALSTATUSCODE_SMWATCHDOG 0x001B
Sync manager watchdog.
#define ALSTATUSCODE_SYNCTYPESNOTCOMPATIBLE 0x001C
Invalid Sync Manager Types.
#define ALSTATUSCODE_INVALIDSMOUTCFG 0x001D
Invalid Output Configuration.
#define ALSTATUSCODE_INVALIDSMINCFG 0x001E
Invalid Input Configuration.
#define ALSTATUSCODE_INVALIDWDCFG 0x001F
Invalid Watchdog Configuration.
#define ALSTATUSCODE_WAITFORCOLDSTART 0x0020
Slave needs cold start.
#define ALSTATUSCODE_WAITFORINIT 0x0021
Slave needs INIT.
#define ALSTATUSCODE_WAITFORPREOP 0x0022
Slave needs PREOP.
#define ALSTATUSCODE_WAITFORSAFEOP 0x0023
Slave needs SAFEOP.
#define ALSTATUSCODE_INVALIDINPUTMAPPING 0x0024
Invalid Input Mapping.
#define ALSTATUSCODE_INVALIDOUTPUTMAPPING 0x0025
Invalid Output Mapping.
#define ALSTATUSCODE_INCONSISTENTSETTINGS 0x0026
Inconsistent Settings.
#define ALSTATUSCODE_FREERUNNOTSUPPORTED 0x0027
FreeRun not supported.
#define ALSTATUSCODE_SYNCHRONNOTSUPPORTED 0x0028
SyncMode not supported.
#define ALSTATUSCODE_FREERUNNEEDS3BUFFERMODE 0x0029
FreeRun needs 3Buffer Mode.
#define ALSTATUSCODE_BACKGROUNDWATCHDOG 0x002A
Background Watchdog.
#define ALSTATUSCODE_NOVALIDINPUTSANDOUTPUTS 0x002B
No Valid Inputs and Outputs.
#define ALSTATUSCODE_FATALSYNCERROR 0x002C
Fatal Sync Error.
#define ALSTATUSCODE_NOSYNCERROR 0x002D
No Sync Error.
#define ALSTATUSCODE_CYCLETIMETOOSMALL 0x002E
EtherCAT cycle time smaller Minimum Cycle Time supported by slave.
#define ALSTATUSCODE_DCINVALIDSYNCCFG 0x0030
Invalid DC SYNCH Configuration.
#define ALSTATUSCODE_DCINVALIDLATCHCFG 0x0031
Invalid DC Latch Configuration.
#define ALSTATUSCODE_DCPLLSYNCERROR 0x0032
PLL Error.
#define ALSTATUSCODE_DCSYNCIOERROR 0x0033
DC Sync IO Error.
#define ALSTATUSCODE_DCSYNCMISSEDERROR 0x0034
DC Sync Timeout Error.
#define ALSTATUSCODE_DCINVALIDSYNCCYCLETIME 0x0035
DC Invalid Sync Cycle Time.
#define ALSTATUSCODE_DCSYNC0CYCLETIME 0x0036
DC Sync0 Cycle Time.
#define ALSTATUSCODE_DCSYNC1CYCLETIME 0x0037
DC Sync1 Cycle Time.
#define ALSTATUSCODE_MBX_AOE 0x0041
MBX_AOE.
#define ALSTATUSCODE_MBX_EOE 0x0042
MBX_EOE.
#define ALSTATUSCODE_MBX_COE 0x0043
MBX_COE.
#define ALSTATUSCODE_MBX_FOE 0x0044
MBX_FOE.
#define ALSTATUSCODE_MBX_SOE 0x0045
MBX_SOE.
#define ALSTATUSCODE_MBX_VOE 0x004F
MBX_VOE.
#define ALSTATUSCODE_EE_NOACCESS 0x0050
EEPROM no access.
#define ALSTATUSCODE_EE_ERROR 0x0051
EEPROM Error.
#define ALSTATUSCODE_EXT_HARDWARE_NOT_READY 0x0052
External hardware not ready. This AL Status Code should be used if the EtherCAT-Slave refused the state transition due to an external connection to another device or signal is missing.
#define ALSTATUSCODE_DEVICE_IDENT_VALUE_UPDATED 0x0061
In legacy identification mode (dip switch mapped to register 0x12) this error is returned if the EEPROM ID value does not match to dipswitch value.
#define ALSTATUSCODE_MODULE_ID_LIST_NOT_MATCH 0x0070
Detected Module Ident List (0xF030) and Configured Module Ident List (0xF050) does not match.
#define ALSTATUSCODE_SUPPLY_VOLTAGE_TOO_LOW 0x0080
The slave supply voltage is too low.
#define ALSTATUSCODE_SUPPLY_VOLTAGE_TOO_HIGH 0x0081
The slave supply voltage is too high.
#define ALSTATUSCODE_TEMPERATURE_TOO_LOW 0x0080
The slave temperature is too low.
#define ALSTATUSCODE_TEMPERATURE_TOO_HIGH 0x0081
The slave temperature is too high.
#define SYNCTYPE_FREERUN 0x0000
Sync type FreeRun.
#define SYNCTYPE_SM_SYNCHRON 0x0001
SyncManager synchron (synchron to the corresponding SM, 0x1C32.1 -> SM2 ; 0x1C33.1 -> SM3)
#define SYNCTYPE_SM2_SYNCHRON 0x0022
SyncManager2 synchron (only used for 0x1C33.1)
#define SYNCTYPE_DCSYNC0 0x0002
Sync type Sync0 synchron.
#define SYNCTYPE_DCSYNC1 0x0003
Sync type Sync1 synchron.
#define AL_CONTROL_EVENT ((UINT16) 0x01)
AL Control event.
#define SYNC0_EVENT ((UINT16) 0x04)
Sync0 event.
#define SYNC1_EVENT ((UINT16) 0x08)
Sync1 event.
#define SM_CHANGE_EVENT ((UINT16) 0x10)
SyncManager changed event.
#define EEPROM_CMD_PENDING ((UINT16) 0x20)
EEPROM command pending.
#define MAILBOX_WRITE_EVENT ((UINT16) 0x0100)
MBoxOut write event.
#define MAILBOX_READ_EVENT ((UINT16) 0x0200)
MBoxIn read event.
#define PROCESS_OUTPUT_EVENT ((UINT16) 0x0400)
Output process data write event.
#define PROCESS_INPUT_EVENT ((UINT16) 0x0800)
Input process data read event.
#define MAILBOX_WRITE 0
SyncManager ID for MBoxOut (master to slave)
#define MAILBOX_READ 1
SyncManager ID for MBoxIn (slave to master)
#define PROCESS_DATA_OUT 2
SyncManager ID for output process data (master to slave)
#define PROCESS_DATA_IN 3
SyncManager ID for input process data (slave to master)
#define MEMORY_START_ADDRESS 0x1000
ESC DPRAM start address.
#define DC_SYNC_ACTIVE ESC_DC_SYNC0_ACTIVE_MASK
Expected activated Sync signals by the master.
#define DC_EVENT_MASK PROCESS_OUTPUT_EVENT
AL Event mask (value of register 0x204) in case of DC synchronisation.
#define PROTO extern
#define MAX_SM_EVENT_MISSED 4
threshold of max missed counter value (0x1C32.11 / 0x1C33.11)
Typedefs
typedef struct _UPGRADE_RUNTIME_HEADER UPGRADE_RT_HEAD
typedef struct _UPGRADE_FIRMWARE UPGRADE_FIRMWARE
Enumerations
enum BL_STATE {
BL_STATE_IDLE = 0 , BL_STATE_START , BL_STATE_START_DOWNLOAD , BL_STATE_DATA ,
BL_STATE_FW_TRANSMIT_DONE
}
Functions
void BL_Start (UINT8 State)
Called from INIT to BOOT.
void BL_Init (void)
void BL_Stop (void)
Called in the state transition from BOOT to Init.
void BL_StartDownload (UINT32 password0)
Dummy BL_StartDownload function.
UINT16 BL_Data (UINT16 *pData, UINT16 Size)
Dummy BL_Data function.
void BL_Reboot (void)
void ResetALEventMask (UINT16 intMask)
This function makes an logical and with the AL Event Mask register (0x204)
void SetALEventMask (UINT16 intMask)
This function makes an logical or with the AL Event Mask register (0x204)
void UpdateEEPROMLoadedState (void)
This function reads the EEPROM loaded state.
TSYNCMAN ESCMEM * GetSyncMan (UINT8 channel)
This function is called to read the SYNC Manager channel descriptions of the process data SYNC Managers.
void DisableSyncManChannel (UINT8 channel)
This function disables a Sync Manager channel.
void EnableSyncManChannel (UINT8 channel)
This function enables a Sync Manager channel.
UINT8 CheckSmSettings (UINT8 maxChannel)
This function checks all SM channels.
UINT16 StartInputHandler (void)
This function is called in case of the state transition from PREOP to SAFEOP. |brief the areas of the Sync Managers will be checked for overlapping,.
UINT16 StartOutputHandler (void)
This function is called in case of the state transition from SAFEOP to OP.
void StopOutputHandler (void)
This function is called in case of the state transition from OP to SAFEOP.
void StopInputHandler (void)
This function is called in case of the state transition from SAFEOP to PREOP.
void BackToInitTransition (void)
This function is called when a X to Init transition is completed.
void SetALStatus (UINT8 alStatus, UINT16 alStatusCode)
The function changes the state of the EtherCAT ASIC to the requested.
void AL_ControlInd (UINT8 alControl, UINT16 alStatusCode)
This function handles the EtherCAT State Machine. It is called in case of an AL Control event (Bit 0 of AL-Event (Reg 0x220), when the Master has written the AL Control Register (from ECAT_Main), alControl contains the content of the AL Control (Reg 0x120) in case of a SM-Change event (Bit 4 of AL-Event (Reg 0x220)), when an Activate SYNCM y register is written by the master (from ECAT_Main), alControl contains the actual state (Bit 0-3 of AL Status (Reg 0x130)) in case of a locally expired watchdog (from ECAT_Main), alControl contains the requested new state (SAFE_OP) in case of an application specific event to change the EtherCAT state (from application), alControl contains the requested new state (INIT, PRE_OP or SAFE_OP)
void AL_ControlRes (void)
This function is called cyclic if a state transition is pending (bEcatWaitForAlControlRes == TRUE)
void DC_CheckWatchdog (void)
This function checks the current Sync state and set the local flags The analyse of the local flags is handled in "CheckIfEcatError".
void CheckIfEcatError (void)
Checks communication and synchronisation variables and update AL status / AL status code if an error has occurred.
void ECAT_StateChange (UINT8 alStatus, UINT16 alStatusCode)
This function changes the state of the EtherCAT slave if the requested state is lower than the actual state, otherwise the error condition will be reset.
void ECAT_Init (void)
This function initialize the EtherCAT Slave Interface.
void ECAT_Main (void)
This function has to be called cyclically.
Variables
UPGRADE_FIRMWARE firmwareObj
UPGRADE_RT_HEAD firmwareHeader
UINT16 timerForJumpToBldr
UINT16 foeLeftBytes
unsigned long dwordData [8]
UINT16 u16ALEventMask
VARVOLATILE UINT8 u8dummy
VARVOLATILE UINT8 SMActivate = 0
TSYNCMAN SyncManInfo
BOOL EepromLoaded = FALSE
PROTO BOOL bBootMode
Indicates in slave is in BOOT mode.
PROTO BOOL bEcatOutputUpdateRunning
Indicates the OP state, will be set in StartOutputHandler and reset in StopOutputHandler.
PROTO BOOL bEcatInputUpdateRunning
Indicates the SAFEOP or OP state, will be set in StartInputHandler and reset in Stop InputHandler.
PROTO BOOL bEcatFirstOutputsReceived
Indicates if outputs were received (SM2-event) or inputs were read (SM3-event, if the output size is 0), has to be set by the application and reset in StopOutputHandler.
PROTO BOOL bWdTrigger
Indicates that the SM2 WD trigger bit (0x814 bit6) is set.
PROTO BOOL bDcSyncActive
Indicates that the Distributed Clocks synchronization is active,.
PROTO INT16 EsmTimeoutCounter
Counter used to detect an ESM timeout. -1 indicates a deactivated counter and 0 is expired.
PROTO BOOL bDcRunning
Indicates if Sync0 events are received.
PROTO UINT16 u16SmSync0Counter
PROTO UINT16 u16SmSync0Value
PROTO BOOL bSmSyncSequenceValid
Set to true if SM/Sync0 sequence is valid.
PROTO INT16 i16WaitForPllRunningTimeout
The time bPllRunnig shall be true while state change from SafeOp to Op.
PROTO INT16 i16WaitForPllRunningCnt
Incremented with every valid Sync-SyncManger cycle.
PROTO UINT16 Sync0WdCounter
Sync0 watchdog counter.
PROTO UINT16 Sync0WdValue
Sync0 watchdog value.
PROTO UINT16 Sync1WdCounter
Sync1 watchdog counter.
PROTO UINT16 Sync1WdValue
Sync1 watchdog value.
PROTO UINT16 LatchInputSync0Value
Sync0 event on which the inputs shall be latched and copied to the ESC buffer. If the inputs shall be latched base don Sync1 the value is set to 0.
PROTO UINT16 LatchInputSync0Counter
Sync0 counter used to get the Sync0 event to latch the Inputs.
PROTO BOOL b32BitDc
PROTO BOOL bEscIntEnabled
Indicates that the ESC interrupt is enabled (SM2/3 or SYNC0/1-event), will be set in StartInputHandler and reset in StopInputHandler.
PROTO BOOL b3BufferMode
Indicates that inputs and outputs are running in 3-Buffer-Mode.
PROTO BOOL bLocalErrorFlag
Contains the information if the application has a local error.
PROTO UINT16 u16LocalErrorCode
Reason for local error.
PROTO BOOL bApplEsmPending
Indicates if the local application ESM function need to be called from Al_ConntrolRes (is true if NOERR_INWORK is returned by generic ESM function)
PROTO BOOL bEcatWaitForAlControlRes
Contains the information that the state machine waits for an acknowledge for the last AL_ControlInd from the application/generic stack.
PROTO UINT16 nEcatStateTrans
Current state transition.
PROTO UINT16 nPdInputSize
Contains the input size (SM3 size)/SM2 if no outputs are supported, has to be written by the application.
PROTO UINT16 nPdOutputSize
Contains the output size (SM2 size), has to be written by the application.
PROTO UINT8 nMaxSyncMan
Contains the maximum number of Sync Manager channels, will be initialized in ECAT_Main.
PROTO UINT16 nMaxEscAddress
Max supported address by the ESC (register(0x1000) + size of the supported DPRAM in Byte)
PROTO UINT8 nAlStatus
Contains the actual AL Status, will be written in AL_ControlInd.
PROTO UINT16 EcatWdValue
Contains the value of the watchdog in ms, will be written in StartInputHandler. In case that the ESC watchdog feature is used this variable just indicates if the watchdog is enabled or disabled.
PROTO UINT16 nEscAddrOutputData
Contains the SM address for the output process data.
PROTO UINT16 nEscAddrInputData
Contains the SM address for the input process data.
Detailed Description
Macro Definition Documentation
_BOOTMODE_
#define _BOOTMODE_ 1
Definition at line 31 of file bootmode.c.
_ECATSLV_
#define _ECATSLV_ 1
Definition at line 189 of file ecatslv.c.
AL_CONTROL_EVENT
#define AL_CONTROL_EVENT ((UINT16) 0x01)
AL Control event.
Definition at line 315 of file ecatslv.h.
ALSTATUSCODE_BACKGROUNDWATCHDOG
#define ALSTATUSCODE_BACKGROUNDWATCHDOG 0x002A
Background Watchdog.
Definition at line 271 of file ecatslv.h.
ALSTATUSCODE_BOOTNOTSUPP
#define ALSTATUSCODE_BOOTNOTSUPP 0x0013
Bootstrap not supported.
Definition at line 248 of file ecatslv.h.
ALSTATUSCODE_CYCLETIMETOOSMALL
#define ALSTATUSCODE_CYCLETIMETOOSMALL 0x002E
EtherCAT cycle time smaller Minimum Cycle Time supported by slave.
Definition at line 275 of file ecatslv.h.
ALSTATUSCODE_DCINVALIDLATCHCFG
#define ALSTATUSCODE_DCINVALIDLATCHCFG 0x0031
Invalid DC Latch Configuration.
Definition at line 277 of file ecatslv.h.
ALSTATUSCODE_DCINVALIDSYNCCFG
#define ALSTATUSCODE_DCINVALIDSYNCCFG 0x0030
Invalid DC SYNCH Configuration.
Definition at line 276 of file ecatslv.h.
ALSTATUSCODE_DCINVALIDSYNCCYCLETIME
#define ALSTATUSCODE_DCINVALIDSYNCCYCLETIME 0x0035
DC Invalid Sync Cycle Time.
Definition at line 281 of file ecatslv.h.
ALSTATUSCODE_DCPLLSYNCERROR
#define ALSTATUSCODE_DCPLLSYNCERROR 0x0032
PLL Error.
Definition at line 278 of file ecatslv.h.
ALSTATUSCODE_DCSYNC0CYCLETIME
#define ALSTATUSCODE_DCSYNC0CYCLETIME 0x0036
DC Sync0 Cycle Time.
Definition at line 282 of file ecatslv.h.
ALSTATUSCODE_DCSYNC1CYCLETIME
#define ALSTATUSCODE_DCSYNC1CYCLETIME 0x0037
DC Sync1 Cycle Time.
Definition at line 283 of file ecatslv.h.
ALSTATUSCODE_DCSYNCIOERROR
#define ALSTATUSCODE_DCSYNCIOERROR 0x0033
DC Sync IO Error.
Definition at line 279 of file ecatslv.h.
ALSTATUSCODE_DCSYNCMISSEDERROR
#define ALSTATUSCODE_DCSYNCMISSEDERROR 0x0034
DC Sync Timeout Error.
Definition at line 280 of file ecatslv.h.
ALSTATUSCODE_DEVICE_IDENT_VALUE_UPDATED
#define ALSTATUSCODE_DEVICE_IDENT_VALUE_UPDATED 0x0061
In legacy identification mode (dip switch mapped to register 0x12) this error is returned if the EEPROM ID value does not match to dipswitch value.
Definition at line 293 of file ecatslv.h.
ALSTATUSCODE_EE_ERROR
#define ALSTATUSCODE_EE_ERROR 0x0051
EEPROM Error.
Definition at line 291 of file ecatslv.h.
ALSTATUSCODE_EE_NOACCESS
#define ALSTATUSCODE_EE_NOACCESS 0x0050
EEPROM no access.
Definition at line 290 of file ecatslv.h.
ALSTATUSCODE_EXT_HARDWARE_NOT_READY
#define ALSTATUSCODE_EXT_HARDWARE_NOT_READY 0x0052
External hardware not ready. This AL Status Code should be used if the EtherCAT-Slave refused the state transition due to an external connection to another device or signal is missing.
Definition at line 292 of file ecatslv.h.
ALSTATUSCODE_FATALSYNCERROR
#define ALSTATUSCODE_FATALSYNCERROR 0x002C
Fatal Sync Error.
Definition at line 273 of file ecatslv.h.
ALSTATUSCODE_FREERUNNEEDS3BUFFERMODE
#define ALSTATUSCODE_FREERUNNEEDS3BUFFERMODE 0x0029
FreeRun needs 3Buffer Mode.
Definition at line 270 of file ecatslv.h.
ALSTATUSCODE_FREERUNNOTSUPPORTED
#define ALSTATUSCODE_FREERUNNOTSUPPORTED 0x0027
FreeRun not supported.
Definition at line 268 of file ecatslv.h.
ALSTATUSCODE_FW_SII_NOT_MATCH
#define ALSTATUSCODE_FW_SII_NOT_MATCH 0x0006
Firmware and EEPROM do not match. Slave needs BOOT-INIT transition.
Definition at line 244 of file ecatslv.h.
ALSTATUSCODE_FW_UPDATE_FAILED
#define ALSTATUSCODE_FW_UPDATE_FAILED 0x0007
Firmware update not successful. Old firmware still running.
Definition at line 245 of file ecatslv.h.
ALSTATUSCODE_INCONSISTENTSETTINGS
#define ALSTATUSCODE_INCONSISTENTSETTINGS 0x0026
Inconsistent Settings.
Definition at line 267 of file ecatslv.h.
ALSTATUSCODE_INVALID_REVISION
#define ALSTATUSCODE_INVALID_REVISION 0x0004
Output/Input mapping is not valid for this hardware or software revision (0x1018:03)
Definition at line 243 of file ecatslv.h.
ALSTATUSCODE_INVALIDALCONTROL
#define ALSTATUSCODE_INVALIDALCONTROL 0x0011
Invalid requested state change.
Definition at line 246 of file ecatslv.h.
ALSTATUSCODE_INVALIDINPUTMAPPING
#define ALSTATUSCODE_INVALIDINPUTMAPPING 0x0024
Invalid Input Mapping.
Definition at line 265 of file ecatslv.h.
ALSTATUSCODE_INVALIDMBXCFGINBOOT
#define ALSTATUSCODE_INVALIDMBXCFGINBOOT 0x0015
Invalid mailbox configuration (BOOT state)
Definition at line 250 of file ecatslv.h.
ALSTATUSCODE_INVALIDMBXCFGINPREOP
#define ALSTATUSCODE_INVALIDMBXCFGINPREOP 0x0016
Invalid mailbox configuration (PreOP state)
Definition at line 251 of file ecatslv.h.
ALSTATUSCODE_INVALIDOUTPUTMAPPING
#define ALSTATUSCODE_INVALIDOUTPUTMAPPING 0x0025
Invalid Output Mapping.
Definition at line 266 of file ecatslv.h.
ALSTATUSCODE_INVALIDSMCFG
#define ALSTATUSCODE_INVALIDSMCFG 0x0017
Invalid sync manager configuration.
Definition at line 252 of file ecatslv.h.
ALSTATUSCODE_INVALIDSMINCFG
#define ALSTATUSCODE_INVALIDSMINCFG 0x001E
Invalid Input Configuration.
Definition at line 259 of file ecatslv.h.
ALSTATUSCODE_INVALIDSMOUTCFG
#define ALSTATUSCODE_INVALIDSMOUTCFG 0x001D
Invalid Output Configuration.
Definition at line 258 of file ecatslv.h.
ALSTATUSCODE_INVALIDWDCFG
#define ALSTATUSCODE_INVALIDWDCFG 0x001F
Invalid Watchdog Configuration.
Definition at line 260 of file ecatslv.h.
ALSTATUSCODE_MBX_AOE
#define ALSTATUSCODE_MBX_AOE 0x0041
MBX_AOE.
Definition at line 284 of file ecatslv.h.
ALSTATUSCODE_MBX_COE
#define ALSTATUSCODE_MBX_COE 0x0043
MBX_COE.
Definition at line 286 of file ecatslv.h.
ALSTATUSCODE_MBX_EOE
#define ALSTATUSCODE_MBX_EOE 0x0042
MBX_EOE.
Definition at line 285 of file ecatslv.h.
ALSTATUSCODE_MBX_FOE
#define ALSTATUSCODE_MBX_FOE 0x0044
MBX_FOE.
Definition at line 287 of file ecatslv.h.
ALSTATUSCODE_MBX_SOE
#define ALSTATUSCODE_MBX_SOE 0x0045
MBX_SOE.
Definition at line 288 of file ecatslv.h.
ALSTATUSCODE_MBX_VOE
#define ALSTATUSCODE_MBX_VOE 0x004F
MBX_VOE.
Definition at line 289 of file ecatslv.h.
ALSTATUSCODE_MODULE_ID_LIST_NOT_MATCH
#define ALSTATUSCODE_MODULE_ID_LIST_NOT_MATCH 0x0070
Detected Module Ident List (0xF030) and Configured Module Ident List (0xF050) does not match.
Definition at line 294 of file ecatslv.h.
ALSTATUSCODE_NOERROR
#define ALSTATUSCODE_NOERROR 0x0000
No error.
Definition at line 240 of file ecatslv.h.
ALSTATUSCODE_NOMEMORY
#define ALSTATUSCODE_NOMEMORY 0x0002
No Memory.
Definition at line 242 of file ecatslv.h.
ALSTATUSCODE_NOSYNCERROR
#define ALSTATUSCODE_NOSYNCERROR 0x002D
No Sync Error.
Definition at line 274 of file ecatslv.h.
ALSTATUSCODE_NOVALIDFIRMWARE
#define ALSTATUSCODE_NOVALIDFIRMWARE 0x0014
No valid firmware.
Definition at line 249 of file ecatslv.h.
ALSTATUSCODE_NOVALIDINPUTS
#define ALSTATUSCODE_NOVALIDINPUTS 0x0018
No valid inputs available.
Definition at line 253 of file ecatslv.h.
ALSTATUSCODE_NOVALIDINPUTSANDOUTPUTS
#define ALSTATUSCODE_NOVALIDINPUTSANDOUTPUTS 0x002B
No Valid Inputs and Outputs.
Definition at line 272 of file ecatslv.h.
ALSTATUSCODE_NOVALIDOUTPUTS
#define ALSTATUSCODE_NOVALIDOUTPUTS 0x0019
No valid outputs.
Definition at line 254 of file ecatslv.h.
ALSTATUSCODE_SMWATCHDOG
#define ALSTATUSCODE_SMWATCHDOG 0x001B
Sync manager watchdog.
Definition at line 256 of file ecatslv.h.
ALSTATUSCODE_SUPPLY_VOLTAGE_TOO_HIGH
#define ALSTATUSCODE_SUPPLY_VOLTAGE_TOO_HIGH 0x0081
The slave supply voltage is too high.
Definition at line 296 of file ecatslv.h.
ALSTATUSCODE_SUPPLY_VOLTAGE_TOO_LOW
#define ALSTATUSCODE_SUPPLY_VOLTAGE_TOO_LOW 0x0080
The slave supply voltage is too low.
Definition at line 295 of file ecatslv.h.
ALSTATUSCODE_SYNCERROR
#define ALSTATUSCODE_SYNCERROR 0x001A
Synchronization error.
Definition at line 255 of file ecatslv.h.
ALSTATUSCODE_SYNCHRONNOTSUPPORTED
#define ALSTATUSCODE_SYNCHRONNOTSUPPORTED 0x0028
SyncMode not supported.
Definition at line 269 of file ecatslv.h.
ALSTATUSCODE_SYNCTYPESNOTCOMPATIBLE
#define ALSTATUSCODE_SYNCTYPESNOTCOMPATIBLE 0x001C
Invalid Sync Manager Types.
Definition at line 257 of file ecatslv.h.
ALSTATUSCODE_TEMPERATURE_TOO_HIGH
#define ALSTATUSCODE_TEMPERATURE_TOO_HIGH 0x0081
The slave temperature is too high.
Definition at line 298 of file ecatslv.h.
ALSTATUSCODE_TEMPERATURE_TOO_LOW
#define ALSTATUSCODE_TEMPERATURE_TOO_LOW 0x0080
The slave temperature is too low.
Definition at line 297 of file ecatslv.h.
ALSTATUSCODE_UNKNOWNALCONTROL
#define ALSTATUSCODE_UNKNOWNALCONTROL 0x0012
Unknown requested state.
Definition at line 247 of file ecatslv.h.
ALSTATUSCODE_UNSPECIFIEDERROR
#define ALSTATUSCODE_UNSPECIFIEDERROR 0x0001
Unspecified error.
Definition at line 241 of file ecatslv.h.
ALSTATUSCODE_WAITFORCOLDSTART
#define ALSTATUSCODE_WAITFORCOLDSTART 0x0020
Slave needs cold start.
Definition at line 261 of file ecatslv.h.
ALSTATUSCODE_WAITFORINIT
#define ALSTATUSCODE_WAITFORINIT 0x0021
Slave needs INIT.
Definition at line 262 of file ecatslv.h.
ALSTATUSCODE_WAITFORPREOP
#define ALSTATUSCODE_WAITFORPREOP 0x0022
Slave needs PREOP.
Definition at line 263 of file ecatslv.h.
ALSTATUSCODE_WAITFORSAFEOP
#define ALSTATUSCODE_WAITFORSAFEOP 0x0023
Slave needs SAFEOP.
Definition at line 264 of file ecatslv.h.
BIT2BYTE
#define BIT2BYTE (x) (((x)+7)>>3)
Marco to convert Bit size to Byte size (round up)
Definition at line 136 of file ecatslv.h.
BIT2WORD
#define BIT2WORD (x) (((x)+15)>>4)
Marco to convert Bit size to Word size (round up)
Definition at line 144 of file ecatslv.h.
BOOT_2_INIT
#define BOOT_2_INIT ((UINT8)((STATE_BOOT) << 4) | (STATE_INIT))
State transition BOOT to INIT.
Definition at line 169 of file ecatslv.h.
BOOT_2_OP
#define BOOT_2_OP ((UINT8)((STATE_BOOT) << 4) | (STATE_OP))
State transition BOOT to INIT.
Definition at line 172 of file ecatslv.h.
BOOT_2_PREOP
#define BOOT_2_PREOP ((UINT8)((STATE_BOOT) << 4) | (STATE_PREOP))
State transition BOOT to INIT.
Definition at line 170 of file ecatslv.h.
BOOT_2_SAFEOP
#define BOOT_2_SAFEOP ((UINT8)((STATE_BOOT) << 4) | (STATE_SAFEOP))
State transition BOOT to INIT.
Definition at line 171 of file ecatslv.h.
BYTE2BIT
#define BYTE2BIT (x) ((x)<<3)
Marco to convert Byte size to Bit size.
Definition at line 140 of file ecatslv.h.
BYTE2WORD
#define BYTE2WORD (x) (((x)+1)>>1)
Marco to convert Bytes size to Word size (round up)
Definition at line 148 of file ecatslv.h.
DC_EVENT_MASK
#define DC_EVENT_MASK PROCESS_OUTPUT_EVENT
AL Event mask (value of register 0x204) in case of DC synchronisation.
Definition at line 342 of file ecatslv.h.
DC_SYNC_ACTIVE
#define DC_SYNC_ACTIVE ESC_DC_SYNC0_ACTIVE_MASK
Expected activated Sync signals by the master.
Definition at line 339 of file ecatslv.h.
EEPROM_CMD_PENDING
#define EEPROM_CMD_PENDING ((UINT16) 0x20)
EEPROM command pending.
Definition at line 319 of file ecatslv.h.
EMCY_SM_DEVICESPECIFIC
#define EMCY_SM_DEVICESPECIFIC 0xFF00
Emergency and Diagnosis code for a device specific error.
Definition at line 234 of file ecatslv.h.
EMCY_SM_ERRORCODE
#define EMCY_SM_ERRORCODE 0xA000
Emergency and Diagnosis code for an SyncManager error.
Definition at line 233 of file ecatslv.h.
ERROR_DCCYCLEPARAMETER
#define ERROR_DCCYCLEPARAMETER 0x84
Emergency and Diagnosis code for an invalid Cycle parameter.
Definition at line 219 of file ecatslv.h.
ERROR_DCLATCHCONTROL
#define ERROR_DCLATCHCONTROL 0x85
Emergency and Diagnosis code for an invalid Latch control.
Definition at line 220 of file ecatslv.h.
ERROR_DCSYNC0CYCLETIME
#define ERROR_DCSYNC0CYCLETIME 0x82
Emergency and Diagnosis code for an invalid Sync0 cycle time.
Definition at line 217 of file ecatslv.h.
ERROR_DCSYNC1CYCLETIME
#define ERROR_DCSYNC1CYCLETIME 0x83
Emergency and Diagnosis code for an invalid Sync1 cycle time.
Definition at line 218 of file ecatslv.h.
ERROR_DCSYNCCONTROL
#define ERROR_DCSYNCCONTROL 0x81
Emergency and Diagnosis code for an invalid DC Sync control.
Definition at line 216 of file ecatslv.h.
ERROR_INVALIDSTATE
#define ERROR_INVALIDSTATE 0xF0
Emergency and Diagnosis code for an invalid State.
Definition at line 222 of file ecatslv.h.
ERROR_NOMEMORY
#define ERROR_NOMEMORY 0xF1
Emergency and Diagnosis code for no memory.
Definition at line 223 of file ecatslv.h.
ERROR_NOOFRXPDOS
#define ERROR_NOOFRXPDOS 0xF4
Emergency and Diagnosis code for no RxPDOs.
Definition at line 226 of file ecatslv.h.
ERROR_NOOFTXPDOS
#define ERROR_NOOFTXPDOS 0xF5
Emergency and Diagnosis code for no TxPDOs.
Definition at line 227 of file ecatslv.h.
ERROR_NOSYNCMANACCESS
#define ERROR_NOSYNCMANACCESS 0xF3
Emergency and Diagnosis code for no SyncManager access.
Definition at line 225 of file ecatslv.h.
ERROR_OBJECTDICTIONARY
#define ERROR_OBJECTDICTIONARY 0xF2
Emergency and Diagnosis code for generic object dictionary error.
Definition at line 224 of file ecatslv.h.
ERROR_STATECHANGE
#define ERROR_STATECHANGE 0xF6
Emergency and Diagnosis code state change error.
Definition at line 228 of file ecatslv.h.
ERROR_SYNCMANCH
#define ERROR_SYNCMANCH (code, channel) ((code)+((channel)<<2))
Marco to add SyncManager channel.
Definition at line 210 of file ecatslv.h.
ERROR_SYNCMANCHADDRESS
#define ERROR_SYNCMANCHADDRESS (channel) ((SYNCMANCHADDRESS)+((channel)<<2))
Marco to add SyncManager channel.
Definition at line 212 of file ecatslv.h.
ERROR_SYNCMANCHODDADDRESS
#define ERROR_SYNCMANCHODDADDRESS (channel) ((SYNCMANCHODDADDRESS)+((channel)<<2))
Marco to add SyncManager channel.
Definition at line 211 of file ecatslv.h.
ERROR_SYNCMANCHSETTINGS
#define ERROR_SYNCMANCHSETTINGS (channel) ((SYNCMANCHSETTINGS)+((channel)<<2))
Marco to add SyncManager channel.
Definition at line 214 of file ecatslv.h.
ERROR_SYNCMANCHSIZE
#define ERROR_SYNCMANCHSIZE (channel) ((SYNCMANCHSIZE)+((channel)<<2))
Marco to add SyncManager channel.
Definition at line 213 of file ecatslv.h.
ERROR_SYNCTYPES
#define ERROR_SYNCTYPES 0x80
Emergency and Diagnosis code for an invalid Sync types.
Definition at line 215 of file ecatslv.h.
FIRMWARE_UPDATE_ENABLE
#define FIRMWARE_UPDATE_ENABLE 1
Definition at line 43 of file bootmode.c.
FIRMWARE_UPDATE_MAX_FILE_SIZE
#define FIRMWARE_UPDATE_MAX_FILE_SIZE 0x80000
Definition at line 41 of file bootmode.c.
FIRMWARE_UPDATE_MAX_PAGE_NUMBER
#define FIRMWARE_UPDATE_MAX_PAGE_NUMBER 4
Definition at line 40 of file bootmode.c.
H2NL
#define H2NL (x) ((x >> 24 & 0x000000FF) | (x >> 8 & 0x0000FF00) | (x << 24 & 0xFF000000) | (x << 8 & 0x00FF0000))
Definition at line 44 of file bootmode.c.
H2NS
#define H2NS (x) ((x>>8 & 0x00FF) | (x<<8 & 0xFF00))
Definition at line 45 of file bootmode.c.
HI_BYTE
#define HI_BYTE 1
HighByte within an WORD.
Definition at line 68 of file ecatslv.h.
HI_WORD
#define HI_WORD 1
HighWord within an DWORD.
Definition at line 92 of file ecatslv.h.
HIBYTE
#define HIBYTE (x) (((x)&0xFF00)>>8)
HighwByte mask.
Definition at line 108 of file ecatslv.h.
HIHI_BYTE
#define HIHI_BYTE 3
HighHighByte within an DWORD.
Definition at line 84 of file ecatslv.h.
HIHIBYTE
#define HIHIBYTE (x) (((x)&0xFF000000)>>24)
HighHighByte mask.
Definition at line 124 of file ecatslv.h.
HILO_BYTE
#define HILO_BYTE 2
HighLowByte within an DWORD.
Definition at line 80 of file ecatslv.h.
HILOBYTE
#define HILOBYTE (x) (((x)&0xFF0000)>>16)
HighLowByte mask.
Definition at line 120 of file ecatslv.h.
HIWORD
#define HIWORD (x) (((x)&0xFFFF0000)>>16)
HighByte mask.
Definition at line 132 of file ecatslv.h.
INIT_2_BOOT
#define INIT_2_BOOT ((UINT8)((STATE_INIT) << 4) | (STATE_BOOT))
State transition INIT to BOOT.
Definition at line 174 of file ecatslv.h.
INIT_2_INIT
#define INIT_2_INIT ((UINT8)((STATE_INIT) << 4) | (STATE_INIT))
State transition INIT to INIT.
Definition at line 179 of file ecatslv.h.
INIT_2_OP
#define INIT_2_OP ((UINT8)((STATE_INIT) << 4) | (STATE_OP))
State transition INIT to OP.
Definition at line 182 of file ecatslv.h.
INIT_2_PREOP
#define INIT_2_PREOP ((UINT8)((STATE_INIT) << 4) | (STATE_PREOP))
State transition INIT to PREOP.
Definition at line 180 of file ecatslv.h.
INIT_2_SAFEOP
#define INIT_2_SAFEOP ((UINT8)((STATE_INIT) << 4) | (STATE_SAFEOP))
State transition INIT to SAFEOP.
Definition at line 181 of file ecatslv.h.
LO_BYTE
#define LO_BYTE 0
LowByte within an WORD.
Definition at line 64 of file ecatslv.h.
LO_WORD
#define LO_WORD 0
LowWord within an DWORD.
Definition at line 88 of file ecatslv.h.
LOBYTE
#define LOBYTE (x) ((x)&0xFF)
LowByte mask.
Definition at line 104 of file ecatslv.h.
LOHI_BYTE
#define LOHI_BYTE 1
LowHighByte within an DWORD.
Definition at line 76 of file ecatslv.h.
LOHIBYTE
#define LOHIBYTE (x) (((x)&0xFF00)>>8)
LowHighByte mask.
Definition at line 116 of file ecatslv.h.
LOLO_BYTE
#define LOLO_BYTE 0
LowLowByte within an DWORD.
Definition at line 72 of file ecatslv.h.
LOLOBYTE
#define LOLOBYTE (x) ((x)&0xFF)
LowLowByte mask.
Definition at line 112 of file ecatslv.h.
LOWORD
#define LOWORD (x) ((x)&0xFFFF)
LowWord mask.
Definition at line 128 of file ecatslv.h.
MAILBOX_READ
#define MAILBOX_READ 1
SyncManager ID for MBoxIn (slave to master)
Definition at line 326 of file ecatslv.h.
MAILBOX_READ_EVENT
#define MAILBOX_READ_EVENT ((UINT16) 0x0200)
MBoxIn read event.
Definition at line 321 of file ecatslv.h.
MAILBOX_WRITE
#define MAILBOX_WRITE 0
SyncManager ID for MBoxOut (master to slave)
Definition at line 325 of file ecatslv.h.
MAILBOX_WRITE_EVENT
#define MAILBOX_WRITE_EVENT ((UINT16) 0x0100)
MBoxOut write event.
Definition at line 320 of file ecatslv.h.
MAX_SM_EVENT_MISSED
#define MAX_SM_EVENT_MISSED 4
threshold of max missed counter value (0x1C32.11 / 0x1C33.11)
Definition at line 376 of file ecatslv.h.
MEMORY_START_ADDRESS
#define MEMORY_START_ADDRESS 0x1000
ESC DPRAM start address.
Definition at line 335 of file ecatslv.h.
NOERROR_INWORK
#define NOERROR_INWORK 0xFF
Indication for no error but operation is pending.
Definition at line 231 of file ecatslv.h.
NOERROR_NOSTATECHANGE
#define NOERROR_NOSTATECHANGE 0xFE
Indicates no state change.
Definition at line 230 of file ecatslv.h.
OBJGETNEXTSTR
#define OBJGETNEXTSTR (p) ((OBJCONST CHAR OBJMEM *)(&((p)[OBJSTRLEN((OBJCONST CHAR OBJMEM *) (p)) + 1])))
Macro to get next name within the objetc name string.
Definition at line 60 of file ecatslv.h.
OP_2_BOOT
#define OP_2_BOOT ((UINT8)((STATE_OP) << 4) | (STATE_BOOT))
State transition OP to BOOT.
Definition at line 177 of file ecatslv.h.
OP_2_INIT
#define OP_2_INIT ((UINT8)((STATE_OP) << 4) | (STATE_INIT))
State transition OP to INIT.
Definition at line 194 of file ecatslv.h.
OP_2_OP
#define OP_2_OP ((UINT8)((STATE_OP) << 4) | (STATE_OP))
State transition OP to OP.
Definition at line 197 of file ecatslv.h.
OP_2_PREOP
#define OP_2_PREOP ((UINT8)((STATE_OP) << 4) | (STATE_PREOP))
State transition OP to PREOP.
Definition at line 195 of file ecatslv.h.
OP_2_SAFEOP
#define OP_2_SAFEOP ((UINT8)((STATE_OP) << 4) | (STATE_SAFEOP))
State transition OP to SAFEOP.
Definition at line 196 of file ecatslv.h.
PREOP_2_BOOT
#define PREOP_2_BOOT ((UINT8)((STATE_PREOP) << 4) | (STATE_BOOT))
State transition PREOP to BOOT.
Definition at line 175 of file ecatslv.h.
PREOP_2_INIT
#define PREOP_2_INIT ((UINT8)((STATE_PREOP) << 4) | (STATE_INIT))
State transition PREOP to INIT.
Definition at line 184 of file ecatslv.h.
PREOP_2_OP
#define PREOP_2_OP ((UINT8)((STATE_PREOP) << 4) | (STATE_OP))
State transition PREOP to OP.
Definition at line 187 of file ecatslv.h.
PREOP_2_PREOP
#define PREOP_2_PREOP ((UINT8)((STATE_PREOP) << 4) | (STATE_PREOP))
State transition PREOP to PREOP.
Definition at line 185 of file ecatslv.h.
PREOP_2_SAFEOP
#define PREOP_2_SAFEOP ((UINT8)((STATE_PREOP) << 4) | (STATE_SAFEOP))
State transition PREOP to SAFEOP.
Definition at line 186 of file ecatslv.h.
PROCESS_DATA_IN
#define PROCESS_DATA_IN 3
SyncManager ID for input process data (slave to master)
Definition at line 328 of file ecatslv.h.
PROCESS_DATA_OUT
#define PROCESS_DATA_OUT 2
SyncManager ID for output process data (master to slave)
Definition at line 327 of file ecatslv.h.
PROCESS_INPUT_EVENT
#define PROCESS_INPUT_EVENT ((UINT16) 0x0800)
Input process data read event.
Definition at line 323 of file ecatslv.h.
PROCESS_OUTPUT_EVENT
#define PROCESS_OUTPUT_EVENT ((UINT16) 0x0400)
Output process data write event.
Definition at line 322 of file ecatslv.h.
PROTO [1/2]
#define PROTO extern
Definition at line 46 of file bootmode.h.
PROTO [2/2]
#define PROTO extern
Definition at line 351 of file ecatslv.h.
ROUNDUPBYTE2WORD
#define ROUNDUPBYTE2WORD (x) ((((x)+1)>>1)<<1)
Round up Byte size to even number of Words.
Definition at line 152 of file ecatslv.h.
SAFEOP_2_BOOT
#define SAFEOP_2_BOOT ((UINT8)((STATE_SAFEOP) << 4) | (STATE_BOOT))
State transition SAFEOP to BOOT.
Definition at line 176 of file ecatslv.h.
SAFEOP_2_INIT
#define SAFEOP_2_INIT ((UINT8)((STATE_SAFEOP) << 4) | (STATE_INIT))
State transition SAFEOP to INIT.
Definition at line 189 of file ecatslv.h.
SAFEOP_2_OP
#define SAFEOP_2_OP ((UINT8)((STATE_SAFEOP) << 4) |(STATE_OP))
State transition SAFEOP to OP.
Definition at line 192 of file ecatslv.h.
SAFEOP_2_PREOP
#define SAFEOP_2_PREOP ((UINT8)((STATE_SAFEOP) << 4) | (STATE_PREOP))
State transition SAFEOP to PREOP.
Definition at line 190 of file ecatslv.h.
SAFEOP_2_SAFEOP
#define SAFEOP_2_SAFEOP ((UINT8)((STATE_SAFEOP) << 4) | (STATE_SAFEOP))
State transition SAFEOP to SAFEOP.
Definition at line 191 of file ecatslv.h.
SIGNATURE_STR
#define SIGNATURE_STR "ASIX"
Definition at line 42 of file bootmode.c.
SM_CHANGE_EVENT
#define SM_CHANGE_EVENT ((UINT16) 0x10)
SyncManager changed event.
Definition at line 318 of file ecatslv.h.
STATE_BOOT
#define STATE_BOOT ((UINT8) 0x03)
State BOOT.
Definition at line 161 of file ecatslv.h.
STATE_CHANGE
#define STATE_CHANGE ((UINT8) 0x10)
State change (Error indication/acknowledge) mask and value.
Definition at line 166 of file ecatslv.h.
STATE_DEVID
#define STATE_DEVID ((UINT8) 0x20)
Request/response Explicit device ID.
Definition at line 167 of file ecatslv.h.
STATE_INIT
#define STATE_INIT ((UINT8) 0x01)
State INIT.
Definition at line 159 of file ecatslv.h.
STATE_MASK
#define STATE_MASK ((UINT8) 0x0F)
State mask.
Definition at line 165 of file ecatslv.h.
STATE_OP
#define STATE_OP ((UINT8) 0x08)
State OP.
Definition at line 163 of file ecatslv.h.
STATE_PREOP
#define STATE_PREOP ((UINT8) 0x02)
State PreOP.
Definition at line 160 of file ecatslv.h.
STATE_SAFEOP
#define STATE_SAFEOP ((UINT8) 0x04)
State SafeOP.
Definition at line 162 of file ecatslv.h.
SWAPDWORD
#define SWAPDWORD (x) (x)
Macro to swap a DWORD.
Definition at line 100 of file ecatslv.h.
SWAPWORD
#define SWAPWORD (x) (x)
Macro to swap a WORD.
Definition at line 96 of file ecatslv.h.
SYNC0_EVENT
#define SYNC0_EVENT ((UINT16) 0x04)
Sync0 event.
Definition at line 316 of file ecatslv.h.
SYNC1_EVENT
#define SYNC1_EVENT ((UINT16) 0x08)
Sync1 event.
Definition at line 317 of file ecatslv.h.
SYNCMANCHADDRESS
#define SYNCMANCHADDRESS 0x01
Emergency and Diagnosis code for an invalid SyncManager address.
Definition at line 207 of file ecatslv.h.
SYNCMANCHODDADDRESS
#define SYNCMANCHODDADDRESS 0x00
Emergency and Diagnosis code for an odd SyncManager address.
Definition at line 206 of file ecatslv.h.
SYNCMANCHSETTINGS
#define SYNCMANCHSETTINGS 0x03
Emergency and Diagnosis code for an invalid SyncManager settings.
Definition at line 209 of file ecatslv.h.
SYNCMANCHSIZE
#define SYNCMANCHSIZE 0x02
Emergency and Diagnosis code for an invalid SyncManager size.
Definition at line 208 of file ecatslv.h.
SYNCTYPE_DCSYNC0
#define SYNCTYPE_DCSYNC0 0x0002
Sync type Sync0 synchron.
Definition at line 308 of file ecatslv.h.
SYNCTYPE_DCSYNC1
#define SYNCTYPE_DCSYNC1 0x0003
Sync type Sync1 synchron.
Definition at line 309 of file ecatslv.h.
SYNCTYPE_FREERUN
#define SYNCTYPE_FREERUN 0x0000
Sync type FreeRun.
Definition at line 305 of file ecatslv.h.
SYNCTYPE_SM2_SYNCHRON
#define SYNCTYPE_SM2_SYNCHRON 0x0022
SyncManager2 synchron (only used for 0x1C33.1)
Definition at line 307 of file ecatslv.h.
SYNCTYPE_SM_SYNCHRON
#define SYNCTYPE_SM_SYNCHRON 0x0001
SyncManager synchron (synchron to the corresponding SM, 0x1C32.1 -> SM2 ; 0x1C33.1 -> SM3)
Definition at line 306 of file ecatslv.h.
TIMEOUT_FOR_REBOOT
#define TIMEOUT_FOR_REBOOT 1000
Definition at line 46 of file bootmode.c.
Enumeration Type Documentation
BL_STATE
enum BL_STATE
Definition at line 48 of file bootmode.h.
Function Documentation
AL_ControlInd()
PROTO void AL_ControlInd (UINT8 alControl, UINT16 alStatusCode)
This function handles the EtherCAT State Machine. It is called in case of an AL Control event (Bit 0 of AL-Event (Reg 0x220), when the Master has written the AL Control Register (from ECAT_Main), alControl contains the content of the AL Control (Reg 0x120) in case of a SM-Change event (Bit 4 of AL-Event (Reg 0x220)), when an Activate SYNCM y register is written by the master (from ECAT_Main), alControl contains the actual state (Bit 0-3 of AL Status (Reg 0x130)) in case of a locally expired watchdog (from ECAT_Main), alControl contains the requested new state (SAFE_OP) in case of an application specific event to change the EtherCAT state (from application), alControl contains the requested new state (INIT, PRE_OP or SAFE_OP)
Parameters
alControl requested new state
alStatusCode requested status code
Definition at line 1411 of file ecatslv.c.
References ALSTATUSCODE_EE_ERROR, ALSTATUSCODE_INVALIDALCONTROL, ALSTATUSCODE_INVALIDMBXCFGINBOOT, ALSTATUSCODE_INVALIDMBXCFGINPREOP, ALSTATUSCODE_UNKNOWNALCONTROL, APPL_AckErrorInd(), APPL_GenerateMapping(), APPL_StartInputHandler(), APPL_StartMailboxHandler(), APPL_StartOutputHandler(), APPL_StopInputHandler(), APPL_StopMailboxHandler(), APPL_StopOutputHandler(), BackToInitTransition(), bApplEsmPending, bBootMode, bEcatInputUpdateRunning, bEcatOutputUpdateRunning, bEcatWaitForAlControlRes, BL_Start(), BL_Stop(), bMbxRunning, BOOT_2_INIT, BOOT_2_OP, BOOT_2_PREOP, BOOT_2_SAFEOP, CheckSmSettings(), DisableSyncManChannel(), EnableSyncManChannel(), EsmTimeoutCounter, INIT_2_BOOT, INIT_2_INIT, INIT_2_OP, INIT_2_PREOP, INIT_2_SAFEOP, MAILBOX_READ, MAILBOX_WRITE, MBX_StartMailboxHandler(), MBX_StopMailboxHandler(), nAlStatus, nEcatStateTrans, nMaxSyncMan, NOERROR_INWORK, NOERROR_NOSTATECHANGE, nPdInputSize, nPdOutputSize, OP_2_BOOT, OP_2_INIT, OP_2_OP, OP_2_PREOP, OP_2_SAFEOP, PREOP_2_BOOT, PREOP_2_INIT, PREOP_2_OP, PREOP_2_PREOP, PREOP_2_SAFEOP, PROCESS_DATA_IN, PROCESS_DATA_OUT, ResetALEventMask(), SAFEOP_2_BOOT, SAFEOP_2_INIT, SAFEOP_2_OP, SAFEOP_2_PREOP, SAFEOP_2_SAFEOP, SetALEventMask(), SetALStatus(), StartInputHandler(), StartOutputHandler(), STATE_BOOT, STATE_CHANGE, STATE_INIT, STATE_MASK, STATE_OP, STATE_PREOP, STATE_SAFEOP, StopInputHandler(), StopOutputHandler(), and UpdateEEPROMLoadedState().
Referenced by CheckIfEcatError(), ECAT_Main(), and ECAT_StateChange().
AL_ControlRes()
void AL_ControlRes (void)
This function is called cyclic if a state transition is pending (bEcatWaitForAlControlRes == TRUE)
If the ESM timeout is expired the state transition will be rejected. Otherwise the application specific state transition function is called.
If the pending state transition is triggered by the application the transition need to be completed by the application (ECAT_StateChange())
Definition at line 1931 of file ecatslv.c.
References ALSTATUSCODE_NOSYNCERROR, ALSTATUSCODE_SMWATCHDOG, ALSTATUSCODE_SYNCERROR, ALSTATUSCODE_UNSPECIFIEDERROR, APPL_StartInputHandler(), APPL_StartMailboxHandler(), APPL_StartOutputHandler(), APPL_StopInputHandler(), APPL_StopMailboxHandler(), APPL_StopOutputHandler(), bApplEsmPending, bDcRunning, bDcSyncActive, bEcatFirstOutputsReceived, bEcatInputUpdateRunning, bEcatOutputUpdateRunning, bEcatWaitForAlControlRes, bLocalErrorFlag, bMbxRunning, EsmTimeoutCounter, i16WaitForPllRunningCnt, i16WaitForPllRunningTimeout, INIT_2_BOOT, INIT_2_PREOP, MBX_StopMailboxHandler(), nEcatStateTrans, NOERROR_INWORK, nPdOutputSize, PREOP_2_SAFEOP, SAFEOP_2_OP, SetALStatus(), STATE_CHANGE, STATE_MASK, STATE_OP, STATE_SAFEOP, StopInputHandler(), StopOutputHandler(), and u16LocalErrorCode.
Referenced by ECAT_Main().
BackToInitTransition()
void BackToInitTransition (void)
This function is called when a X to Init transition is completed.
Definition at line 1355 of file ecatslv.c.
References bSyncSetByUser.
Referenced by AL_ControlInd().
BL_Data()
PROTO UINT16 BL_Data (UINT16 * pData, UINT16 Size)
Dummy BL_Data function.
Parameters
pData Data pointer
Size Data Length
Returns
FoE error code
Definition at line 145 of file bootmode.c.
References ECAT_FOE_ERRCODE_DISKFULL, ECAT_FOE_ERRCODE_ILLEGAL, ECAT_FOE_ERRCODE_INVALID_CHECKSUM, ECAT_FOE_ERRCODE_INVALID_FIRMWARE, and ECAT_FOE_ERRCODE_PROGERROR.
Referenced by AX58400_FoeWriteData().
BL_Init()
PROTO void BL_Init (void)
Definition at line 97 of file bootmode.c.
BL_Reboot()
PROTO void BL_Reboot (void)
Definition at line 383 of file bootmode.c.
BL_Start()
PROTO void BL_Start (UINT8 State)
Called from INIT to BOOT.
Parameters
State Current state
Definition at line 84 of file bootmode.c.
References STATE_BOOT.
Referenced by AL_ControlInd().
BL_StartDownload()
PROTO void BL_StartDownload (UINT32 password0)
Dummy BL_StartDownload function.
Parameters
password download password
Definition at line 119 of file bootmode.c.
Referenced by AX58400_FoeWrite().
BL_Stop()
PROTO void BL_Stop (void)
Called in the state transition from BOOT to Init.
Definition at line 109 of file bootmode.c.
Referenced by AL_ControlInd().
CheckIfEcatError()
PROTO void CheckIfEcatError (void)
Checks communication and synchronisation variables and update AL status / AL status code if an error has occurred.
Definition at line 2249 of file ecatslv.c.
References AL_ControlInd(), ALSTATUSCODE_FATALSYNCERROR, ALSTATUSCODE_SMWATCHDOG, ALSTATUSCODE_SYNCERROR, bDcRunning, bDcSyncActive, bEcatFirstOutputsReceived, bEcatOutputUpdateRunning, bSmSyncSequenceValid, EcatWdValue, ESC_PD_WD_STATE, ESC_PD_WD_TRIGGER_MASK, nPdOutputSize, STATE_SAFEOP, and SWAPWORD.
Referenced by MainLoop().
CheckSmSettings()
UINT8 CheckSmSettings (UINT8 maxChannel)
This function checks all SM channels.
Parameters
maxChannel last SM channel which should be checked
Returns
0: okay else AL Status Code
Definition at line 390 of file ecatslv.c.
References ALSTATUSCODE_INVALIDMBXCFGINPREOP, ALSTATUSCODE_INVALIDSMINCFG, ALSTATUSCODE_INVALIDSMOUTCFG, ALSTATUSCODE_NOVALIDFIRMWARE, b3BufferMode, bWdTrigger, GetSyncMan(), MAILBOX_READ, MAILBOX_WRITE, nAlStatus, nEscAddrInputData, nEscAddrOutputData, nMaxEscAddress, nMaxSyncMan, nPdInputSize, nPdOutputSize, PROCESS_DATA_IN, PROCESS_DATA_OUT, SM_SETTING_ACTIVATE_OFFSET, SM_SETTING_CONTROL_OFFSET, SM_SETTING_DIRECTION_MASK, SM_SETTING_DIRECTION_READ_VALUE, SM_SETTING_DIRECTION_WRITE_VALUE, SM_SETTING_ENABLE_VALUE, SM_SETTING_MODE_MASK, SM_SETTING_MODE_ONE_BUFFER_VALUE, SM_SETTING_WATCHDOG_VALUE, STATE_PREOP, SYNCMANCHADDRESS, SYNCMANCHSETTINGS, and SYNCMANCHSIZE.
Referenced by AL_ControlInd().
DC_CheckWatchdog()
PROTO void DC_CheckWatchdog (void)
This function checks the current Sync state and set the local flags The analyse of the local flags is handled in "CheckIfEcatError".
Definition at line 2172 of file ecatslv.c.
References bDcRunning, bDcSyncActive, bEcatInputUpdateRunning, bSmSyncSequenceValid, i16WaitForPllRunningCnt, i16WaitForPllRunningTimeout, sErrorSettings, sSyncManOutPar, Sync0WdCounter, Sync0WdValue, Sync1WdCounter, Sync1WdValue, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, and OBJ_STRUCT_PACKED_START::u16SyncErrorCounterLimit.
Referenced by ECAT_CheckTimer().
DisableSyncManChannel()
PROTO void DisableSyncManChannel (UINT8 channel)
This function disables a Sync Manager channel.
Parameters
channel Sync Manager channel
Definition at line 342 of file ecatslv.c.
References SIZEOF_SM_REGISTER, and SM_SETTING_PDI_DISABLE.
Referenced by AL_ControlInd(), ECAT_Init(), MBX_MailboxRepeatReq(), MBX_StopMailboxHandler(), and StopInputHandler().
ECAT_Init()
PROTO void ECAT_Init (void)
This function initialize the EtherCAT Slave Interface.
Definition at line 2428 of file ecatslv.c.
References bApplEsmPending, bBootMode, bDcSyncActive, bEcatFirstOutputsReceived, bEcatInputUpdateRunning, bEcatOutputUpdateRunning, bEcatWaitForAlControlRes, bEscIntEnabled, bLocalErrorFlag, bWdTrigger, COE_Init(), DisableSyncManChannel(), EcatWdValue, ESC_DPRAM_SIZE_OFFSET, ESC_SM_CHANNELS_OFFSET, MBX_Init(), nAlStatus, nEcatStateTrans, nMaxEscAddress, nMaxSyncMan, nPdInputSize, nPdOutputSize, ResetALEventMask(), SetALStatus(), STATE_INIT, Sync0WdCounter, Sync0WdValue, Sync1WdCounter, Sync1WdValue, u16LocalErrorCode, and UpdateEEPROMLoadedState().
Referenced by MainInit().
ECAT_Main()
PROTO void ECAT_Main (void)
This function has to be called cyclically.
Definition at line 2491 of file ecatslv.c.
References AL_CONTROL_EVENT, AL_ControlInd(), AL_ControlRes(), bEcatWaitForAlControlRes, bMbxRepeatToggle, bMbxRunning, ESC_AL_CONTROL_OFFSET, ESC_SYNCMAN_ACTIVE_OFFSET, MAILBOX_READ_EVENT, MAILBOX_WRITE_EVENT, MBX_CheckAndCopyMailbox(), MBX_MailboxReadInd(), MBX_MailboxRepeatReq(), MBX_Main(), nAlStatus, SIZEOF_SM_REGISTER, SM_CHANGE_EVENT, SM_SETTING_ENABLE_VALUE, SM_SETTING_REPAET_REQ_MASK, SM_SETTING_REPEAT_ACK, STATE_CHANGE, STATE_INIT, STATE_MASK, SWAPWORD, and u16EscAddrSendMbx.
Referenced by MainLoop().
ECAT_StateChange()
void ECAT_StateChange (UINT8 alStatus, UINT16 alStatusCode)
This function changes the state of the EtherCAT slave if the requested state is lower than the actual state, otherwise the error condition will be reset.
This function shall be called by the application to trigger state transition in case.
Parameters
alStatus requested state
alStatusCode value for the AL-Status register
Definition at line 2308 of file ecatslv.c.
References AL_ControlInd(), APPL_StopInputHandler(), APPL_StopMailboxHandler(), APPL_StopOutputHandler(), bApplEsmPending, bEcatInputUpdateRunning, bEcatOutputUpdateRunning, bEcatWaitForAlControlRes, bLocalErrorFlag, bMbxRunning, EsmTimeoutCounter, INIT_2_BOOT, INIT_2_PREOP, MBX_StopMailboxHandler(), nAlStatus, nEcatStateTrans, PREOP_2_SAFEOP, SAFEOP_2_OP, SetALEventMask(), SetALStatus(), STATE_CHANGE, STATE_MASK, StopInputHandler(), StopOutputHandler(), and u16LocalErrorCode.
EnableSyncManChannel()
PROTO void EnableSyncManChannel (UINT8 channel)
This function enables a Sync Manager channel.
Parameters
channel Sync Manager channel
Definition at line 363 of file ecatslv.c.
References SIZEOF_SM_REGISTER, and SM_SETTING_PDI_DISABLE.
Referenced by AL_ControlInd(), MBX_MailboxRepeatReq(), MBX_StartMailboxHandler(), and StartInputHandler().
GetSyncMan()
PROTO TSYNCMAN ESCMEM * GetSyncMan (UINT8 channel)
This function is called to read the SYNC Manager channel descriptions of the process data SYNC Managers.
Parameters
channel Sync Manager channel
Returns
pPdSyncMan Pointer to the settings of requested SYNC Manager channel
Definition at line 327 of file ecatslv.c.
References ESC_SYNCMAN_REG_OFFSET, and SIZEOF_SM_REGISTER.
Referenced by CheckSmSettings(), MBX_StartMailboxHandler(), and StartInputHandler().
ResetALEventMask()
void ResetALEventMask (UINT16 intMask)
This function makes an logical and with the AL Event Mask register (0x204)
Parameters
intMask interrupt mask (disabled interrupt shall be zero)
Definition at line 248 of file ecatslv.c.
References ESC_AL_EVENTMASK_OFFSET.
Referenced by AL_ControlInd(), ECAT_Init(), and StopInputHandler().
SetALEventMask()
void SetALEventMask (UINT16 intMask)
This function makes an logical or with the AL Event Mask register (0x204)
Parameters
intMask interrupt mask (enabled interrupt shall be one)
Definition at line 269 of file ecatslv.c.
References ESC_AL_EVENTMASK_OFFSET.
Referenced by AL_ControlInd(), and ECAT_StateChange().
SetALStatus()
PROTO void SetALStatus (UINT8 alStatus, UINT16 alStatusCode)
The function changes the state of the EtherCAT ASIC to the requested.
Parameters
alStatus New AL Status (written to register 0x130)
alStatusCode New AL Status Code (written to register 0x134)
Definition at line 1368 of file ecatslv.c.
References ESC_AL_STATUS_CODE_OFFSET, ESC_AL_STATUS_OFFSET, nAlStatus, and SWAPWORD.
Referenced by AL_ControlInd(), AL_ControlRes(), ECAT_Init(), and ECAT_StateChange().
StartInputHandler()
UINT16 StartInputHandler (void)
This function is called in case of the state transition from PREOP to SAFEOP. |brief the areas of the Sync Managers will be checked for overlapping,.
Returns
AL Status Code (see ecatslv.h ALSTATUSCODE_....)
the synchronization mode (Free Run, Synchron, Distributed Clocks) is selected,
the requested cycle time will be checked, the watchdog is started
and the AL Event Mask register will be set
Definition at line 677 of file ecatslv.c.
References ALSTATUSCODE_DCINVALIDSYNCCFG, ALSTATUSCODE_DCSYNC0CYCLETIME, ALSTATUSCODE_FREERUNNEEDS3BUFFERMODE, ALSTATUSCODE_INVALIDSMINCFG, ALSTATUSCODE_INVALIDSMOUTCFG, ALSTATUSCODE_INVALIDWDCFG, ALSTATUSCODE_NOERROR, b3BufferMode, bDcRunning, bDcSyncActive, bEcatFirstOutputsReceived, bEscIntEnabled, bSmSyncSequenceValid, bSyncSetByUser, bWdTrigger, EcatWdValue, EnableSyncManChannel(), ESC_DC_SYNC0_ACTIVE_MASK, ESC_DC_SYNC0_CYCLETIME_OFFSET, ESC_DC_SYNC1_ACTIVE_MASK, ESC_DC_SYNC1_CYCLETIME_OFFSET, ESC_DC_SYNC_ACTIVATION_OFFSET, ESC_DC_SYNC_UNIT_ACTIVE_MASK, ESC_DC_SYNC_UNIT_AUTO_ACTIVE_MASK, ESC_PD_WD_TIME, ESC_WD_DIVIDER_OFFSET, GetSyncMan(), i16WaitForPllRunningTimeout, LatchInputSync0Counter, LatchInputSync0Value, nEscAddrInputData, nEscAddrOutputData, nPdInputSize, nPdOutputSize, PDO_InputMapping(), PROCESS_DATA_IN, PROCESS_DATA_OUT, PROCESS_INPUT_EVENT, PROCESS_OUTPUT_EVENT, sCycleDiag, SM_SETTING_CONTROL_OFFSET, SM_SETTING_MODE_ONE_BUFFER_VALUE, sSyncManInPar, sSyncManOutPar, SWAPDWORD, SWAPWORD, Sync0WdCounter, Sync0WdValue, Sync1WdCounter, Sync1WdValue, OBJ_STRUCT_PACKED_START::syncFailedCounter, SYNCTYPE_DCSYNC0, SYNCTYPE_DCSYNC0SUPP, SYNCTYPE_DCSYNC1, SYNCTYPE_DCSYNC1SUPP, SYNCTYPE_FREERUN, SYNCTYPE_SM2_SYNCHRON, SYNCTYPE_SM_SYNCHRON, SYNCTYPE_SUBCYCLESUPP, OBJ_STRUCT_PACKED_START::u16CycleExceededCounter, u16EscAddrReceiveMbx, u16EscAddrSendMbx, u16ReceiveMbxSize, u16SendMbxSize, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, u16SmSync0Counter, u16SmSync0Value, OBJ_STRUCT_PACKED_START::u16SyncType, OBJ_STRUCT_PACKED_START::u16SyncTypesSupported, OBJ_STRUCT_PACKED_START::u32CycleTime, OBJ_STRUCT_PACKED_START::u32MinCycleTime, OBJ_STRUCT_PACKED_START::u32Sync0CycleTime, and OBJ_STRUCT_PACKED_START::u8SyncError.
Referenced by AL_ControlInd().
StartOutputHandler()
UINT16 StartOutputHandler (void)
This function is called in case of the state transition from SAFEOP to OP.
Returns
AL Status Code (see ecatslv.h ALSTATUSCODE_....)
It will be checked if outputs had to be received before switching to OP
and the state transition would be refused if outputs are missing
Definition at line 1230 of file ecatslv.c.
References bDcSyncActive, bLocalErrorFlag, i16WaitForPllRunningCnt, i16WaitForPllRunningTimeout, NOERROR_INWORK, sSyncManInPar, sSyncManOutPar, u16LocalErrorCode, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, and OBJ_STRUCT_PACKED_START::u8SyncError.
Referenced by AL_ControlInd().
StopInputHandler()
void StopInputHandler (void)
This function is called in case of the state transition from SAFEOP to PREOP.
Definition at line 1288 of file ecatslv.c.
References bDcRunning, bDcSyncActive, bEcatFirstOutputsReceived, bEcatInputUpdateRunning, bEscIntEnabled, bSmSyncSequenceValid, bSyncSetByUser, bWdTrigger, DisableSyncManChannel(), i16WaitForPllRunningTimeout, LatchInputSync0Counter, LatchInputSync0Value, nPdInputSize, nPdOutputSize, PROCESS_DATA_IN, PROCESS_DATA_OUT, PROCESS_INPUT_EVENT, PROCESS_OUTPUT_EVENT, ResetALEventMask(), sSyncManInPar, sSyncManOutPar, SYNC0_EVENT, Sync0WdCounter, Sync0WdValue, SYNC1_EVENT, Sync1WdCounter, Sync1WdValue, OBJ_STRUCT_PACKED_START::u16CycleExceededCounter, OBJ_STRUCT_PACKED_START::u16SmEventMissedCounter, u16SmSync0Counter, u16SmSync0Value, and OBJ_STRUCT_PACKED_START::u8SyncError.
Referenced by AL_ControlInd(), AL_ControlRes(), and ECAT_StateChange().
StopOutputHandler()
void StopOutputHandler (void)
This function is called in case of the state transition from OP to SAFEOP.
the outputs can be set to an application specific safe state,
the state transition can be delayed by returning NOERROR_INWORK
Definition at line 1275 of file ecatslv.c.
References bEcatFirstOutputsReceived, and bEcatOutputUpdateRunning.
Referenced by AL_ControlInd(), AL_ControlRes(), and ECAT_StateChange().
UpdateEEPROMLoadedState()
void UpdateEEPROMLoadedState (void)
This function reads the EEPROM loaded state.
Definition at line 290 of file ecatslv.c.
References ESC_EEPROM_ERROR_CRC, ESC_EEPROM_ERROR_LOAD, and SWAPWORD.
Referenced by AL_ControlInd(), and ECAT_Init().
Variable Documentation
b32BitDc
PROTO BOOL b32BitDc
Definition at line 399 of file ecatslv.h.
b3BufferMode
PROTO BOOL b3BufferMode
Indicates that inputs and outputs are running in 3-Buffer-Mode.
Definition at line 407 of file ecatslv.h.
Referenced by CheckSmSettings(), and StartInputHandler().
bApplEsmPending
PROTO BOOL bApplEsmPending
Indicates if the local application ESM function need to be called from Al_ConntrolRes (is true if NOERR_INWORK is returned by generic ESM function)
Definition at line 411 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), ECAT_Init(), and ECAT_StateChange().
bBootMode
PROTO BOOL bBootMode
Indicates in slave is in BOOT mode.
Definition at line 358 of file ecatslv.h.
Referenced by AL_ControlInd(), AX58400_FoeWrite(), AX58400_FoeWriteData(), ECAT_Init(), FOE_ServiceInd(), and MailboxServiceInd().
bDcRunning
PROTO BOOL bDcRunning
Indicates if Sync0 events are received.
Definition at line 378 of file ecatslv.h.
Referenced by AL_ControlRes(), CheckIfEcatError(), DC_CheckWatchdog(), StartInputHandler(), and StopInputHandler().
bDcSyncActive
PROTO BOOL bDcSyncActive
Indicates that the Distributed Clocks synchronization is active,.
Definition at line 371 of file ecatslv.h.
Referenced by AL_ControlRes(), APPL_StartInputHandler(), CheckIfEcatError(), CiA402_Application(), DC_CheckWatchdog(), ECAT_Init(), HandleCycleTimeMeasurement(), MainLoop(), StartInputHandler(), StartOutputHandler(), and StopInputHandler().
bEcatFirstOutputsReceived
PROTO BOOL bEcatFirstOutputsReceived
Indicates if outputs were received (SM2-event) or inputs were read (SM3-event, if the output size is 0), has to be set by the application and reset in StopOutputHandler.
Definition at line 365 of file ecatslv.h.
Referenced by AL_ControlRes(), CheckIfEcatError(), ECAT_Init(), MainLoop(), StartInputHandler(), StopInputHandler(), and StopOutputHandler().
bEcatInputUpdateRunning
PROTO BOOL bEcatInputUpdateRunning
Indicates the SAFEOP or OP state, will be set in StartInputHandler and reset in Stop InputHandler.
Definition at line 362 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), DC_CheckWatchdog(), ECAT_Init(), ECAT_StateChange(), MainLoop(), and StopInputHandler().
bEcatOutputUpdateRunning
PROTO BOOL bEcatOutputUpdateRunning
Indicates the OP state, will be set in StartOutputHandler and reset in StopOutputHandler.
Definition at line 359 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), CheckIfEcatError(), ECAT_Init(), ECAT_StateChange(), MainLoop(), and StopOutputHandler().
bEcatWaitForAlControlRes
PROTO BOOL bEcatWaitForAlControlRes
Contains the information that the state machine waits for an acknowledge for the last AL_ControlInd from the application/generic stack.
Definition at line 412 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), ECAT_CheckTimer(), ECAT_Init(), ECAT_Main(), and ECAT_StateChange().
bEscIntEnabled
PROTO BOOL bEscIntEnabled
Indicates that the ESC interrupt is enabled (SM2/3 or SYNC0/1-event), will be set in StartInputHandler and reset in StopInputHandler.
Definition at line 404 of file ecatslv.h.
Referenced by ECAT_Init(), MainLoop(), StartInputHandler(), and StopInputHandler().
bLocalErrorFlag
PROTO BOOL bLocalErrorFlag
Contains the information if the application has a local error.
Definition at line 409 of file ecatslv.h.
Referenced by AL_ControlRes(), ECAT_Init(), ECAT_StateChange(), and StartOutputHandler().
bSmSyncSequenceValid
PROTO BOOL bSmSyncSequenceValid
Set to true if SM/Sync0 sequence is valid.
Definition at line 383 of file ecatslv.h.
Referenced by CheckIfEcatError(), DC_CheckWatchdog(), StartInputHandler(), and StopInputHandler().
bWdTrigger
PROTO BOOL bWdTrigger
Indicates that the SM2 WD trigger bit (0x814 bit6) is set.
Definition at line 369 of file ecatslv.h.
Referenced by CheckSmSettings(), ECAT_Init(), StartInputHandler(), and StopInputHandler().
dwordData
unsigned long dwordData[8]
Definition at line 74 of file bootmode.c.
EcatWdValue
PROTO UINT16 EcatWdValue
Contains the value of the watchdog in ms, will be written in StartInputHandler. In case that the ESC watchdog feature is used this variable just indicates if the watchdog is enabled or disabled.
Definition at line 429 of file ecatslv.h.
Referenced by CheckIfEcatError(), ECAT_Init(), and StartInputHandler().
EepromLoaded
BOOL EepromLoaded = FALSE
Definition at line 233 of file ecatslv.c.
EsmTimeoutCounter
PROTO INT16 EsmTimeoutCounter
Counter used to detect an ESM timeout. -1 indicates a deactivated counter and 0 is expired.
Definition at line 373 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), ECAT_CheckTimer(), and ECAT_StateChange().
firmwareHeader
UPGRADE_RT_HEAD firmwareHeader
Definition at line 71 of file bootmode.c.
firmwareObj
UPGRADE_FIRMWARE firmwareObj
Definition at line 70 of file bootmode.c.
foeLeftBytes
UINT16 foeLeftBytes
Definition at line 73 of file bootmode.c.
i16WaitForPllRunningCnt
PROTO INT16 i16WaitForPllRunningCnt
Incremented with every valid Sync-SyncManger cycle.
Definition at line 387 of file ecatslv.h.
Referenced by AL_ControlRes(), DC_CheckWatchdog(), and StartOutputHandler().
i16WaitForPllRunningTimeout
PROTO INT16 i16WaitForPllRunningTimeout
The time bPllRunnig shall be true while state change from SafeOp to Op.
Definition at line 385 of file ecatslv.h.
Referenced by AL_ControlRes(), DC_CheckWatchdog(), StartInputHandler(), StartOutputHandler(), and StopInputHandler().
LatchInputSync0Counter
PROTO UINT16 LatchInputSync0Counter
Sync0 counter used to get the Sync0 event to latch the Inputs.
Definition at line 396 of file ecatslv.h.
Referenced by StartInputHandler(), and StopInputHandler().
LatchInputSync0Value
PROTO UINT16 LatchInputSync0Value
Sync0 event on which the inputs shall be latched and copied to the ESC buffer. If the inputs shall be latched base don Sync1 the value is set to 0.
Definition at line 395 of file ecatslv.h.
Referenced by StartInputHandler(), and StopInputHandler().
nAlStatus
PROTO UINT8 nAlStatus
Contains the actual AL Status, will be written in AL_ControlInd.
Definition at line 426 of file ecatslv.h.
Referenced by AL_ControlInd(), CheckSmSettings(), CiA402_StateMachine(), ECAT_Init(), ECAT_Main(), ECAT_StateChange(), MBX_CopyToSendMailbox(), MBX_MailboxSendReq(), OBJ_Read(), OBJ_Write(), and SetALStatus().
nEcatStateTrans
PROTO UINT16 nEcatStateTrans
Current state transition.
Definition at line 415 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), ECAT_Init(), and ECAT_StateChange().
nEscAddrInputData
PROTO UINT16 nEscAddrInputData
Contains the SM address for the input process data.
Definition at line 432 of file ecatslv.h.
Referenced by CheckSmSettings(), PDO_InputMapping(), and StartInputHandler().
nEscAddrOutputData
PROTO UINT16 nEscAddrOutputData
Contains the SM address for the output process data.
Definition at line 431 of file ecatslv.h.
Referenced by CheckSmSettings(), PDO_OutputMapping(), and StartInputHandler().
nMaxEscAddress
PROTO UINT16 nMaxEscAddress
Max supported address by the ESC (register(0x1000) + size of the supported DPRAM in Byte)
Definition at line 424 of file ecatslv.h.
Referenced by CheckSmSettings(), and ECAT_Init().
nMaxSyncMan
PROTO UINT8 nMaxSyncMan
Contains the maximum number of Sync Manager channels, will be initialized in ECAT_Main.
Definition at line 422 of file ecatslv.h.
Referenced by AL_ControlInd(), CheckSmSettings(), and ECAT_Init().
nPdInputSize
PROTO UINT16 nPdInputSize
Contains the input size (SM3 size)/SM2 if no outputs are supported, has to be written by the application.
Definition at line 418 of file ecatslv.h.
Referenced by AL_ControlInd(), CheckSmSettings(), CheckSyncTypeValue(), CiA402_DeallocateAxis(), ECAT_Application(), ECAT_Init(), PDO_InputMapping(), StartInputHandler(), and StopInputHandler().
nPdOutputSize
PROTO UINT16 nPdOutputSize
Contains the output size (SM2 size), has to be written by the application.
Definition at line 420 of file ecatslv.h.
Referenced by AL_ControlInd(), AL_ControlRes(), CheckIfEcatError(), CheckSmSettings(), CheckSyncTypeValue(), CiA402_DeallocateAxis(), ECAT_Application(), ECAT_Init(), MainLoop(), PDO_OutputMapping(), StartInputHandler(), and StopInputHandler().
SMActivate
VARVOLATILE UINT8 SMActivate = 0
Definition at line 228 of file ecatslv.c.
Sync0WdCounter
PROTO UINT16 Sync0WdCounter
Sync0 watchdog counter.
Definition at line 389 of file ecatslv.h.
Referenced by DC_CheckWatchdog(), ECAT_Init(), StartInputHandler(), and StopInputHandler().
Sync0WdValue
PROTO UINT16 Sync0WdValue
Sync0 watchdog value.
Definition at line 390 of file ecatslv.h.
Referenced by DC_CheckWatchdog(), ECAT_Init(), StartInputHandler(), and StopInputHandler().
Sync1WdCounter
PROTO UINT16 Sync1WdCounter
Sync1 watchdog counter.
Definition at line 392 of file ecatslv.h.
Referenced by DC_CheckWatchdog(), ECAT_Init(), StartInputHandler(), and StopInputHandler().
Sync1WdValue
PROTO UINT16 Sync1WdValue
Sync1 watchdog value.
Definition at line 393 of file ecatslv.h.
Referenced by DC_CheckWatchdog(), ECAT_Init(), StartInputHandler(), and StopInputHandler().
SyncManInfo
TSYNCMAN SyncManInfo
Definition at line 230 of file ecatslv.c.
timerForJumpToBldr
UINT16 timerForJumpToBldr
Definition at line 72 of file bootmode.c.
u16ALEventMask
UINT16 u16ALEventMask
Definition at line 222 of file ecatslv.c.
u16LocalErrorCode
PROTO UINT16 u16LocalErrorCode
Reason for local error.
Definition at line 410 of file ecatslv.h.
Referenced by AL_ControlRes(), ECAT_Init(), ECAT_StateChange(), and StartOutputHandler().
u16SmSync0Counter
PROTO UINT16 u16SmSync0Counter
/brief Incremented by one on every Sync0 event and reset to 0 on every SM event. It is used to check the SM/Sync0 sequence
Definition at line 380 of file ecatslv.h.
Referenced by StartInputHandler(), and StopInputHandler().
u16SmSync0Value
PROTO UINT16 u16SmSync0Value
/brief Allowed Sync0 events within one SM cycle. If 0 the Sequence check is disabled
Definition at line 381 of file ecatslv.h.
Referenced by StartInputHandler(), and StopInputHandler().
u8dummy
VARVOLATILE UINT8 u8dummy
Definition at line 225 of file ecatslv.c.