AX58400-CM7: FileTransfer over EtherCAT
FileTransfer over EtherCAT
Files
file ecatfoe.c
Implementation This file contains the FoE mailbox interface.
file ecatfoe.h
file foeappl.c
Implementation This file contains an example how to use the FoE services.
file foeappl.h
Data Structures
struct MBX_STRUCT_PACKED_START
CoE Mailbox header.
Macros
#define _ECATFOE_ 1
#define _ECATFOE_ 0
#define ECAT_FOE_OPCODE_RRQ 1
Read request.
#define ECAT_FOE_OPCODE_WRQ 2
Write request.
#define ECAT_FOE_OPCODE_DATA 3
Data datagram.
#define ECAT_FOE_OPCODE_ACK 4
Acknowledge datagram.
#define ECAT_FOE_OPCODE_ERR 5
Error datagram.
#define ECAT_FOE_OPCODE_BUSY 6
Busy datagram.
#define FOE_READY 0
Ready state.
#define FOE_WAIT_FOR_ACK 1
Wait for acknowledgement state.
#define FOE_WAIT_FOR_DATA 2
Wait for data state.
#define FOE_WAIT_FOR_RESET 3
Wait for reset state.
#define FOE_WAIT_FOR_LAST_ACK 4
Wait for last acknowledgement state.
#define FOE_PROGRAMMING 5
Programming state.
#define FOE_WAIT_FOR_LAST_DATA 6
Wait for last data state.
#define FW_UPDATE_SIZE SIZEOF(TEFWUPDATE)
#define FOE_HEADER_SIZE SIZEOF(TFOEHEADER)
FoE header size.
#define FOE_ERROR 0x8000
Error result.
#define FOE_FINISHED ((FOE_ERROR)-1)
Datagram finished.
#define FOE_FINISHED_NOACK ((FOE_FINISHED)-1)
Datagram finished no acknowledgement.
#define FOE_ACK ((FOE_FINISHED_NOACK)-1)
Acknowledgement.
#define FOE_ACKFINISHED ((FOE_ACK)-1)
Acknowledgement finished.
#define FOE_WAIT ((FOE_ACKFINISHED)-1)
Wait.
#define FOE_MAXBUSY ((FOE_WAIT)-1)
Max busy indication.
#define FOE_MAXBUSY_ZERO ((FOE_MAXBUSY)-100)
Min busy indication.
#define FOE_MAXDATA ((FOE_MAXBUSY_ZERO)-1)
Maximum data within one FoE Datagram.
#define PROTO extern
#define _FOEAPPL_ 1
#define _FOEAPPL_ 0
#define ECAT_FOE_ERRCODE_NOTDEFINED 0x8000
Not defined.
#define ECAT_FOE_ERRCODE_NOTFOUND 0x8001
The file requested by an FoE upload service could not be found on the server.
#define ECAT_FOE_ERRCODE_ACCESS 0x8002
Read or write access to this file not allowed (e.g. due to local control).
#define ECAT_FOE_ERRCODE_DISKFULL 0x8003
Disk to store file is full or memory allocation exceeded.
#define ECAT_FOE_ERRCODE_ILLEGAL 0x8004
Illegal FoE operation, e.g. service identifier invalid.
#define ECAT_FOE_ERRCODE_PACKENO 0x8005
FoE packet number invalid.
#define ECAT_FOE_ERRCODE_EXISTS 0x8006
The file which is requested to be downloaded does already exist.
#define ECAT_FOE_ERRCODE_NOUSER 0x8007
No User.
#define ECAT_FOE_ERRCODE_BOOTSTRAPONLY 0x8008
FoE only supported in Bootstrap.
#define ECAT_FOE_ERRCODE_NOTINBOOTSTRAP 0x8009
This file may not be accessed in BOOTSTRAP state.
#define ECAT_FOE_ERRCODE_NORIGHTS 0x800A
Password invalid.
#define ECAT_FOE_ERRCODE_PROGERROR 0x800B
Generic programming error. Should only be returned if error reason cannot be distinguished.
#define ECAT_FOE_ERRCODE_INVALID_CHECKSUM 0x800C
checksum included in the file is invalid
#define ECAT_FOE_ERRCODE_INVALID_FIRMWARE 0x800D
The hardware does not support the downloaded firmware.
#define ECAT_FOE_ERRCODE_NO_FILE 0x800F
Do not use (identical with 0x8001)
#define ECAT_FOE_ERRCODE_NO_FILE_HEADER 0x8010
Missing file header of error in file header.
#define ECAT_FOE_ERRCODE_FLASH_ERROR 0x8011
Flash cannot be accessed.
#define PROTO extern
Typedefs
typedef struct MBX_STRUCT_PACKED_START TEFWUPDATE
typedef struct MBX_STRUCT_PACKED_START TFOEHEADER
FoE header.
typedef struct MBX_STRUCT_PACKED_START TFOEMBX
Complete FoE datagram.
Functions
void FOE_Init (void)
This function initialize the FoE Interface.
UINT8 FOE_ServiceInd (TFOEMBX MBXMEM *pFoeInd)
This function is called when a FoE (File Access over EtherCAT) service is received from the master.
void FOE_ContinueInd (TMBX MBXMEM *pMbx)
This function is called when the next mailbox fragment can be sent.
UINT16 FOE_Read (UINT16 MBXMEM *pName, UINT16 nameSize, UINT16 MBXMEM *pData, UINT32 password)
The function starts a file reading.
UINT16 FOE_Write (UINT16 MBXMEM *pName, UINT16 nameSize, UINT32 password)
The function starts a file writing.
UINT16 FOE_Data (UINT16 MBXMEM *pData, UINT16 Size)
The function is called to write the next part of a file.
UINT16 FOE_Ack (UINT32 fileOffset, UINT16 MBXMEM *pData)
The function is called when the reading of a part of a file is acknowledged.
UINT16 FOE_Busy (UINT16 done, UINT32 fileOffset, UINT16 MBXMEM *pData)
The function is called when the reading of a part of a file should be repeated.
void FOE_Error (UINT32 errorCode)
The function is called when a file transfer is aborted from the other station.
Variables
PROTO UINT32 u32PacketNo
Stores the actual packet number to be expected.
PROTO UINT32 u32FileOffset
Stores the next file offset to be sent.
PROTO UINT32 u32LastFileOffset
Stores the actual sent file offset.
PROTO UINT16 u16FileAccessState
Stores the actual state of the file transmission sequence.
PROTO TMBX MBXMEM * pFoeSendStored
PROTO UINT16 u16FoeMaxSendBlockSize
indicates the maximum size of an FoE fragment (from the slave to the master)
Detailed Description
Macro Definition Documentation
_ECATFOE_ [1/2]
#define _ECATFOE_ 1
Definition at line 62 of file ecatfoe.c.
_ECATFOE_ [2/2]
#define _ECATFOE_ 0
Definition at line 62 of file ecatfoe.c.
_FOEAPPL_ [1/2]
#define _FOEAPPL_ 1
Definition at line 56 of file foeappl.c.
_FOEAPPL_ [2/2]
#define _FOEAPPL_ 0
Definition at line 56 of file foeappl.c.
ECAT_FOE_ERRCODE_ACCESS
#define ECAT_FOE_ERRCODE_ACCESS 0x8002
Read or write access to this file not allowed (e.g. due to local control).
Definition at line 44 of file foeappl.h.
ECAT_FOE_ERRCODE_BOOTSTRAPONLY
#define ECAT_FOE_ERRCODE_BOOTSTRAPONLY 0x8008
FoE only supported in Bootstrap.
Definition at line 50 of file foeappl.h.
ECAT_FOE_ERRCODE_DISKFULL
#define ECAT_FOE_ERRCODE_DISKFULL 0x8003
Disk to store file is full or memory allocation exceeded.
Definition at line 45 of file foeappl.h.
ECAT_FOE_ERRCODE_EXISTS
#define ECAT_FOE_ERRCODE_EXISTS 0x8006
The file which is requested to be downloaded does already exist.
Definition at line 48 of file foeappl.h.
ECAT_FOE_ERRCODE_FLASH_ERROR
#define ECAT_FOE_ERRCODE_FLASH_ERROR 0x8011
Flash cannot be accessed.
Definition at line 58 of file foeappl.h.
ECAT_FOE_ERRCODE_ILLEGAL
#define ECAT_FOE_ERRCODE_ILLEGAL 0x8004
Illegal FoE operation, e.g. service identifier invalid.
Definition at line 46 of file foeappl.h.
ECAT_FOE_ERRCODE_INVALID_CHECKSUM
#define ECAT_FOE_ERRCODE_INVALID_CHECKSUM 0x800C
checksum included in the file is invalid
Definition at line 54 of file foeappl.h.
ECAT_FOE_ERRCODE_INVALID_FIRMWARE
#define ECAT_FOE_ERRCODE_INVALID_FIRMWARE 0x800D
The hardware does not support the downloaded firmware.
Definition at line 55 of file foeappl.h.
ECAT_FOE_ERRCODE_NO_FILE
#define ECAT_FOE_ERRCODE_NO_FILE 0x800F
Do not use (identical with 0x8001)
Definition at line 56 of file foeappl.h.
ECAT_FOE_ERRCODE_NO_FILE_HEADER
#define ECAT_FOE_ERRCODE_NO_FILE_HEADER 0x8010
Missing file header of error in file header.
Definition at line 57 of file foeappl.h.
ECAT_FOE_ERRCODE_NORIGHTS
#define ECAT_FOE_ERRCODE_NORIGHTS 0x800A
Password invalid.
Definition at line 52 of file foeappl.h.
ECAT_FOE_ERRCODE_NOTDEFINED
#define ECAT_FOE_ERRCODE_NOTDEFINED 0x8000
Not defined.
Definition at line 42 of file foeappl.h.
ECAT_FOE_ERRCODE_NOTFOUND
#define ECAT_FOE_ERRCODE_NOTFOUND 0x8001
The file requested by an FoE upload service could not be found on the server.
Definition at line 43 of file foeappl.h.
ECAT_FOE_ERRCODE_NOTINBOOTSTRAP
#define ECAT_FOE_ERRCODE_NOTINBOOTSTRAP 0x8009
This file may not be accessed in BOOTSTRAP state.
Definition at line 51 of file foeappl.h.
ECAT_FOE_ERRCODE_NOUSER
#define ECAT_FOE_ERRCODE_NOUSER 0x8007
No User.
Definition at line 49 of file foeappl.h.
ECAT_FOE_ERRCODE_PACKENO
#define ECAT_FOE_ERRCODE_PACKENO 0x8005
FoE packet number invalid.
Definition at line 47 of file foeappl.h.
ECAT_FOE_ERRCODE_PROGERROR
#define ECAT_FOE_ERRCODE_PROGERROR 0x800B
Generic programming error. Should only be returned if error reason cannot be distinguished.
Definition at line 53 of file foeappl.h.
ECAT_FOE_OPCODE_ACK
#define ECAT_FOE_OPCODE_ACK 4
Acknowledge datagram.
Definition at line 53 of file ecatfoe.h.
ECAT_FOE_OPCODE_BUSY
#define ECAT_FOE_OPCODE_BUSY 6
Busy datagram.
Definition at line 55 of file ecatfoe.h.
ECAT_FOE_OPCODE_DATA
#define ECAT_FOE_OPCODE_DATA 3
Data datagram.
Definition at line 52 of file ecatfoe.h.
ECAT_FOE_OPCODE_ERR
#define ECAT_FOE_OPCODE_ERR 5
Error datagram.
Definition at line 54 of file ecatfoe.h.
ECAT_FOE_OPCODE_RRQ
#define ECAT_FOE_OPCODE_RRQ 1
Read request.
Definition at line 50 of file ecatfoe.h.
ECAT_FOE_OPCODE_WRQ
#define ECAT_FOE_OPCODE_WRQ 2
Write request.
Definition at line 51 of file ecatfoe.h.
FOE_ACK
#define FOE_ACK ((FOE_FINISHED_NOACK)-1)
Acknowledgement.
Definition at line 150 of file ecatfoe.h.
FOE_ACKFINISHED
#define FOE_ACKFINISHED ((FOE_ACK)-1)
Acknowledgement finished.
Definition at line 151 of file ecatfoe.h.
FOE_ERROR
#define FOE_ERROR 0x8000
Error result.
Definition at line 147 of file ecatfoe.h.
FOE_FINISHED
#define FOE_FINISHED ((FOE_ERROR)-1)
Datagram finished.
Definition at line 148 of file ecatfoe.h.
FOE_FINISHED_NOACK
#define FOE_FINISHED_NOACK ((FOE_FINISHED)-1)
Datagram finished no acknowledgement.
Definition at line 149 of file ecatfoe.h.
FOE_HEADER_SIZE
#define FOE_HEADER_SIZE SIZEOF(TFOEHEADER)
FoE header size.
Definition at line 130 of file ecatfoe.h.
FOE_MAXBUSY
#define FOE_MAXBUSY ((FOE_WAIT)-1)
Max busy indication.
Definition at line 153 of file ecatfoe.h.
FOE_MAXBUSY_ZERO
#define FOE_MAXBUSY_ZERO ((FOE_MAXBUSY)-100)
Min busy indication.
Definition at line 154 of file ecatfoe.h.
FOE_MAXDATA
#define FOE_MAXDATA ((FOE_MAXBUSY_ZERO)-1)
Maximum data within one FoE Datagram.
Definition at line 155 of file ecatfoe.h.
FOE_PROGRAMMING
#define FOE_PROGRAMMING 5
Programming state.
Definition at line 66 of file ecatfoe.h.
FOE_READY
#define FOE_READY 0
Ready state.
Definition at line 61 of file ecatfoe.h.
FOE_WAIT
#define FOE_WAIT ((FOE_ACKFINISHED)-1)
Wait.
Definition at line 152 of file ecatfoe.h.
FOE_WAIT_FOR_ACK
#define FOE_WAIT_FOR_ACK 1
Wait for acknowledgement state.
Definition at line 62 of file ecatfoe.h.
FOE_WAIT_FOR_DATA
#define FOE_WAIT_FOR_DATA 2
Wait for data state.
Definition at line 63 of file ecatfoe.h.
FOE_WAIT_FOR_LAST_ACK
#define FOE_WAIT_FOR_LAST_ACK 4
Wait for last acknowledgement state.
Definition at line 65 of file ecatfoe.h.
FOE_WAIT_FOR_LAST_DATA
#define FOE_WAIT_FOR_LAST_DATA 6
Wait for last data state.
Definition at line 67 of file ecatfoe.h.
FOE_WAIT_FOR_RESET
#define FOE_WAIT_FOR_RESET 3
Wait for reset state.
Definition at line 64 of file ecatfoe.h.
FW_UPDATE_SIZE
#define FW_UPDATE_SIZE SIZEOF(TEFWUPDATE)
Definition at line 92 of file ecatfoe.h.
PROTO [1/2]
#define PROTO extern
Definition at line 162 of file ecatfoe.h.
PROTO [2/2]
#define PROTO extern
Definition at line 66 of file foeappl.h.
Function Documentation
FOE_Ack()
PROTO UINT16 FOE_Ack (UINT32 fileOffset, UINT16 MBXMEM * pData)
The function is called when the reading of a part of a file is acknowledged.
Parameters
fileOffset Offset of the next file data to be sent
pData Buffer for file data to be sent
Returns
size of the data to be sent, busy or an error code 0 (all data was sent before) 1..MAX_FILE_SIZE (size of data to be sent) FOE_MAXBUSY-100 (0%) (busy) FOE_MAXBUSY (100%) (busy) ECAT_FOE_ERRCODE_NOTDEFINED (error) ECAT_FOE_ERRCODE_NOTFOUND (error) ECAT_FOE_ERRCODE_ACCESS (error) ECAT_FOE_ERRCODE_DISKFULL (error) ECAT_FOE_ERRCODE_ILLEGAL (error) ECAT_FOE_ERRCODE_PACKENO (error) ECAT_FOE_ERRCODE_EXISTS (error) ECAT_FOE_ERRCODE_NOUSER (error)
Definition at line 243 of file foeappl.c.
References ECAT_FOE_ERRCODE_NOTDEFINED, pAPPL_FoeReadData, and u16FoeMaxSendBlockSize.
Referenced by FOE_Busy(), and FOE_ServiceInd().
FOE_Busy()
PROTO UINT16 FOE_Busy (UINT16 done, UINT32 fileOffset, UINT16 MBXMEM * pData)
The function is called when the reading of a part of a file should be repeated.
Parameters
done Indicates how much of the busy action is done
fileOffset Offset of the next file data to be sent
pData Buffer for file data to be sent
Returns
size of the data to be sent, busy or an error code 0 (all data was sent before) 1..MAX_FILE_SIZE (size of data to be sent) FOE_MAXBUSY-100 (0%) (busy) FOE_MAXBUSY (100%) (busy) ECAT_FOE_ERRCODE_NOTDEFINED (error) ECAT_FOE_ERRCODE_NOTFOUND (error) ECAT_FOE_ERRCODE_ACCESS (error) ECAT_FOE_ERRCODE_DISKFULL (error) ECAT_FOE_ERRCODE_ILLEGAL (error) ECAT_FOE_ERRCODE_PACKENO (error) ECAT_FOE_ERRCODE_EXISTS (error) ECAT_FOE_ERRCODE_NOUSER (error)
Definition at line 281 of file foeappl.c.
References FOE_Ack().
Referenced by FOE_ServiceInd().
FOE_ContinueInd()
PROTO void FOE_ContinueInd (TMBX MBXMEM * pMbx)
This function is called when the next mailbox fragment can be sent.
Parameters
pMbx Pointer to the free mailbox buffer
Definition at line 418 of file ecatfoe.c.
References MBX_MailboxSendReq(), and pFoeSendStored.
Referenced by MBX_MailboxReadInd().
FOE_Data()
PROTO UINT16 FOE_Data (UINT16 MBXMEM * pData, UINT16 Size)
The function is called to write the next part of a file.
Parameters
pData Received file data
Size Length of received file data
Returns
okay, busy or an error code 0 (okay) FOE_MAXBUSY-100 (0%) (busy) FOE_MAXBUSY (100%) (busy) ECAT_FOE_ERRCODE_NOTDEFINED (error) ECAT_FOE_ERRCODE_NOTFOUND (error) ECAT_FOE_ERRCODE_ACCESS (error) ECAT_FOE_ERRCODE_DISKFULL (error) ECAT_FOE_ERRCODE_ILLEGAL (error) ECAT_FOE_ERRCODE_PACKENO (error) ECAT_FOE_ERRCODE_EXISTS (error) ECAT_FOE_ERRCODE_NOUSER (error)
Definition at line 186 of file foeappl.c.
References ECAT_FOE_ERRCODE_NOTDEFINED, FOE_ACKFINISHED, FOE_HEADER_SIZE, MBX_HEADER_SIZE, pAPPL_FoeWriteData, and u16ReceiveMbxSize.
Referenced by FOE_ServiceInd().
FOE_Error()
PROTO void FOE_Error (UINT32 errorCode)
The function is called when a file transfer is aborted from the other station.
Parameters
errorCode error code
Definition at line 296 of file foeappl.c.
References pAPPL_FoeError.
Referenced by FOE_ServiceInd().
FOE_Init()
PROTO void FOE_Init (void)
This function initialize the FoE Interface.
Definition at line 77 of file ecatfoe.c.
References FOE_READY, pFoeSendStored, u16FileAccessState, and u32PacketNo.
Referenced by MBX_StopMailboxHandler().
FOE_Read()
PROTO UINT16 FOE_Read (UINT16 MBXMEM * pName, UINT16 nameSize, UINT16 MBXMEM * pData, UINT32 password)
The function starts a file reading.
Parameters
pName Pointer to the name of the file
nameSize Length of the file name
pData Pointer to the response data
password Password for the file read
Returns
size of the data to be sent, busy or an error code 1..FOE_MAXBUSY-101 (size of data to be sent) FOE_MAXBUSY-100 (0%) (busy) FOE_MAXBUSY (100%) (busy) ECAT_FOE_ERRCODE_NOTDEFINED (error) ECAT_FOE_ERRCODE_NOTFOUND (error) ECAT_FOE_ERRCODE_ACCESS (error) ECAT_FOE_ERRCODE_DISKFULL (error) ECAT_FOE_ERRCODE_ILLEGAL (error) ECAT_FOE_ERRCODE_PACKENO (error) ECAT_FOE_ERRCODE_EXISTS (error) ECAT_FOE_ERRCODE_NOUSER (error)
Definition at line 112 of file foeappl.c.
References ECAT_FOE_ERRCODE_NOTDEFINED, pAPPL_FoeRead, and u16FoeMaxSendBlockSize.
Referenced by FOE_ServiceInd().
FOE_ServiceInd()
PROTO UINT8 FOE_ServiceInd (TFOEMBX MBXMEM * pFoeInd)
This function is called when a FoE (File Access over EtherCAT) service is received from the master.
Parameters
pFoeInd Pointer to the received mailbox data from the master.
Returns
result of the operation (0 (success) or mailbox error code (MBXERR_.... defined in mailbox.h))
Definition at line 98 of file ecatfoe.c.
References bBootMode, ECAT_FOE_ERRCODE_ILLEGAL, ECAT_FOE_ERRCODE_PACKENO, ECAT_FOE_OPCODE_ACK, ECAT_FOE_OPCODE_BUSY, ECAT_FOE_OPCODE_DATA, ECAT_FOE_OPCODE_ERR, ECAT_FOE_OPCODE_RRQ, ECAT_FOE_OPCODE_WRQ, FOE_ACK, FOE_Ack(), FOE_ACKFINISHED, FOE_Busy(), FOE_Data(), FOE_ERROR, FOE_Error(), FOE_FINISHED, FOE_FINISHED_NOACK, FOE_HEADER_SIZE, FOE_MAXBUSY, FOE_MAXBUSY_ZERO, FOE_MAXDATA, FOE_Read(), FOE_READY, FOE_SERVICE, FOE_WAIT_FOR_ACK, FOE_WAIT_FOR_DATA, FOE_WAIT_FOR_LAST_ACK, FOE_WAIT_FOR_LAST_DATA, FOE_Write(), MBX_CopyToSendMailbox(), MBX_HEADER_SIZE, MBX_MailboxSendReq(), MBX_OFFS_COUNTER, MBX_SHIFT_COUNTER, MBXERR_SIZETOOSHORT, pFoeSendStored, SWAPDWORD, SWAPWORD, u16FileAccessState, u16SendMbxSize, u32FileOffset, u32LastFileOffset, u32PacketNo, and u8MbxReadCounter.
Referenced by MailboxServiceInd().
FOE_Write()
PROTO UINT16 FOE_Write (UINT16 MBXMEM * pName, UINT16 nameSize, UINT32 password)
The function starts a file writing.
Parameters
pName Pointer to the name of the file
nameSize Length of the file name
password Password for the file read
Returns
okay, busy or an error code 0 (okay) ECAT_FOE_ERRCODE_NOTDEFINED (error) ECAT_FOE_ERRCODE_NOTFOUND (error) ECAT_FOE_ERRCODE_ACCESS (error) ECAT_FOE_ERRCODE_DISKFULL (error) ECAT_FOE_ERRCODE_ILLEGAL (error) ECAT_FOE_ERRCODE_PACKENO (error) ECAT_FOE_ERRCODE_EXISTS (error) ECAT_FOE_ERRCODE_NOUSER (error)
(no busy response shall be returned by this function. If the slave stack requires some time to handle the incoming data the function FOE_Data() should return busy)
Definition at line 151 of file foeappl.c.
References ECAT_FOE_ERRCODE_NOTDEFINED, and pAPPL_FoeWrite.
Referenced by FOE_ServiceInd().
Variable Documentation
pFoeSendStored
PROTO TMBX MBXMEM* pFoeSendStored
If the mailbox service could not be sent (or stored), the FoE service will be stored in this variable and will be sent automatically from the mailbox handler (FOE_ContinueInd) when the send mailbox will be read the next time from the master
Definition at line 174 of file ecatfoe.h.
Referenced by FOE_ContinueInd(), FOE_Init(), and FOE_ServiceInd().
u16FileAccessState
PROTO UINT16 u16FileAccessState
Stores the actual state of the file transmission sequence.
Definition at line 173 of file ecatfoe.h.
Referenced by FOE_Init(), and FOE_ServiceInd().
u16FoeMaxSendBlockSize
PROTO UINT16 u16FoeMaxSendBlockSize
indicates the maximum size of an FoE fragment (from the slave to the master)
Definition at line 180 of file ecatfoe.h.
Referenced by FOE_Ack(), FOE_Read(), and MBX_StartMailboxHandler().
u32FileOffset
PROTO UINT32 u32FileOffset
Stores the next file offset to be sent.
Definition at line 171 of file ecatfoe.h.
Referenced by FOE_ServiceInd().
u32LastFileOffset
PROTO UINT32 u32LastFileOffset
Stores the actual sent file offset.
Definition at line 172 of file ecatfoe.h.
Referenced by FOE_ServiceInd().
u32PacketNo
PROTO UINT32 u32PacketNo
Stores the actual packet number to be expected.
Definition at line 170 of file ecatfoe.h.
Referenced by FOE_Init(), and FOE_ServiceInd().