AX58400-CM7: EtherCAT application
EtherCAT application
Files
file applInterface.h
Definition of the application interface functions.
file ecatappl.c
Implementation This file contains the Process Data interface.
file ecatappl.h
Macros
#define PROTO extern
#define _ECATAPPL_ 1
#define _APPL_INTERFACE_ 1
#define MAX_CMD_RETIRES 10
#define MEASUREMENT_ACTIVE (((sSyncManOutPar.u16GetCycleTime & 0x1) == 0x1) || ((sSyncManInPar.u16GetCycleTime & 0x1) == 0x1))
#define BOOLEAN(x) UINT16(x):1
Marco to define BOOLEAN object entry.
#define BIT1(x) UINT16(x):1
Marco to define BIT1 object entry.
#define BIT2(x) UINT16(x):2
Marco to define BIT2 object entry.
#define BIT3(x) UINT16(x):3
Marco to define BIT3 object entry.
#define BIT4(x) UINT16(x):4
Marco to define BIT4 object entry.
#define BIT5(x) UINT16(x):5
Marco to define BIT5 object entry.
#define BIT6(x) UINT16(x):6
Marco to define BIT5 object entry.
#define BIT7(x) UINT16(x):7
Marco to define BIT6 object entry.
#define BIT8(x) UINT16(x):8
Marco to define BIT7 object entry.
#define ALIGN0(x)
#define ALIGN1(x) UINT16(x):1;
Marco to define ALIGN1 object entry.
#define ALIGN2(x) UINT16(x):2;
Marco to define ALIGN2 object entry.
#define ALIGN3(x) UINT16(x):3;
Marco to define ALIGN3 object entry.
#define ALIGN4(x) UINT16(x):4;
Marco to define ALIGN4 object entry.
#define ALIGN5(x) UINT16(x):5;
Marco to define ALIGN5 object entry.
#define ALIGN6(x) UINT16(x):6;
Marco to define ALIGN6 object entry.
#define ALIGN7(x) UINT16(x):7;
Marco to define ALIGN7 object entry.
#define ALIGN8(x) UINT16(x):8;
Marco to define ALIGN8 object entry.
#define ALIGN9(x) UINT16(x):9;
Marco to define ALIGN9 object entry.
#define ALIGN10(x) UINT16(x):10;
Marco to define ALIGN10 object entry.
#define ALIGN11(x) UINT16(x):11;
Marco to define ALIGN11 object entry.
#define ALIGN12(x) UINT16(x):12;
Marco to define ALIGN12 object entry.
#define ALIGN13(x) UINT16(x):13;
Marco to define ALIGN13 object entry.
#define ALIGN14(x) UINT16(x):14;
Marco to define ALIGN14 object entry.
#define ALIGN15(x) UINT16(x):15;
Marco to define ALIGN15 object entry.
#define PROTO extern
Functions
PROTO UINT16 MainInit (void)
Initialize the generic slave stack.
PROTO void MainLoop (void)
This function handles the low priority function like EtherCAT state machine.
PROTO void ECAT_StateChange (UINT8 alStatus, UINT16 alStatusCode)
This function shall be called by the application to trigger state transition in case.
UINT32 GetSystemTimeDelay (UINT32 u32StartTime)
indicates if the initialization is finished
void HandleCycleTimeMeasurement (void)
In case of non DC synchronization the cycle time measurement is started and 0x1C3.2 (Cycle time) is updated.
void PDO_InputMapping (void)
This function will copies the inputs from the local memory to the ESC memory.
void PDO_OutputMapping (void)
This function will copies the outputs from the ESC memory to the local memory. This function is only called in case of an SM2 (output process data) event.
void ECAT_CheckTimer (void)
This function shall be called every 1ms.
void PDI_Isr (void)
void Sync0_Isr (void)
void Sync1_Isr (void)
void ECAT_Application (void)
ECAT_Application (prev. SSC versions "COE_Application") this function calculates and the physical process signals and triggers the input mapping.
UINT16 ESC_EepromAccess (UINT32 wordaddress, UINT16 wordsize, UINT16 MBXMEM *pData, UINT8 access)
This function is called to read or write the EEPROM data, for BigEndian.
UINT16 ESC_EepromWriteCRC (void)
This function recalculates the EEPROM CRC and writes the updated value to EEPROM. After writing the ESC Config Area a device restart is required!
PROTO void PDO_ResetOutputs (void)
PROTO void PDO_ReadInputs (void)
PROTO void CalcSMCycleTime (void)
Variables
PROTO UINT16(* pAPPL_FoeRead)(UINT16 MBXMEM *pName, UINT16 nameSize, UINT32 password, UINT16 maxBlockSize, UINT16 *pData)
The function is called when a file read request was received. The Foe fragments shall always have the length of "maxBlockSize" till the last file fragment.
PROTO UINT16(* pAPPL_FoeReadData)(UINT32 offset, UINT16 maxBlockSize, UINT16 *pData)
The function is called to transmit FoE read data 2 .. n (the slave received an acknowledge on a previous accepted file read request). The Foe fragments shall always have the length of "maxBlockSize" till the last file fragment.
PROTO void(* pAPPL_FoeError)(UINT32 errorCode)
The function is called when the master has send an FoE Abort.
PROTO UINT16(* pAPPL_FoeWrite)(UINT16 MBXMEM *pName, UINT16 nameSize, UINT32 password)
This function is called on a received FoE write request.
PROTO UINT16(* pAPPL_FoeWriteData)(UINT16 MBXMEM *pData, UINT16 Size, BOOL bDataFollowing)
This function is called on a FoE Data request.
PROTO void(* pAPPL_MainLoop)()
This function is called by the SSC from the main loop.
UINT32 u32CycleTimeStartValue
UINT32 u32MinCycleTimeStartValue
contains the timer start value to measure the application cycle (used in freerun and SM2 sync)
UINT32 u32SystemTimeReadFailure
timeout counter in ms to measure the process timings (stored in 0x1C3x)
BOOL bMinCycleTimeMeasurementStarted
System time measurement failure (the value is calculated on main init)
UINT32 u32MinCycleTimeValue
Indicates if the min cycle measurement is started.
UINT16 aPdOutputData [(MAX_PD_OUTPUT_SIZE > >1)]
tmp value of the min cycle time during measurement
UINT16 aPdInputData [(MAX_PD_INPUT_SIZE > >1)]
VARVOLATILE UINT8 u8dummy
BOOL bInitFinished = FALSE
PROTO BOOL bEcatWaitForInputUpdate
Wait for input update.
PROTO BOOL bEtherCATRunLed
Current run LED value.
PROTO BOOL bEtherCATErrorLed
Current error LED value.
PROTO BOOL bRunApplication
Indicates if the stack shall be running (if false the Hardware will be released)
Detailed Description
Macro Definition Documentation
_APPL_INTERFACE_
#define _APPL_INTERFACE_ 1
Definition at line 137 of file ecatappl.c.
_ECATAPPL_
#define _ECATAPPL_ 1
Definition at line 128 of file ecatappl.c.
ALIGN0
#define ALIGN0 (x)
Definition at line 68 of file ecatappl.h.
ALIGN1
#define ALIGN1 (x) UINT16(x):1;
Marco to define ALIGN1 object entry.
Definition at line 69 of file ecatappl.h.
ALIGN10
#define ALIGN10 (x) UINT16(x):10;
Marco to define ALIGN10 object entry.
Definition at line 78 of file ecatappl.h.
ALIGN11
#define ALIGN11 (x) UINT16(x):11;
Marco to define ALIGN11 object entry.
Definition at line 79 of file ecatappl.h.
ALIGN12
#define ALIGN12 (x) UINT16(x):12;
Marco to define ALIGN12 object entry.
Definition at line 80 of file ecatappl.h.
ALIGN13
#define ALIGN13 (x) UINT16(x):13;
Marco to define ALIGN13 object entry.
Definition at line 81 of file ecatappl.h.
ALIGN14
#define ALIGN14 (x) UINT16(x):14;
Marco to define ALIGN14 object entry.
Definition at line 82 of file ecatappl.h.
ALIGN15
#define ALIGN15 (x) UINT16(x):15;
Marco to define ALIGN15 object entry.
Definition at line 83 of file ecatappl.h.
ALIGN2
#define ALIGN2 (x) UINT16(x):2;
Marco to define ALIGN2 object entry.
Definition at line 70 of file ecatappl.h.
ALIGN3
#define ALIGN3 (x) UINT16(x):3;
Marco to define ALIGN3 object entry.
Definition at line 71 of file ecatappl.h.
ALIGN4
#define ALIGN4 (x) UINT16(x):4;
Marco to define ALIGN4 object entry.
Definition at line 72 of file ecatappl.h.
ALIGN5
#define ALIGN5 (x) UINT16(x):5;
Marco to define ALIGN5 object entry.
Definition at line 73 of file ecatappl.h.
ALIGN6
#define ALIGN6 (x) UINT16(x):6;
Marco to define ALIGN6 object entry.
Definition at line 74 of file ecatappl.h.
ALIGN7
#define ALIGN7 (x) UINT16(x):7;
Marco to define ALIGN7 object entry.
Definition at line 75 of file ecatappl.h.
ALIGN8
#define ALIGN8 (x) UINT16(x):8;
Marco to define ALIGN8 object entry.
Definition at line 76 of file ecatappl.h.
ALIGN9
#define ALIGN9 (x) UINT16(x):9;
Marco to define ALIGN9 object entry.
Definition at line 77 of file ecatappl.h.
BIT1
#define BIT1 (x) UINT16(x):1
Marco to define BIT1 object entry.
Definition at line 60 of file ecatappl.h.
BIT2
#define BIT2 (x) UINT16(x):2
Marco to define BIT2 object entry.
Definition at line 61 of file ecatappl.h.
BIT3
#define BIT3 (x) UINT16(x):3
Marco to define BIT3 object entry.
Definition at line 62 of file ecatappl.h.
BIT4
#define BIT4 (x) UINT16(x):4
Marco to define BIT4 object entry.
Definition at line 63 of file ecatappl.h.
BIT5
#define BIT5 (x) UINT16(x):5
Marco to define BIT5 object entry.
Definition at line 64 of file ecatappl.h.
BIT6
#define BIT6 (x) UINT16(x):6
Marco to define BIT5 object entry.
Definition at line 65 of file ecatappl.h.
BIT7
#define BIT7 (x) UINT16(x):7
Marco to define BIT6 object entry.
Definition at line 66 of file ecatappl.h.
BIT8
#define BIT8 (x) UINT16(x):8
Marco to define BIT7 object entry.
Definition at line 67 of file ecatappl.h.
BOOLEAN
#define BOOLEAN (x) UINT16(x):1
Marco to define BOOLEAN object entry.
Definition at line 59 of file ecatappl.h.
MAX_CMD_RETIRES
#define MAX_CMD_RETIRES 10
Definition at line 151 of file ecatappl.c.
MEASUREMENT_ACTIVE
#define MEASUREMENT_ACTIVE (((sSyncManOutPar.u16GetCycleTime & 0x1) == 0x1) || ((sSyncManInPar.u16GetCycleTime & 0x1) == 0x1))
Definition at line 163 of file ecatappl.c.
PROTO [1/2]
#define PROTO extern
Definition at line 57 of file applInterface.h.
PROTO [2/2]
#define PROTO extern
Definition at line 89 of file ecatappl.h.
Function Documentation
ECAT_Application()
PROTO void ECAT_Application (void)
ECAT_Application (prev. SSC versions "COE_Application") this function calculates and the physical process signals and triggers the input mapping.
Definition at line 870 of file ecatappl.c.
References APPL_Application(), bMinCycleTimeMeasurementStarted, GetSystemTimeDelay(), HandleCycleTimeMeasurement(), nPdInputSize, nPdOutputSize, sSyncManInPar, sSyncManOutPar, OBJ_STRUCT_PACKED_START::u32MinCycleTime, u32MinCycleTimeStartValue, and u32MinCycleTimeValue.
Referenced by MainLoop().
ECAT_CheckTimer()
PROTO void ECAT_CheckTimer (void)
This function shall be called every 1ms.
If the switch ECAT_TIMER_INT is 0, the watchdog control is implemented without using
interrupts. In this case a local timer register is checked every ECAT_Main cycle
and the function is triggered if 1 ms is elapsed
Definition at line 345 of file ecatappl.c.
References bEcatWaitForAlControlRes, CHECK_DC_OVERRUN_IN_MS, DC_CheckWatchdog(), and EsmTimeoutCounter.
ECAT_StateChange()
PROTO void ECAT_StateChange (UINT8 alStatus, UINT16 alStatusCode)
This function shall be called by the application to trigger state transition in case.
Parameters
alStatus requested AL Status
alStatusCode requested AL Status Code
of an application error or to complete a pending transition.
If the function was called due to an error it shall be again if the error is gone.
NOTE: state requests to a higher state than the current state are not allowed.
This function shall be called by the application to trigger state transition in case.
Parameters
alStatus requested state
alStatusCode value for the AL-Status register
Definition at line 2308 of file ecatslv.c.
References AL_ControlInd(), APPL_StopInputHandler(), APPL_StopMailboxHandler(), APPL_StopOutputHandler(), bApplEsmPending, bEcatInputUpdateRunning, bEcatOutputUpdateRunning, bEcatWaitForAlControlRes, bLocalErrorFlag, bMbxRunning, EsmTimeoutCounter, INIT_2_BOOT, INIT_2_PREOP, MBX_StopMailboxHandler(), nAlStatus, nEcatStateTrans, PREOP_2_SAFEOP, SAFEOP_2_OP, SetALEventMask(), SetALStatus(), STATE_CHANGE, STATE_MASK, StopInputHandler(), StopOutputHandler(), and u16LocalErrorCode.
ESC_EepromAccess()
PROTO UINT16 ESC_EepromAccess (UINT32 wordaddress, UINT16 wordsize, UINT16 MBXMEM * pData, UINT8 access)
This function is called to read or write the EEPROM data, for BigEndian.
Parameters
wordaddress WORD based address in the EEPROM to be read
wordsize size in WORD of EEPROM data to be read
pData buffer for EEPROM to be read or with EEPROM data to be written
access read (ESC_RD) or write (ESC_WR) access
Returns
0 - success, > 0: error code
Controller (switch BIG_ENDIAN_FORMAT set) the data has to be swapped outside
of this function)
Definition at line 959 of file ecatappl.c.
References ALSTATUSCODE_EE_ERROR, ALSTATUSCODE_EE_NOACCESS, ESC_EEPROM_ASSIGN_TO_PDI_MASK, ESC_EEPROM_BUSY_MASK, ESC_EEPROM_CMD_READ_MASK, ESC_EEPROM_CMD_WRITE_MASK, ESC_EEPROM_CONFIG_OFFSET, ESC_EEPROM_ERROR_CMD_ACK, ESC_EEPROM_ERROR_MASK, ESC_EEPROM_LOCKED_BY_PDI_MASK, ESC_EEPROM_SUPPORTED_READBYTES_MASK, and SWAPWORD.
Referenced by ESC_EepromWriteCRC().
ESC_EepromWriteCRC()
PROTO UINT16 ESC_EepromWriteCRC (void)
This function recalculates the EEPROM CRC and writes the updated value to EEPROM. After writing the ESC Config Area a device restart is required!
Returns
success : ALSTATUSCODE_WAITFORCOLDSTART failed : EEPROM ERRROR Code
Definition at line 1140 of file ecatappl.c.
References ALSTATUSCODE_UNSPECIFIEDERROR, ALSTATUSCODE_WAITFORCOLDSTART, and ESC_EepromAccess().
GetSystemTimeDelay()
UINT32 GetSystemTimeDelay (UINT32 u32StartTime)
indicates if the initialization is finished
Calculates the difference between the old and current system time value in ns. NOTE: This function only handles a 32Bit system time values (therefore the maximum delay about 4sec).
<
Parameters
u32StartTime Old system time (0x910:0x913) value
Returns
System time delta in ns
Definition at line 419 of file ecatappl.c.
References ESC_SYSTEMTIME_OFFSET, and u32SystemTimeReadFailure.
Referenced by ECAT_Application(), HandleCycleTimeMeasurement(), PDO_InputMapping(), and PDO_OutputMapping().
HandleCycleTimeMeasurement()
void HandleCycleTimeMeasurement (void)
In case of non DC synchronization the cycle time measurement is started and 0x1C3.2 (Cycle time) is updated.
Definition at line 384 of file ecatappl.c.
References bDcSyncActive, GetSystemTimeDelay(), sSyncManInPar, sSyncManOutPar, and OBJ_STRUCT_PACKED_START::u32CycleTime.
Referenced by ECAT_Application(), and PDO_OutputMapping().
MainInit()
UINT16 MainInit (void)
Initialize the generic slave stack.
This function shall called within a 1ms cycle. Set Run and Error Led depending on the Led state.
Returns
0 if successful or greater 0 in case of an error
This function should be called after the platform including operating system and
ESC is ready to use.
Parameters
pObjectDictionary Pointer to application specific object dictionary. NULL if no specific object are available.
Returns
0 if initialization was successful
This function initialize the EtherCAT Sample Code
Definition at line 663 of file ecatappl.c.
References bMinCycleTimeMeasurementStarted, COE_ObjInit(), ECAT_Init(), ESC_EEPROM_ASSIGN_TO_PDI_MASK, ESC_EEPROM_CONFIG_OFFSET, ESC_SYSTEMTIME_OFFSET, pAPPL_FoeError, pAPPL_FoeRead, pAPPL_FoeReadData, pAPPL_FoeWrite, pAPPL_FoeWriteData, pAPPL_MainLoop, SWAPWORD, u32MinCycleTimeStartValue, and u32SystemTimeReadFailure.
Referenced by main().
MainLoop()
void MainLoop (void)
This function handles the low priority function like EtherCAT state machine.
This function shall be called cyclically from main.
handling, mailbox protocols and if no synchronization is enabled also the
application.
This function shall be called cyclically from the application.
Definition at line 772 of file ecatappl.c.
References bDcSyncActive, bEcatFirstOutputsReceived, bEcatInputUpdateRunning, bEcatOutputUpdateRunning, bEscIntEnabled, CHECK_DC_OVERRUN_IN_MS, CheckIfEcatError(), COE_Main(), COE_SyncTimeStamp(), ECAT_Application(), ECAT_Main(), nPdOutputSize, pAPPL_MainLoop, PDO_InputMapping(), PDO_OutputMapping(), PROCESS_INPUT_EVENT, PROCESS_OUTPUT_EVENT, and SWAPWORD.
Referenced by main().
PDI_Isr()
PROTO void PDI_Isr (void)
Definition at line 458 of file ecatappl.c.
PDO_InputMapping()
PROTO void PDO_InputMapping (void)
This function will copies the inputs from the local memory to the ESC memory.
Definition at line 216 of file ecatappl.c.
References APPL_InputMapping(), bMinCycleTimeMeasurementStarted, GetSystemTimeDelay(), nEscAddrInputData, nPdInputSize, sSyncManInPar, sSyncManOutPar, SWAPWORD, OBJ_STRUCT_PACKED_START::u32CalcAndCopyTime, OBJ_STRUCT_PACKED_START::u32MinCycleTime, and u32MinCycleTimeValue.
Referenced by MainLoop(), and StartInputHandler().
PDO_OutputMapping()
void PDO_OutputMapping (void)
This function will copies the outputs from the ESC memory to the local memory. This function is only called in case of an SM2 (output process data) event.
Definition at line 291 of file ecatappl.c.
References aPdOutputData, APPL_OutputMapping(), bMinCycleTimeMeasurementStarted, GetSystemTimeDelay(), HandleCycleTimeMeasurement(), nEscAddrOutputData, nPdOutputSize, sSyncManOutPar, OBJ_STRUCT_PACKED_START::u32CalcAndCopyTime, u32MinCycleTimeStartValue, and u32MinCycleTimeValue.
Referenced by MainLoop().
Sync0_Isr()
PROTO void Sync0_Isr (void)
Definition at line 545 of file ecatappl.c.
Sync1_Isr()
PROTO void Sync1_Isr (void)
Definition at line 631 of file ecatappl.c.
Variable Documentation
aPdInputData
UINT16 aPdInputData[(MAX_PD_INPUT_SIZE > >1)]
Definition at line 190 of file ecatappl.c.
aPdOutputData
UINT16 aPdOutputData[(MAX_PD_OUTPUT_SIZE > >1)]
tmp value of the min cycle time during measurement
<
Definition at line 189 of file ecatappl.c.
Referenced by PDO_OutputMapping().
bEcatWaitForInputUpdate
PROTO BOOL bEcatWaitForInputUpdate
Wait for input update.
Definition at line 101 of file ecatappl.h.
bEtherCATErrorLed
PROTO BOOL bEtherCATErrorLed
Current error LED value.
Definition at line 103 of file ecatappl.h.
bEtherCATRunLed
PROTO BOOL bEtherCATRunLed
Current run LED value.
Definition at line 102 of file ecatappl.h.
bInitFinished
BOOL bInitFinished = FALSE
Definition at line 195 of file ecatappl.c.
bMinCycleTimeMeasurementStarted
BOOL bMinCycleTimeMeasurementStarted
System time measurement failure (the value is calculated on main init)
<
Definition at line 180 of file ecatappl.c.
Referenced by ECAT_Application(), MainInit(), PDO_InputMapping(), and PDO_OutputMapping().
bRunApplication
PROTO BOOL bRunApplication
Indicates if the stack shall be running (if false the Hardware will be released)
Definition at line 104 of file ecatappl.h.
pAPPL_FoeError
PROTO void(* pAPPL_FoeError) (UINT32 errorCode) (UINT32 errorCode)
The function is called when the master has send an FoE Abort.
Parameters
errorCode Error code send by the EtherCAT master
Definition at line 142 of file applInterface.h.
Referenced by FOE_Error(), and MainInit().
pAPPL_FoeRead
PROTO UINT16(* pAPPL_FoeRead) (UINT16 MBXMEM *pName, UINT16 nameSize, UINT32 password, UINT16 maxBlockSize, UINT16 *pData) (UINT16 MBXMEM * pName, UINT16 nameSize, UINT32 password, UINT16 maxBlockSize, UINT16 * pData)
The function is called when a file read request was received. The Foe fragments shall always have the length of "maxBlockSize" till the last file fragment.
Parameters
pName Pointer to the name of the file (the pointer is null if the function is called due to a previous busy state)
nameSize Length of the file name (the value is 0 if the function is called due to a previous busy state)
password Password for the file read (the value is 0 if the function is called due to a previous busy state)
maxBlockSize Maximum size of a data block (copied to pData)
pData Destination pointer for the first FoE fragment
Returns
block size: < FOE_MAXBUSY-101 (0x7F95) busy: FOE_MAXBUSY-100 (0%) (0x7FFA - 0x64) ... FOE_MAXBUSY (100%) (0x7FFA) error: ECAT_FOE_ERRCODE_NOTDEFINED (0x8000) ECAT_FOE_ERRCODE_NOTFOUND (0x8001) ECAT_FOE_ERRCODE_ACCESS (0x8002) ECAT_FOE_ERRCODE_DISKFULL (0x8003) ECAT_FOE_ERRCODE_ILLEGAL (0x8004) ECAT_FOE_ERRCODE_EXISTS (0x8006) ECAT_FOE_ERRCODE_NOUSER (0x8007)
In case that the file size is a multiple of "maxBlockSize" 0 shall be returned after the last fragment.
Definition at line 101 of file applInterface.h.
Referenced by FOE_Read(), and MainInit().
pAPPL_FoeReadData
PROTO UINT16(* pAPPL_FoeReadData) (UINT32 offset, UINT16 maxBlockSize, UINT16 *pData) (UINT32 offset, UINT16 maxBlockSize, UINT16 * pData)
The function is called to transmit FoE read data 2 .. n (the slave received an acknowledge on a previous accepted file read request). The Foe fragments shall always have the length of "maxBlockSize" till the last file fragment.
Parameters
offset File offset which shall be transmitted next
maxBlockSize Maximum size of a data block (copied to pData)
pData Destination pointer for the next foe fragment
Returns
block size: < FOE_MAXBUSY-101 (0x7F95) busy: FOE_MAXBUSY-100 (0%) (0x7FFA - 0x64) ... FOE_MAXBUSY (100%) (0x7FFA) error: ECAT_FOE_ERRCODE_NOTDEFINED (0x8000) ECAT_FOE_ERRCODE_NOTFOUND (0x8001) ECAT_FOE_ERRCODE_ACCESS (0x8002) ECAT_FOE_ERRCODE_DISKFULL (0x8003) ECAT_FOE_ERRCODE_ILLEGAL (0x8004) ECAT_FOE_ERRCODE_EXISTS (0x8006) ECAT_FOE_ERRCODE_NOUSER (0x8007)
In case that the file size is a multiple of "maxBlockSize" 0 shall be returned after the last fragment.
Definition at line 131 of file applInterface.h.
Referenced by FOE_Ack(), and MainInit().
pAPPL_FoeWrite
PROTO UINT16(* pAPPL_FoeWrite) (UINT16 MBXMEM *pName, UINT16 nameSize, UINT32 password) (UINT16 MBXMEM * pName, UINT16 nameSize, UINT32 password)
This function is called on a received FoE write request.
Parameters
pName Pointer to the name of the file
nameSize Length of the file name
password Password for the file read
Returns
okay, or an error code 0 (okay) ECAT_FOE_ERRCODE_NOTDEFINED (0x8000) ECAT_FOE_ERRCODE_NOTFOUND (0x8001) ECAT_FOE_ERRCODE_ACCESS (0x8002) ECAT_FOE_ERRCODE_DISKFULL (0x8003) ECAT_FOE_ERRCODE_ILLEGAL (0x8004) ECAT_FOE_ERRCODE_EXISTS (0x8006) ECAT_FOE_ERRCODE_NOUSER (0x8007)
(no busy response shall be returned by this function. If the slave requires some time to handle the incoming data the function pAPPL_FoeData() shall return a busy)
Definition at line 167 of file applInterface.h.
Referenced by FOE_Write(), and MainInit().
pAPPL_FoeWriteData
PROTO UINT16(* pAPPL_FoeWriteData) (UINT16 MBXMEM *pData, UINT16 Size, BOOL bDataFollowing) (UINT16 MBXMEM * pData, UINT16 Size, BOOL bDataFollowing)
This function is called on a FoE Data request.
Parameters
pData Received file data
Size Length of received file data
bDataFollowing TRUE if more FoE Data requests are following
Returns
okay, busy or an error code 0 (okay) FOE_MAXBUSY-100 (0%) (0x7FFa - 100) FOE_MAXBUSY (100%) (0x7FFA) ECAT_FOE_ERRCODE_NOTDEFINED (0x8000) ECAT_FOE_ERRCODE_ACCESS (0x8002) ECAT_FOE_ERRCODE_DISKFULL (0x8003) ECAT_FOE_ERRCODE_ILLEGAL (0x8004) ECAT_FOE_ERRCODE_NOUSER (0x8007)
Definition at line 189 of file applInterface.h.
Referenced by FOE_Data(), and MainInit().
pAPPL_MainLoop
PROTO void(* pAPPL_MainLoop) () ()
This function is called by the SSC from the main loop.
Definition at line 197 of file applInterface.h.
Referenced by __attribute__(), MainInit(), and MainLoop().
u32CycleTimeStartValue
UINT32 u32CycleTimeStartValue
Definition at line 174 of file ecatappl.c.
u32MinCycleTimeStartValue
UINT32 u32MinCycleTimeStartValue
contains the timer start value to measure the application cycle (used in freerun and SM2 sync)
<
Definition at line 176 of file ecatappl.c.
Referenced by ECAT_Application(), MainInit(), and PDO_OutputMapping().
u32MinCycleTimeValue
UINT32 u32MinCycleTimeValue
Indicates if the min cycle measurement is started.
<
Definition at line 182 of file ecatappl.c.
Referenced by ECAT_Application(), PDO_InputMapping(), and PDO_OutputMapping().
u32SystemTimeReadFailure
UINT32 u32SystemTimeReadFailure
timeout counter in ms to measure the process timings (stored in 0x1C3x)
<
Definition at line 178 of file ecatappl.c.
Referenced by GetSystemTimeDelay(), and MainInit().
u8dummy
VARVOLATILE UINT8 u8dummy extern
Definition at line 225 of file ecatslv.c.