AX58400-CM7: AX58400_MotorControl
AX58400_MotorControl
Modules
Process Data Objects
CiA402 Axis Objects
0x1600 | RxPdoMappingCspCsv
Object 0x1600 (RxPdoMappingCspCsv) definition.
0x1601 | RxPdoMappingCsp
Object 0x1601 (RxPdoMappingCsp) definition.
0x1602 | RxPdoMappingCsv
Object 0x1602 (RxPdoMappingCsv) definition.
0x1A00 | TxPdoMappingCspCsv
Object 0x1A00 (TxPdoMappingCspCsv) definition.
0x1A01 | TxPdoMappingCsp
Object 0x1A01 (TxPdoMappingCsp) definition.
0x1A02 | TxPdoMappingCsv
Object 0x1A02 (TxPdoMappingCsv) definition.
0x1C12 | SM2 assignment
Object 0x1C12 (SM2 assignment) definition.
0x1C13 | SM3 assignment
Object 0x1C13 (SM3 assignment) definition.
0x603F | Error Code
Object 0x603F (Error Code) definition.
0x6040 | Controlword
Object 0x6040 (Controlword) definition.
0x6041 | Statusword
Object 0x6041 (Statusword) definition.
0x604F | VL Ramp Function Time
Object 0x604F (VL Ramp Function Time) definition.
0x605A | Quick stop option code
Object 0x605A (Quick stop option code) definition.
0x605B | Shutdown option code
Object 0x605B (Shutdown option code) definition.
0x605C | Disable operation option code
Object 0x605C (Disable operation option code) definition.
0x605E | Fault reaction option code
Object 0x605E (Fault reaction option code) definition.
0x6060 | Modes of operation
Object 0x6060 (Modes of operation) definition.
0x6061 | Modes of operation display
Object 0x6061 (Modes of operation display) definition.
0x6064 | Position actual value
Object 0x6064 (Position actual value) definition.
0x606C | Velocity actual value
Object 0x606C (Velocity actual value) definition.
0x6077 | Torque actual value
Object 0x6077 (Torque actual value) definition.
0x607A | Target position
Object 0x607A (Target position) definition.
0x607C | Home offset
Object 0x607C (Home offset) definition.
0x607D | Software position limit
Object 0x607D (Software position limit) definition.
0x6085 | Quick stop deceleration
Object 0x6085 (Quick stop deceleration) definition.
0x6098 | Homing method
Object 0x6098 (Homing method) definition.
0x6099 | Homing speed
Object 0x6099 (Homing speed) definition.
0x609A | Homing acceleration
Object 0x609A (Homing acceleration) definition.
0x60C2 | Interpolation time period
Object 0x60C2 (Interpolation time period) definition.
0x60E3 | Supported homing methods
Object 0x60E3 (Supported homing methods) definition.
0x60FD | Digital Inputs
Object 0x60FD (Digital Inputs) definition.
0x60FF | Target velocity
Object 0x60FF (Target velocity) definition.
0x6502 | Supported drive modes
Object 0x6502 (Supported drive modes) definition.
0xF000 | Modular device profile
Object 0xF000 (Modular device profile) definition.
0xF010 | Module profile list
Object 0xF010 (Module profile list) definition.
0xF030 | Configured module Ident list
Object 0xF030 (Configured module Ident list) definition.
0xF050 | Module detected list
Object 0xF050 (Module detected list) definition.
Files
file AX58400_MotorControl.c
Implementation.
file AX58400_MotorControl.h
AX58400_MotorControl function prototypes and defines.
Macros
#define _AX58400__MOTOR_CONTROL_ 1
#define CONTROLWORD_COMMAND_SHUTDOWN_MASK 0x0087
Shutdown command mask.
#define CONTROLWORD_COMMAND_SWITCHON_MASK 0x00C7
Switch on command mask.
#define CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION_MASK 0x008F
Switch on & Enable command mask.
#define CONTROLWORD_COMMAND_DISABLEVOLTAGE_MASK 0x0082
Disable voltage command mask.
#define CONTROLWORD_COMMAND_QUICKSTOP_MASK 0x0086
Quickstop command mask.
#define CONTROLWORD_COMMAND_DISABLEOPERATION_MASK 0x008F
Disable operation command mask.
#define CONTROLWORD_COMMAND_ENABLEOPERATION_MASK 0x008F
Enable operation command mask.
#define CONTROLWORD_COMMAND_FAULTRESET_MASK 0x0080
Fault reset command mask.
#define CONTROLWORD_COMMAND_SHUTDOWN 0x0006
Shutdown command.
#define CONTROLWORD_COMMAND_SWITCHON 0x0007
Switch on command.
#define CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION 0x000F
Switch on & Enable command.
#define CONTROLWORD_COMMAND_DISABLEVOLTAGE 0x0000
Disable voltage command.
#define CONTROLWORD_COMMAND_QUICKSTOP 0x0002
Quickstop command.
#define CONTROLWORD_COMMAND_DISABLEOPERATION 0x0007
Disable operation command.
#define CONTROLWORD_COMMAND_ENABLEOPERATION 0x000F
Enable operation command.
#define CONTROLWORD_COMMAND_FAULTRESET 0x0080
Fault reset command.
#define STATUSWORD_STATE_MASK 0x006F
State mask.
#define STATUSWORD_VOLTAGE_ENABLED 0x0010
Indicate high voltage enabled.
#define STATUSWORD_WARNING 0x0080
Warning active.
#define STATUSWORD_MANUFACTORSPECIFIC 0x0100
Manufacturer specific.
#define STATUSWORD_INTERNAL_LIMIT 0x0800
Internal limit.
#define STATUSWORD_REMOTE 0x0200
Set if the control word is processed.
#define STATUSWORD_TARGET_REACHED 0x0400
Target reached.
#define STATUSWORD_INTERNALLIMITACTIVE 0x0800
Internal limit active.
#define STATUSWORD_DRIVE_FOLLOWS_COMMAND 0x1000
Drive follows command (used in cyclic synchronous modes)
#define STATUSWORD_STATE_NOTREADYTOSWITCHON 0x0000
Not ready to switch on.
#define STATUSWORD_STATE_SWITCHEDONDISABLED 0x0040
Switched on but disabled.
#define STATUSWORD_STATE_READYTOSWITCHON 0x0021
Ready to switch on.
#define STATUSWORD_STATE_SWITCHEDON 0x0023
Switched on.
#define STATUSWORD_STATE_OPERATIONENABLED 0x0027
Operation enabled.
#define STATUSWORD_STATE_QUICKSTOPACTIVE 0x0007
Quickstop active.
#define STATUSWORD_STATE_FAULTREACTIONACTIVE 0x000F
Fault reaction active.
#define STATUSWORD_STATE_FAULT 0x0008
Fault state.
#define STATE_NOT_READY_TO_SWITCH_ON 0x0001
Not ready to switch on (optional)
#define STATE_SWITCH_ON_DISABLED 0x0002
Switch on but disabled (optional)
#define STATE_READY_TO_SWITCH_ON 0x0004
Ready to switch on (mandatory)
#define STATE_SWITCHED_ON 0x0008
Switch on (mandatory)
#define STATE_OPERATION_ENABLED 0x0010
Operation enabled (mandatory)
#define STATE_QUICK_STOP_ACTIVE 0x0020
Quick stop active (optional)
#define STATE_FAULT_REACTION_ACTIVE 0x0040
Fault reaction active (mandatory)
#define STATE_FAULT 0x0080
Fault state (mandatory)
#define NO_MODE 0
No mode.
#define PROFILE_POSITION_MODE 1
Position Profile mode.
#define VELOCITY_MODE 2
Velocity mode.
#define PROFILE_VELOCITY_MOCE 3
Velocity Profile mode.
#define PROFILE_TORQUE_MODE 4
Torque Profile mode.
#define HOMING_MODE 6
Homing mode.
#define INTERPOLATION_POSITION_MODE 7
Interpolation Position mode.
#define CYCLIC_SYNC_POSITION_MODE 8
Cyclic Synchronous Position mode.
#define CYCLIC_SYNC_VELOCITY_MODE 9
Cyclic Synchronous Velocity mode.
#define CYCLIC_SYNC_TORQUE_MODE 10
Cyclic Synchronous Torque mode.
#define ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_INPUT 0x2110
Short circuit/earth leakage (input)
#define ERROR_EARTH_LEAKAGE_INPUT 0x2120
Earth leakage (input)
#define ERROR_EARTH_LEAKAGE_PHASE_L1 0x2121
Earth leakage phase L1.
#define ERROR_EARTH_LEAKAGE_PHASE_L2 0x2122
Earth leakage phase L2.
#define ERROR_EARTH_LEAKAGE_PHASE_L3 0x2123
Earth leakage phase L3.
#define ERROR_SHORT_CIRCUIT_INPUT 0x2130
Short circuit (input)
#define ERROR_SHORT_CIRCUIT_PHASES_L1_L2 0x2131
Short circuit phases L1-L2.
#define ERROR_SHORT_CIRCUIT_PHASES_L2_L3 0x2132
Short circuit phases L2-L3.
#define ERROR_SHORT_CIRCUIT_PHASES_L3_L1 0x2133
Short circuit phases L3-L1.
#define ERROR_INTERNAL_CURRENT_NO1 0x2211
Internal current no 1.
#define ERROR_INTERNAL_CURRENT_NO2 0x2212
Internal current no 2.
#define ERROR_OVER_CURRENT_IN_RAMP_FUNCTION 0x2213
Over-current in ramp function.
#define ERROR_OVER_CURRENT_IN_THE_SEQUENCE 0x2214
Over-current in the sequence.
#define ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL 0x2220
Continuous over current (device internal)
#define ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL_NO1 0x2221
Continuous over current no 1.
#define ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL_NO2 0x2222
Continuous over current no 2.
#define ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_DEVICE_INTERNAL 0x2230
Short circuit/earth leakage (device internal)
#define ERROR_EARTH_LEAKAGE_DEVICE_INTERNAL 0x2240
Earth leakage (device internal)
#define ERROR_SHORT_CIRCUIT_DEVICE_INTERNAL 0x2250
Short circuit (device internal)
#define ERROR_CONTINUOUS_OVER_CURRENT 0x2310
Continuous over current.
#define ERROR_CONTINUOUS_OVER_CURRENT_NO1 0x2311
Continuous over current no 1.
#define ERROR_CONTINUOUS_OVER_CURRENT_NO2 0x2312
Continuous over current no 2.
#define ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_MOTOR_SIDE 0x2320
Short circuit/earth leakage (motor-side)
#define ERROR_EARTH_LEAKAGE_MOTOR_SIDE 0x2330
Earth leakage (motor-side)
#define ERROR_EARTH_LEAKAGE_PHASE_U 0x2331
Earth leakage phase U.
#define ERROR_EARTH_LEAKAGE_PHASE_V 0x2332
Earth leakage phase V.
#define ERROR_EARTH_LEAKAGE_PHASE_W 0x2333
Earth leakage phase W.
#define ERROR_SHORT_CIRCUIT_MOTOR_SIDE 0x2340
Short circuit (motor-side)
#define ERROR_SHORT_CIRCUIT_PHASES_U_V 0x2341
Short circuit phases U-V.
#define ERROR_EARTH_LEAKAGE_PHASE_V_W 0x2342
Earth leakage phase V-W.
#define ERROR_EARTH_LEAKAGE_PHASE_W_U 0x2343
Earth leakage phase W-U.
#define ERROR_LOAD_LEVEL_FAULT_I2T_THERMAL_STATE 0x2350
Load level fault (I2t, thermal state)
#define ERROR_LOAD_LEVEL_WARNING_I2T_THERMAL_STATE 0x2351
Load level warning (I2t, thermal state)
#define ERROR_MAINS_OVER_VOLTAGE 0x3110
Mains over-voltage.
#define ERROR_MAINS_OVER_VOLTAGE_PHASE_L1 0x3111
Mains over-voltage phase L1.
#define ERROR_MAINS_OVER_VOLTAGE_PHASE_L2 0x3112
Mains over-voltage phase L2.
#define ERROR_MAINS_OVER_VOLTAGE_PHASE_L3 0x3113
Mains over-voltage phase L3.
#define ERROR_MAINS_UNDER_VOLTAGE 0x3120
Mains under-voltage.
#define ERROR_MAINS_UNDER_VOLTAGE_PHASE_L1 0x3121
Mains under-voltage phase L1.
#define ERROR_MAINS_UNDER_VOLTAGE_PHASE_L2 0x3122
Mains under-voltage phase L2.
#define ERROR_MAINS_UNDER_VOLTAGE_PHASE_L3 0x3123
Mains under-voltage phase L3.
#define ERROR_PHASE_FAILURE 0x3130
Phase failure.
#define ERROR_PHASE_FAILURE_L1 0x3131
Phase failure L1.
#define ERROR_PHASE_FAILURE_L2 0x3132
Phase failure L2.
#define ERROR_PHASE_FAILURE_L3 0x3133
Phase failure L3.
#define ERROR_PHASE_SEQUENCE 0x3134
Phase sequence.
#define ERROR_MAINS_FREQUENCY 0x3140
Mains frequency.
#define ERROR_MAINS_FREQUENCY_TOO_GREAT 0x3141
Mains frequency too great.
#define ERROR_MAINS_FREQUENCY_TOO_SMALL 0x3142
Mains frequency too small.
#define ERROR_DC_LINK_OVER_VOLTAGE 0x3210
DC link over-voltage.
#define ERROR_OVER_VOLTAGE_NO_1 0x3211
Over-voltage no 1.
#define ERROR_OVER_VOLTAGE_NO_2 0x3212
Over voltage no 2.
#define ERROR_DC_LINK_UNDER_VOLTAGE 0x3220
DC link under-voltage.
#define ERROR_UNDER_VOLTAGE_NO_1 0x3221
Under-voltage no 1.
#define ERROR_UNDER_VOLTAGE_NO_2 0x3222
Under-voltage no 2.
#define ERROR_LOAD_ERROR 0x3230
Load error.
#define ERROR_OUTPUT_OVER_VOLTAGE 0x3310
Output over-voltage.
#define ERROR_OUTPUT_OVER_VOLTAGE_PHASE_U 0x3311
Output over-voltage phase U.
#define ERROR_OUTPUT_OVER_VOLTAGE_PHASE_V 0x3312
Output over-voltage phase V.
#define ERROR_OUTPUT_OVER_VOLTAGE_PHASE_W 0x3313
Output over-voltage phase W.
#define ERROR_ARMATURE_CIRCUIT 0x3320
Armature circuit.
#define ERROR_ARMATURE_CIRCUIT_INTERRUPTED 0x3321
Armature circuit interrupted.
#define ERROR_FIELD_CIRCUIT 0x3330
Field circuit error.
#define ERROR_FIELD_CIRCUIT_INTERRUPTED 0x3331
Field circuit interrupted.
#define ERROR_EXCESS_AMBIENT_TEMPERATURE 0x4110
Excess ambient temperature.
#define ERROR_TOO_LOW_AMBIENT_TEMPERATURE 0x4120
Too low ambient temperature.
#define ERROR_TEMPERATURE_SUPPLY_AIR 0x4130
Temperature supply air.
#define ERROR_TEMPERATURE_AIR_OUTLET 0x4140
Temperature air outlet.
#define ERROR_EXCESS_TEMPERATURE_DEVICE 0x4210
Excess temperature device.
#define ERROR_TOO_LOW_TEMPERATURE_DEVICE 0x4220
Too low temperature device.
#define ERROR_TEMPERATURE_DRIVE 0x4300
Temperature drive error.
#define ERROR_EXCESS_TEMPERATURE_DRIVE 0x4310
Excess temperature drive error.
#define ERROR_TOO_LOW_TEMPERATURE_DRIVE 0x4320
Too low temperature drive error.
#define ERROR_TEMPERATURE_SUPPLY 0x4400
Temperature supply error.
#define ERROR_EXCESS_TEMPERATURE_SUPPLY 0x4410
Excess temperature supply.
#define ERROR_TOO_LOW_TEMPERATURE_SUPPLY 0x4420
Too low temperature supply.
#define ERROR_SUPPLY_ERROR 0x5100
Supply error.
#define ERROR_SUPPLY_LOW_VOLTAGE 0x5110
Supply low voltage.
#define ERROR_U1_SUPPLY_15V 0x5111
U1 = supply +15V/-15V.
#define ERROR_U2_SUPPLY_24_V 0x5112
U2 = supply +24 V.
#define ERROR_U3_SUPPLY_5_V 0x5113
U3 = supply +5 V.
#define ERROR_U4_MANUFACTURER_SPECIFIC 0x5114
U4 = manufacturer-specific error.
#define ERROR_U5_MANUFACTURER_SPECIFIC 0x5115
U5 = manufacturer-specific error.
#define ERROR_U6_MANUFACTURER_SPECIFIC 0x5116
U6 = manufacturer-specific error.
#define ERROR_U7_MANUFACTURER_SPECIFIC 0x5117
U7 = manufacturer-specific error.
#define ERROR_U8_MANUFACTURER_SPECIFIC 0x5118
U8 = manufacturer-specific error.
#define ERROR_U9_MANUFACTURER_SPECIFIC 0x5119
U9 = manufacturer-specific error.
#define ERROR_SUPPLY_INTERMEDIATE_CIRCUIT 0x5120
Supply intermediate circuit.
#define ERROR_CONTROL_MEASUREMENT_CIRCUIT 0x5210
Measurement circuit.
#define ERROR_CONTROL_COMPUTING_CIRCUIT 0x5220
Computing circuit.
#define ERROR_OPERATING_UNIT 0x5300
Operating unit error.
#define ERROR_POWER_SECTION 0x5400
Power section error.
#define ERROR_OUTPUT_STAGES 0x5410
Output stages error.
#define ERROR_CHOPPER 0x5420
Chopper error.
#define ERROR_INPUT_STAGES 0x5430
Input stages error.
#define ERROR_CONTACTS_ERROR 0x5440
Contacts error.
#define ERROR_CONTACT_1_MANUFACTURER_SPECIFIC 0x5441
Contact 1 = manufacturer-specific error.
#define ERROR_CONTACT_2_MANUFACTURER_SPECIFIC 0x5442
Contact 2 = manufacturer-specific error.
#define ERROR_CONTACT_3_MANUFACTURER_SPECIFIC 0x5443
Contact 3 = manufacturer-specific error.
#define ERROR_CONTACT_4_MANUFACTURER_SPECIFIC 0x5444
Contact 4 = manufacturer-specific error.
#define ERROR_CONTACT_5_MANUFACTURER_SPECIFIC 0x5445
Contact 5 = manufacturer-specific error.
#define ERROR_FUSES_ERROR 0x5450
Fuses error.
#define ERROR_S1_L1 0x5451
S1 = l1 error.
#define ERROR_S2_L2 0x5452
S2 = l2 error.
#define ERROR_S3_L3 0x5453
S3 = l3 error.
#define ERROR_S4_MANUFACTURER_SPECIFIC 0x5454
S4 = manufacturer-specific error.
#define ERROR_S5_MANUFACTURER_SPECIFIC 0x5455
S5 = manufacturer-specific error.
#define ERROR_S6_MANUFACTURER_SPECIFIC 0x5456
S6 = manufacturer-specific error.
#define ERROR_S7_MANUFACTURER_SPECIFIC 0x5457
S7 = manufacturer-specific error.
#define ERROR_S8_MANUFACTURER_SPECIFIC 0x5458
S8 = manufacturer-specific error.
#define ERROR_S9_MANUFACTURER_SPECIFIC 0x5459
S9 = manufacturer-specific error.
#define ERROR_HARDWARE_MEMORY 0x5500
Hardware memory error.
#define ERROR_RAM 0x5510
RAM error.
#define ERROR_ROM_EPROM 0x5520
ROM/EPROM error.
#define ERROR_EEPROM 0x5530
EEPROM error.
#define ERROR_SOFTWARE_RESET_WATCHDOG 0x6010
Software reset (watchdog)
#define ERROR_LOSS_OF_PARAMETERS 0x6310
Loss of parameters.
#define ERROR_PARAMETER_ERROR 0x6320
Parameter error.
#define ERROR_POWER_ERROR 0x7100
Power error.
#define ERROR_BRAKE_CHOPPER 0x7110
Brake chopper.
#define ERROR_FAILURE_BRAKE_CHOPPER 0x7111
Failure brake chopper.
#define ERROR_OVER_CURRENT_BRAKE_CHOPPER 0x7112
Over current brake chopper.
#define ERROR_PROTECTIVE_CIRCUIT_BRAKE_CHOPPER 0x7113
Protective circuit brake chopper error.
#define ERROR_MOTOR_ERROR 0x7120
Motor error.
#define ERROR_MOTOR_BLOCKED 0x7121
Motor blocked error.
#define ERROR_MOTOR_ERROR_OR_COMMUTATION_MALFUNC 0x7122
Motor error or commutation malfunc.
#define ERROR_MOTOR_TILTED 0x7123
Motor tilted.
#define ERROR_MEASUREMENT_CIRCUIT 0x7200
Measurement circuit.
#define ERROR_SENSOR_ERROR 0x7300
Sensor error.
#define ERROR_TACHO_FAULT 0x7301
Tacho fault.
#define ERROR_TACHO_WRONG_POLARITY 0x7302
Tacho wrong polarity.
#define ERROR_RESOLVER_1_FAULT 0x7303
Resolver 1 fault.
#define ERROR_RESOLVER_2_FAULT 0x7304
Resolver 2 fault.
#define ERROR_INCREMENTAL_SENSOR_1_FAULT 0x7305
Incremental sensor 1 fault.
#define ERROR_INCREMENTAL_SENSOR_2_FAULT 0x7306
Incremental sensor 2 fault.
#define ERROR_INCREMENTAL_SENSOR_3_FAULT 0x7307
Incremental sensor 3 fault.
#define ERROR_SPEED 0x7310
Speed error.
#define ERROR_POSITION 0x7320
Position error.
#define ERROR_COMPUTATION_CIRCUIT 0x7400
Computation circuit.
#define ERROR_COMMUNICATION 0x7500
Communication error.
#define ERROR_SERIAL_INTERFACE_NO_1 0x7510
Serial interface no 1 error.
#define ERROR_SERIAL_INTERFACE_NO_2 0x7520
Serial interface no 2 error.
#define ERROR_DATA_STORAGE_EXTERNAL 0x7600
Data storage (external) error.
#define ERROR_TORQUE_CONTROL 0x8300
Torque control error.
#define ERROR_EXCESS_TORQUE 0x8311
Excess torque error.
#define ERROR_DIFFICULT_START_UP 0x8312
Difficult start up error.
#define ERROR_STANDSTILL_TORQUE 0x8313
Standstill torque error.
#define ERROR_INSUFFICIENT_TORQUE 0x8321
Insufficient torque error.
#define ERROR_TORQUE_FAULT 0x8331
Torque fault.
#define ERROR_VELOCITY_SPEED_CONTROLLER 0x8400
Velocity speed controller.
#define ERROR_POSITION_CONTROLLER 0x8500
Position controller.
#define ERROR_POSITIONING_CONTROLLER 0x8600
Positioning controller.
#define ERROR_FOLLOWING_ERROR 0x8611
Following error.
#define ERROR_REFERENCE_LIMIT 0x8612
Reference limit.
#define ERROR_SYNC_CONTROLLER 0x8700
Sync controller.
#define ERROR_WINDING_CONTROLLER 0x8800
Winding controller.
#define ERROR_PROCESS_DATA_MONITORING 0x8900
Process data monitoring.
#define ERROR_DECELERATION 0xF001
Deceleration error.
#define ERROR_SUB_SYNCHRONOUS_RUN 0xF002
Sub-synchronous run error.
#define ERROR_STROKE_OPERATION 0xF003
Stroke operation error.
#define ERROR_EMERGENCY_OCCUR 0xFF00
Emergency occur.
#define ERROR_SOFTWARE 0xFF01
#define ERROR_UNKNOWN 0xFFFF
#define DISABLE_DRIVE 0
Disable drive (options: 0x605B; 0x605C; 0x605E)
#define SLOW_DOWN_RAMP 1
Slow down ramp (options: 0x605B; 0x605C; 0x605E)
#define QUICKSTOP_RAMP 2
Quick stop ramp (options: 0x605E)
#define STOP_ON_CURRENT_LIMIT 3
Stop on current limit (options: 0x605E)
#define STOP_ON_VOLTAGE_LIMIT 4
Stop on voltage limit (options: 0x605E)
#define SLOWDOWN_RAMP_NO_TRANSIT 5
Slow down on slow down ramp and stay in Quick Stop Active.
#define QUICKSTOP_RAMP_NO_TRANSIT 6
Slow down on quick stop ramp and stay in Quick Stop Active.
#define CURRENT_LIMIT_NO_TRANSIT 7
Slow down on current limit and stay in Quick Stop Active.
#define VOLTAGE_LIMIT_NO_TRANSIT 8
Slow down on voltage limit and stay in Quick Stop Active.
#define DEFULT_VL_RAMP_FUNC_TIME 500 /* ms */
#define MAX_AXES 1
Number of supported axes.
#define CSV_CSP_MODULE_ID 0x00119800
Module Id for cyclic synchronous position/velocity mode (dynamic switching supported)
#define CSP_MODULE_ID 0x00219800
Module Id for cyclic synchronous position mode.
#define CSV_MODULE_ID 0x00319800
Module Id for cyclic synchronous velocity mode.
#define ESC_RD 1
#define ESC_WR 2
#define PROTO extern
#define PROTO extern
Functions
PROTO UINT16 CiA402_Init (void)
Variables
PROTO pTCiA402Axis LocalAxes
Fault source error codes
__attribute__ ((section(".RAM_D3"))) volatile
This function initializes the Axes structures.
void CiA402_DeallocateAxis (void)
CiA402_DeallocateAxis.
int CiA402_UpdateObjects (TCiA402Axis *pCiA402Axis)
CiA402_UpdateObjects.
int CiA402_ConfigureObjects (TCiA402Axis *pCiA402Axis)
CiA402_ConfigureObjects.
void CiA402_StateMachine (void)
CiA402-Statemachine This function handles the state machine for devices using the CiA402 profile. called cyclic from MainLoop() All described transition numbers are referring to the document "ETG Implementation Guideline for the CiA402 Axis Profile" located on the EtherCAT.org download section.
void APPL_MainLoop ()
void CiA402_LocalError (UINT16 ErrorCode)
CiA402_LocalError.
BOOL CiA402_TransitionAction (INT16 Characteristic, TCiA402Axis *pCiA402Axis)
CiA402-TransitionAction.
void CiA402_Application (TCiA402Axis *pCiA402Axis)
CiA402-Application.
void APPL_AckErrorInd (UINT16 stateTrans)
The function is called when an error state was acknowledged by the master.
UINT16 APPL_StartMailboxHandler (void)
The function is called in the state transition from INIT to PREOP when all general settings were checked to start the mailbox handler. This function informs the application about the state transition, the application can refuse the state transition when returning an AL Status error code. The return code NOERROR_INWORK can be used, if the application cannot confirm the state transition immediately, in that case the application need to be complete the transition by calling ECAT_StateChange.
UINT16 APPL_StopMailboxHandler (void)
The function is called in the state transition from PREEOP to INIT to stop the mailbox handler. This functions informs the application about the state transition, the application cannot refuse the state transition.
UINT16 APPL_StartInputHandler (UINT16 *pIntMask)
The function is called in the state transition from PREOP to SAFEOP when all general settings were checked to start the input handler. This function informs the application about the state transition, the application can refuse the state transition when returning an AL Status error code. The return code NOERROR_INWORK can be used, if the application cannot confirm the state transition immediately, in that case the application need to be complete the transition by calling ECAT_StateChange.
UINT16 APPL_StopInputHandler (void)
The function is called in the state transition from SAFEOP to PREEOP to stop the input handler. This functions informs the application about the state transition, the application cannot refuse the state transition.
UINT16 APPL_StartOutputHandler (void)
The function is called in the state transition from SAFEOP to OP when all general settings were checked to start the output handler. This function informs the application about the state transition, the application can refuse the state transition when returning an AL Status error code. The return code NOERROR_INWORK can be used, if the application cannot confirm the state transition immediately, in that case the application need to be complete the transition by calling ECAT_StateChange.
UINT16 APPL_StopOutputHandler (void)
The function is called in the state transition from OP to SAFEOP to stop the output handler. This functions informs the application about the state transition, the application cannot refuse the state transition.
UINT16 APPL_GenerateMapping (UINT16 *pInputSize, UINT16 *pOutputSize)
This function calculates the process data sizes from the actual SM-PDO-Assign and PDO mapping.
void APPL_InputMapping (UINT16 *pData)
This function will copies the inputs from the local memory to the ESC memory to the hardware.
void APPL_OutputMapping (UINT16 *pData)
This function will copies the outputs from the ESC memory to the local memory to the hardware.
void APPL_Application (void)
This function will called from the synchronisation ISR or from the mainloop if no synchronisation is supported.
#define MC_NO_ERROR (uint16_t)(0x0000u)
No error.
#define MC_NO_FAULTS (uint16_t)(0x0000u)
No error.
#define MC_FOC_DURATION (uint16_t)(0x0001u)
Error: FOC rate to high.
#define MC_OVER_VOLT (uint16_t)(0x0002u)
Error: Software over voltage.
#define MC_UNDER_VOLT (uint16_t)(0x0004u)
Error: Software under voltage.
#define MC_OVER_TEMP (uint16_t)(0x0008u)
Error: Software over temperature.
#define MC_START_UP (uint16_t)(0x0010u)
Error: Startup failed.
#define MC_SPEED_FDBK (uint16_t)(0x0020u)
Error: Speed feedback.
#define MC_BREAK_IN (uint16_t)(0x0040u)
Error: Emergency input (Over current).
#define MC_SW_ERROR (uint16_t)(0x0080u)
Software Error.
Detailed Description
Macro Definition Documentation
_AX58400__MOTOR_CONTROL_
#define _AX58400__MOTOR_CONTROL_ 1
Definition at line 28 of file AX58400_MotorControl.c.
CONTROLWORD_COMMAND_DISABLEOPERATION
#define CONTROLWORD_COMMAND_DISABLEOPERATION 0x0007
Disable operation command.
Definition at line 57 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_DISABLEOPERATION_MASK
#define CONTROLWORD_COMMAND_DISABLEOPERATION_MASK 0x008F
Disable operation command mask.
Definition at line 44 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_DISABLEVOLTAGE
#define CONTROLWORD_COMMAND_DISABLEVOLTAGE 0x0000
Disable voltage command.
Definition at line 55 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_DISABLEVOLTAGE_MASK
#define CONTROLWORD_COMMAND_DISABLEVOLTAGE_MASK 0x0082
Disable voltage command mask.
Definition at line 42 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_ENABLEOPERATION
#define CONTROLWORD_COMMAND_ENABLEOPERATION 0x000F
Enable operation command.
Definition at line 58 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_ENABLEOPERATION_MASK
#define CONTROLWORD_COMMAND_ENABLEOPERATION_MASK 0x008F
Enable operation command mask.
Definition at line 45 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_FAULTRESET
#define CONTROLWORD_COMMAND_FAULTRESET 0x0080
Fault reset command.
Definition at line 59 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_FAULTRESET_MASK
#define CONTROLWORD_COMMAND_FAULTRESET_MASK 0x0080
Fault reset command mask.
Definition at line 46 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_QUICKSTOP
#define CONTROLWORD_COMMAND_QUICKSTOP 0x0002
Quickstop command.
Definition at line 56 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_QUICKSTOP_MASK
#define CONTROLWORD_COMMAND_QUICKSTOP_MASK 0x0086
Quickstop command mask.
Definition at line 43 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_SHUTDOWN
#define CONTROLWORD_COMMAND_SHUTDOWN 0x0006
Shutdown command.
Definition at line 52 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_SHUTDOWN_MASK
#define CONTROLWORD_COMMAND_SHUTDOWN_MASK 0x0087
Shutdown command mask.
Definition at line 39 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_SWITCHON
#define CONTROLWORD_COMMAND_SWITCHON 0x0007
Switch on command.
Definition at line 53 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION
#define CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION 0x000F
Switch on & Enable command.
Definition at line 54 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION_MASK
#define CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION_MASK 0x008F
Switch on & Enable command mask.
Definition at line 41 of file AX58400_MotorControl.h.
CONTROLWORD_COMMAND_SWITCHON_MASK
#define CONTROLWORD_COMMAND_SWITCHON_MASK 0x00C7
Switch on command mask.
Definition at line 40 of file AX58400_MotorControl.h.
CSP_MODULE_ID
#define CSP_MODULE_ID 0x00219800
Module Id for cyclic synchronous position mode.
Definition at line 328 of file AX58400_MotorControl.h.
CSV_CSP_MODULE_ID
#define CSV_CSP_MODULE_ID 0x00119800
Module Id for cyclic synchronous position/velocity mode (dynamic switching supported)
Definition at line 327 of file AX58400_MotorControl.h.
CSV_MODULE_ID
#define CSV_MODULE_ID 0x00319800
Module Id for cyclic synchronous velocity mode.
Definition at line 329 of file AX58400_MotorControl.h.
CURRENT_LIMIT_NO_TRANSIT
#define CURRENT_LIMIT_NO_TRANSIT 7
Slow down on current limit and stay in Quick Stop Active.
Definition at line 313 of file AX58400_MotorControl.h.
CYCLIC_SYNC_POSITION_MODE
#define CYCLIC_SYNC_POSITION_MODE 8
Cyclic Synchronous Position mode.
Definition at line 114 of file AX58400_MotorControl.h.
CYCLIC_SYNC_TORQUE_MODE
#define CYCLIC_SYNC_TORQUE_MODE 10
Cyclic Synchronous Torque mode.
Definition at line 116 of file AX58400_MotorControl.h.
CYCLIC_SYNC_VELOCITY_MODE
#define CYCLIC_SYNC_VELOCITY_MODE 9
Cyclic Synchronous Velocity mode.
Definition at line 115 of file AX58400_MotorControl.h.
DEFULT_VL_RAMP_FUNC_TIME
#define DEFULT_VL_RAMP_FUNC_TIME 500 /* ms */
Definition at line 317 of file AX58400_MotorControl.h.
DISABLE_DRIVE
#define DISABLE_DRIVE 0
Disable drive (options: 0x605B; 0x605C; 0x605E)
Definition at line 299 of file AX58400_MotorControl.h.
ERROR_ARMATURE_CIRCUIT
#define ERROR_ARMATURE_CIRCUIT 0x3320
Armature circuit.
Definition at line 183 of file AX58400_MotorControl.h.
ERROR_ARMATURE_CIRCUIT_INTERRUPTED
#define ERROR_ARMATURE_CIRCUIT_INTERRUPTED 0x3321
Armature circuit interrupted.
Definition at line 184 of file AX58400_MotorControl.h.
ERROR_BRAKE_CHOPPER
#define ERROR_BRAKE_CHOPPER 0x7110
Brake chopper.
Definition at line 244 of file AX58400_MotorControl.h.
ERROR_CHOPPER
#define ERROR_CHOPPER 0x5420
Chopper error.
Definition at line 217 of file AX58400_MotorControl.h.
ERROR_COMMUNICATION
#define ERROR_COMMUNICATION 0x7500
Communication error.
Definition at line 264 of file AX58400_MotorControl.h.
ERROR_COMPUTATION_CIRCUIT
#define ERROR_COMPUTATION_CIRCUIT 0x7400
Computation circuit.
Definition at line 263 of file AX58400_MotorControl.h.
ERROR_CONTACT_1_MANUFACTURER_SPECIFIC
#define ERROR_CONTACT_1_MANUFACTURER_SPECIFIC 0x5441
Contact 1 = manufacturer-specific error.
Definition at line 220 of file AX58400_MotorControl.h.
ERROR_CONTACT_2_MANUFACTURER_SPECIFIC
#define ERROR_CONTACT_2_MANUFACTURER_SPECIFIC 0x5442
Contact 2 = manufacturer-specific error.
Definition at line 221 of file AX58400_MotorControl.h.
ERROR_CONTACT_3_MANUFACTURER_SPECIFIC
#define ERROR_CONTACT_3_MANUFACTURER_SPECIFIC 0x5443
Contact 3 = manufacturer-specific error.
Definition at line 222 of file AX58400_MotorControl.h.
ERROR_CONTACT_4_MANUFACTURER_SPECIFIC
#define ERROR_CONTACT_4_MANUFACTURER_SPECIFIC 0x5444
Contact 4 = manufacturer-specific error.
Definition at line 223 of file AX58400_MotorControl.h.
ERROR_CONTACT_5_MANUFACTURER_SPECIFIC
#define ERROR_CONTACT_5_MANUFACTURER_SPECIFIC 0x5445
Contact 5 = manufacturer-specific error.
Definition at line 224 of file AX58400_MotorControl.h.
ERROR_CONTACTS_ERROR
#define ERROR_CONTACTS_ERROR 0x5440
Contacts error.
Definition at line 219 of file AX58400_MotorControl.h.
ERROR_CONTINUOUS_OVER_CURRENT
#define ERROR_CONTINUOUS_OVER_CURRENT 0x2310
Continuous over current.
Definition at line 142 of file AX58400_MotorControl.h.
ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL
#define ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL 0x2220
Continuous over current (device internal)
Definition at line 136 of file AX58400_MotorControl.h.
ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL_NO1
#define ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL_NO1 0x2221
Continuous over current no 1.
Definition at line 137 of file AX58400_MotorControl.h.
ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL_NO2
#define ERROR_CONTINUOUS_OVER_CURRENT_DEVICE_INTERNAL_NO2 0x2222
Continuous over current no 2.
Definition at line 138 of file AX58400_MotorControl.h.
ERROR_CONTINUOUS_OVER_CURRENT_NO1
#define ERROR_CONTINUOUS_OVER_CURRENT_NO1 0x2311
Continuous over current no 1.
Definition at line 143 of file AX58400_MotorControl.h.
ERROR_CONTINUOUS_OVER_CURRENT_NO2
#define ERROR_CONTINUOUS_OVER_CURRENT_NO2 0x2312
Continuous over current no 2.
Definition at line 144 of file AX58400_MotorControl.h.
ERROR_CONTROL_COMPUTING_CIRCUIT
#define ERROR_CONTROL_COMPUTING_CIRCUIT 0x5220
Computing circuit.
Definition at line 213 of file AX58400_MotorControl.h.
ERROR_CONTROL_MEASUREMENT_CIRCUIT
#define ERROR_CONTROL_MEASUREMENT_CIRCUIT 0x5210
Measurement circuit.
Definition at line 212 of file AX58400_MotorControl.h.
ERROR_DATA_STORAGE_EXTERNAL
#define ERROR_DATA_STORAGE_EXTERNAL 0x7600
Data storage (external) error.
Definition at line 267 of file AX58400_MotorControl.h.
ERROR_DC_LINK_OVER_VOLTAGE
#define ERROR_DC_LINK_OVER_VOLTAGE 0x3210
DC link over-voltage.
Definition at line 172 of file AX58400_MotorControl.h.
ERROR_DC_LINK_UNDER_VOLTAGE
#define ERROR_DC_LINK_UNDER_VOLTAGE 0x3220
DC link under-voltage.
Definition at line 175 of file AX58400_MotorControl.h.
ERROR_DECELERATION
#define ERROR_DECELERATION 0xF001
Deceleration error.
Definition at line 283 of file AX58400_MotorControl.h.
ERROR_DIFFICULT_START_UP
#define ERROR_DIFFICULT_START_UP 0x8312
Difficult start up error.
Definition at line 270 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_DEVICE_INTERNAL
#define ERROR_EARTH_LEAKAGE_DEVICE_INTERNAL 0x2240
Earth leakage (device internal)
Definition at line 140 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_INPUT
#define ERROR_EARTH_LEAKAGE_INPUT 0x2120
Earth leakage (input)
Definition at line 124 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_MOTOR_SIDE
#define ERROR_EARTH_LEAKAGE_MOTOR_SIDE 0x2330
Earth leakage (motor-side)
Definition at line 146 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_L1
#define ERROR_EARTH_LEAKAGE_PHASE_L1 0x2121
Earth leakage phase L1.
Definition at line 125 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_L2
#define ERROR_EARTH_LEAKAGE_PHASE_L2 0x2122
Earth leakage phase L2.
Definition at line 126 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_L3
#define ERROR_EARTH_LEAKAGE_PHASE_L3 0x2123
Earth leakage phase L3.
Definition at line 127 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_U
#define ERROR_EARTH_LEAKAGE_PHASE_U 0x2331
Earth leakage phase U.
Definition at line 147 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_V
#define ERROR_EARTH_LEAKAGE_PHASE_V 0x2332
Earth leakage phase V.
Definition at line 148 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_V_W
#define ERROR_EARTH_LEAKAGE_PHASE_V_W 0x2342
Earth leakage phase V-W.
Definition at line 152 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_W
#define ERROR_EARTH_LEAKAGE_PHASE_W 0x2333
Earth leakage phase W.
Definition at line 149 of file AX58400_MotorControl.h.
ERROR_EARTH_LEAKAGE_PHASE_W_U
#define ERROR_EARTH_LEAKAGE_PHASE_W_U 0x2343
Earth leakage phase W-U.
Definition at line 153 of file AX58400_MotorControl.h.
ERROR_EEPROM
#define ERROR_EEPROM 0x5530
EEPROM error.
Definition at line 238 of file AX58400_MotorControl.h.
ERROR_EMERGENCY_OCCUR
#define ERROR_EMERGENCY_OCCUR 0xFF00
Emergency occur.
Definition at line 288 of file AX58400_MotorControl.h.
ERROR_EXCESS_AMBIENT_TEMPERATURE
#define ERROR_EXCESS_AMBIENT_TEMPERATURE 0x4110
Excess ambient temperature.
Definition at line 187 of file AX58400_MotorControl.h.
ERROR_EXCESS_TEMPERATURE_DEVICE
#define ERROR_EXCESS_TEMPERATURE_DEVICE 0x4210
Excess temperature device.
Definition at line 191 of file AX58400_MotorControl.h.
ERROR_EXCESS_TEMPERATURE_DRIVE
#define ERROR_EXCESS_TEMPERATURE_DRIVE 0x4310
Excess temperature drive error.
Definition at line 194 of file AX58400_MotorControl.h.
ERROR_EXCESS_TEMPERATURE_SUPPLY
#define ERROR_EXCESS_TEMPERATURE_SUPPLY 0x4410
Excess temperature supply.
Definition at line 197 of file AX58400_MotorControl.h.
ERROR_EXCESS_TORQUE
#define ERROR_EXCESS_TORQUE 0x8311
Excess torque error.
Definition at line 269 of file AX58400_MotorControl.h.
ERROR_FAILURE_BRAKE_CHOPPER
#define ERROR_FAILURE_BRAKE_CHOPPER 0x7111
Failure brake chopper.
Definition at line 245 of file AX58400_MotorControl.h.
ERROR_FIELD_CIRCUIT
#define ERROR_FIELD_CIRCUIT 0x3330
Field circuit error.
Definition at line 185 of file AX58400_MotorControl.h.
ERROR_FIELD_CIRCUIT_INTERRUPTED
#define ERROR_FIELD_CIRCUIT_INTERRUPTED 0x3331
Field circuit interrupted.
Definition at line 186 of file AX58400_MotorControl.h.
ERROR_FOLLOWING_ERROR
#define ERROR_FOLLOWING_ERROR 0x8611
Following error.
Definition at line 277 of file AX58400_MotorControl.h.
ERROR_FUSES_ERROR
#define ERROR_FUSES_ERROR 0x5450
Fuses error.
Definition at line 225 of file AX58400_MotorControl.h.
ERROR_HARDWARE_MEMORY
#define ERROR_HARDWARE_MEMORY 0x5500
Hardware memory error.
Definition at line 235 of file AX58400_MotorControl.h.
ERROR_INCREMENTAL_SENSOR_1_FAULT
#define ERROR_INCREMENTAL_SENSOR_1_FAULT 0x7305
Incremental sensor 1 fault.
Definition at line 258 of file AX58400_MotorControl.h.
ERROR_INCREMENTAL_SENSOR_2_FAULT
#define ERROR_INCREMENTAL_SENSOR_2_FAULT 0x7306
Incremental sensor 2 fault.
Definition at line 259 of file AX58400_MotorControl.h.
ERROR_INCREMENTAL_SENSOR_3_FAULT
#define ERROR_INCREMENTAL_SENSOR_3_FAULT 0x7307
Incremental sensor 3 fault.
Definition at line 260 of file AX58400_MotorControl.h.
ERROR_INPUT_STAGES
#define ERROR_INPUT_STAGES 0x5430
Input stages error.
Definition at line 218 of file AX58400_MotorControl.h.
ERROR_INSUFFICIENT_TORQUE
#define ERROR_INSUFFICIENT_TORQUE 0x8321
Insufficient torque error.
Definition at line 272 of file AX58400_MotorControl.h.
ERROR_INTERNAL_CURRENT_NO1
#define ERROR_INTERNAL_CURRENT_NO1 0x2211
Internal current no 1.
Definition at line 132 of file AX58400_MotorControl.h.
ERROR_INTERNAL_CURRENT_NO2
#define ERROR_INTERNAL_CURRENT_NO2 0x2212
Internal current no 2.
Definition at line 133 of file AX58400_MotorControl.h.
ERROR_LOAD_ERROR
#define ERROR_LOAD_ERROR 0x3230
Load error.
Definition at line 178 of file AX58400_MotorControl.h.
ERROR_LOAD_LEVEL_FAULT_I2T_THERMAL_STATE
#define ERROR_LOAD_LEVEL_FAULT_I2T_THERMAL_STATE 0x2350
Load level fault (I2t, thermal state)
Definition at line 154 of file AX58400_MotorControl.h.
ERROR_LOAD_LEVEL_WARNING_I2T_THERMAL_STATE
#define ERROR_LOAD_LEVEL_WARNING_I2T_THERMAL_STATE 0x2351
Load level warning (I2t, thermal state)
Definition at line 155 of file AX58400_MotorControl.h.
ERROR_LOSS_OF_PARAMETERS
#define ERROR_LOSS_OF_PARAMETERS 0x6310
Loss of parameters.
Definition at line 241 of file AX58400_MotorControl.h.
ERROR_MAINS_FREQUENCY
#define ERROR_MAINS_FREQUENCY 0x3140
Mains frequency.
Definition at line 169 of file AX58400_MotorControl.h.
ERROR_MAINS_FREQUENCY_TOO_GREAT
#define ERROR_MAINS_FREQUENCY_TOO_GREAT 0x3141
Mains frequency too great.
Definition at line 170 of file AX58400_MotorControl.h.
ERROR_MAINS_FREQUENCY_TOO_SMALL
#define ERROR_MAINS_FREQUENCY_TOO_SMALL 0x3142
Mains frequency too small.
Definition at line 171 of file AX58400_MotorControl.h.
ERROR_MAINS_OVER_VOLTAGE
#define ERROR_MAINS_OVER_VOLTAGE 0x3110
Mains over-voltage.
Definition at line 156 of file AX58400_MotorControl.h.
ERROR_MAINS_OVER_VOLTAGE_PHASE_L1
#define ERROR_MAINS_OVER_VOLTAGE_PHASE_L1 0x3111
Mains over-voltage phase L1.
Definition at line 157 of file AX58400_MotorControl.h.
ERROR_MAINS_OVER_VOLTAGE_PHASE_L2
#define ERROR_MAINS_OVER_VOLTAGE_PHASE_L2 0x3112
Mains over-voltage phase L2.
Definition at line 158 of file AX58400_MotorControl.h.
ERROR_MAINS_OVER_VOLTAGE_PHASE_L3
#define ERROR_MAINS_OVER_VOLTAGE_PHASE_L3 0x3113
Mains over-voltage phase L3.
Definition at line 159 of file AX58400_MotorControl.h.
ERROR_MAINS_UNDER_VOLTAGE
#define ERROR_MAINS_UNDER_VOLTAGE 0x3120
Mains under-voltage.
Definition at line 160 of file AX58400_MotorControl.h.
ERROR_MAINS_UNDER_VOLTAGE_PHASE_L1
#define ERROR_MAINS_UNDER_VOLTAGE_PHASE_L1 0x3121
Mains under-voltage phase L1.
Definition at line 161 of file AX58400_MotorControl.h.
ERROR_MAINS_UNDER_VOLTAGE_PHASE_L2
#define ERROR_MAINS_UNDER_VOLTAGE_PHASE_L2 0x3122
Mains under-voltage phase L2.
Definition at line 162 of file AX58400_MotorControl.h.
ERROR_MAINS_UNDER_VOLTAGE_PHASE_L3
#define ERROR_MAINS_UNDER_VOLTAGE_PHASE_L3 0x3123
Mains under-voltage phase L3.
Definition at line 163 of file AX58400_MotorControl.h.
ERROR_MEASUREMENT_CIRCUIT
#define ERROR_MEASUREMENT_CIRCUIT 0x7200
Measurement circuit.
Definition at line 252 of file AX58400_MotorControl.h.
ERROR_MOTOR_BLOCKED
#define ERROR_MOTOR_BLOCKED 0x7121
Motor blocked error.
Definition at line 249 of file AX58400_MotorControl.h.
ERROR_MOTOR_ERROR
#define ERROR_MOTOR_ERROR 0x7120
Motor error.
Definition at line 248 of file AX58400_MotorControl.h.
ERROR_MOTOR_ERROR_OR_COMMUTATION_MALFUNC
#define ERROR_MOTOR_ERROR_OR_COMMUTATION_MALFUNC 0x7122
Motor error or commutation malfunc.
Definition at line 250 of file AX58400_MotorControl.h.
ERROR_MOTOR_TILTED
#define ERROR_MOTOR_TILTED 0x7123
Motor tilted.
Definition at line 251 of file AX58400_MotorControl.h.
ERROR_OPERATING_UNIT
#define ERROR_OPERATING_UNIT 0x5300
Operating unit error.
Definition at line 214 of file AX58400_MotorControl.h.
ERROR_OUTPUT_OVER_VOLTAGE
#define ERROR_OUTPUT_OVER_VOLTAGE 0x3310
Output over-voltage.
Definition at line 179 of file AX58400_MotorControl.h.
ERROR_OUTPUT_OVER_VOLTAGE_PHASE_U
#define ERROR_OUTPUT_OVER_VOLTAGE_PHASE_U 0x3311
Output over-voltage phase U.
Definition at line 180 of file AX58400_MotorControl.h.
ERROR_OUTPUT_OVER_VOLTAGE_PHASE_V
#define ERROR_OUTPUT_OVER_VOLTAGE_PHASE_V 0x3312
Output over-voltage phase V.
Definition at line 181 of file AX58400_MotorControl.h.
ERROR_OUTPUT_OVER_VOLTAGE_PHASE_W
#define ERROR_OUTPUT_OVER_VOLTAGE_PHASE_W 0x3313
Output over-voltage phase W.
Definition at line 182 of file AX58400_MotorControl.h.
ERROR_OUTPUT_STAGES
#define ERROR_OUTPUT_STAGES 0x5410
Output stages error.
Definition at line 216 of file AX58400_MotorControl.h.
ERROR_OVER_CURRENT_BRAKE_CHOPPER
#define ERROR_OVER_CURRENT_BRAKE_CHOPPER 0x7112
Over current brake chopper.
Definition at line 246 of file AX58400_MotorControl.h.
ERROR_OVER_CURRENT_IN_RAMP_FUNCTION
#define ERROR_OVER_CURRENT_IN_RAMP_FUNCTION 0x2213
Over-current in ramp function.
Definition at line 134 of file AX58400_MotorControl.h.
ERROR_OVER_CURRENT_IN_THE_SEQUENCE
#define ERROR_OVER_CURRENT_IN_THE_SEQUENCE 0x2214
Over-current in the sequence.
Definition at line 135 of file AX58400_MotorControl.h.
ERROR_OVER_VOLTAGE_NO_1
#define ERROR_OVER_VOLTAGE_NO_1 0x3211
Over-voltage no 1.
Definition at line 173 of file AX58400_MotorControl.h.
ERROR_OVER_VOLTAGE_NO_2
#define ERROR_OVER_VOLTAGE_NO_2 0x3212
Over voltage no 2.
Definition at line 174 of file AX58400_MotorControl.h.
ERROR_PARAMETER_ERROR
#define ERROR_PARAMETER_ERROR 0x6320
Parameter error.
Definition at line 242 of file AX58400_MotorControl.h.
ERROR_PHASE_FAILURE
#define ERROR_PHASE_FAILURE 0x3130
Phase failure.
Definition at line 164 of file AX58400_MotorControl.h.
ERROR_PHASE_FAILURE_L1
#define ERROR_PHASE_FAILURE_L1 0x3131
Phase failure L1.
Definition at line 165 of file AX58400_MotorControl.h.
ERROR_PHASE_FAILURE_L2
#define ERROR_PHASE_FAILURE_L2 0x3132
Phase failure L2.
Definition at line 166 of file AX58400_MotorControl.h.
ERROR_PHASE_FAILURE_L3
#define ERROR_PHASE_FAILURE_L3 0x3133
Phase failure L3.
Definition at line 167 of file AX58400_MotorControl.h.
ERROR_PHASE_SEQUENCE
#define ERROR_PHASE_SEQUENCE 0x3134
Phase sequence.
Definition at line 168 of file AX58400_MotorControl.h.
ERROR_POSITION
#define ERROR_POSITION 0x7320
Position error.
Definition at line 262 of file AX58400_MotorControl.h.
ERROR_POSITION_CONTROLLER
#define ERROR_POSITION_CONTROLLER 0x8500
Position controller.
Definition at line 275 of file AX58400_MotorControl.h.
ERROR_POSITIONING_CONTROLLER
#define ERROR_POSITIONING_CONTROLLER 0x8600
Positioning controller.
Definition at line 276 of file AX58400_MotorControl.h.
ERROR_POWER_ERROR
#define ERROR_POWER_ERROR 0x7100
Power error.
Definition at line 243 of file AX58400_MotorControl.h.
ERROR_POWER_SECTION
#define ERROR_POWER_SECTION 0x5400
Power section error.
Definition at line 215 of file AX58400_MotorControl.h.
ERROR_PROCESS_DATA_MONITORING
#define ERROR_PROCESS_DATA_MONITORING 0x8900
Process data monitoring.
Definition at line 281 of file AX58400_MotorControl.h.
ERROR_PROTECTIVE_CIRCUIT_BRAKE_CHOPPER
#define ERROR_PROTECTIVE_CIRCUIT_BRAKE_CHOPPER 0x7113
Protective circuit brake chopper error.
Definition at line 247 of file AX58400_MotorControl.h.
ERROR_RAM
#define ERROR_RAM 0x5510
RAM error.
Definition at line 236 of file AX58400_MotorControl.h.
ERROR_REFERENCE_LIMIT
#define ERROR_REFERENCE_LIMIT 0x8612
Reference limit.
Definition at line 278 of file AX58400_MotorControl.h.
ERROR_RESOLVER_1_FAULT
#define ERROR_RESOLVER_1_FAULT 0x7303
Resolver 1 fault.
Definition at line 256 of file AX58400_MotorControl.h.
ERROR_RESOLVER_2_FAULT
#define ERROR_RESOLVER_2_FAULT 0x7304
Resolver 2 fault.
Definition at line 257 of file AX58400_MotorControl.h.
ERROR_ROM_EPROM
#define ERROR_ROM_EPROM 0x5520
ROM/EPROM error.
Definition at line 237 of file AX58400_MotorControl.h.
ERROR_S1_L1
#define ERROR_S1_L1 0x5451
S1 = l1 error.
Definition at line 226 of file AX58400_MotorControl.h.
ERROR_S2_L2
#define ERROR_S2_L2 0x5452
S2 = l2 error.
Definition at line 227 of file AX58400_MotorControl.h.
ERROR_S3_L3
#define ERROR_S3_L3 0x5453
S3 = l3 error.
Definition at line 228 of file AX58400_MotorControl.h.
ERROR_S4_MANUFACTURER_SPECIFIC
#define ERROR_S4_MANUFACTURER_SPECIFIC 0x5454
S4 = manufacturer-specific error.
Definition at line 229 of file AX58400_MotorControl.h.
ERROR_S5_MANUFACTURER_SPECIFIC
#define ERROR_S5_MANUFACTURER_SPECIFIC 0x5455
S5 = manufacturer-specific error.
Definition at line 230 of file AX58400_MotorControl.h.
ERROR_S6_MANUFACTURER_SPECIFIC
#define ERROR_S6_MANUFACTURER_SPECIFIC 0x5456
S6 = manufacturer-specific error.
Definition at line 231 of file AX58400_MotorControl.h.
ERROR_S7_MANUFACTURER_SPECIFIC
#define ERROR_S7_MANUFACTURER_SPECIFIC 0x5457
S7 = manufacturer-specific error.
Definition at line 232 of file AX58400_MotorControl.h.
ERROR_S8_MANUFACTURER_SPECIFIC
#define ERROR_S8_MANUFACTURER_SPECIFIC 0x5458
S8 = manufacturer-specific error.
Definition at line 233 of file AX58400_MotorControl.h.
ERROR_S9_MANUFACTURER_SPECIFIC
#define ERROR_S9_MANUFACTURER_SPECIFIC 0x5459
S9 = manufacturer-specific error.
Definition at line 234 of file AX58400_MotorControl.h.
ERROR_SENSOR_ERROR
#define ERROR_SENSOR_ERROR 0x7300
Sensor error.
Definition at line 253 of file AX58400_MotorControl.h.
ERROR_SERIAL_INTERFACE_NO_1
#define ERROR_SERIAL_INTERFACE_NO_1 0x7510
Serial interface no 1 error.
Definition at line 265 of file AX58400_MotorControl.h.
ERROR_SERIAL_INTERFACE_NO_2
#define ERROR_SERIAL_INTERFACE_NO_2 0x7520
Serial interface no 2 error.
Definition at line 266 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_DEVICE_INTERNAL
#define ERROR_SHORT_CIRCUIT_DEVICE_INTERNAL 0x2250
Short circuit (device internal)
Definition at line 141 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_DEVICE_INTERNAL
#define ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_DEVICE_INTERNAL 0x2230
Short circuit/earth leakage (device internal)
Definition at line 139 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_INPUT
#define ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_INPUT 0x2110
Short circuit/earth leakage (input)
Definition at line 123 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_MOTOR_SIDE
#define ERROR_SHORT_CIRCUIT_EARTH_LEAKAGE_MOTOR_SIDE 0x2320
Short circuit/earth leakage (motor-side)
Definition at line 145 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_INPUT
#define ERROR_SHORT_CIRCUIT_INPUT 0x2130
Short circuit (input)
Definition at line 128 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_MOTOR_SIDE
#define ERROR_SHORT_CIRCUIT_MOTOR_SIDE 0x2340
Short circuit (motor-side)
Definition at line 150 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_PHASES_L1_L2
#define ERROR_SHORT_CIRCUIT_PHASES_L1_L2 0x2131
Short circuit phases L1-L2.
Definition at line 129 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_PHASES_L2_L3
#define ERROR_SHORT_CIRCUIT_PHASES_L2_L3 0x2132
Short circuit phases L2-L3.
Definition at line 130 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_PHASES_L3_L1
#define ERROR_SHORT_CIRCUIT_PHASES_L3_L1 0x2133
Short circuit phases L3-L1.
Definition at line 131 of file AX58400_MotorControl.h.
ERROR_SHORT_CIRCUIT_PHASES_U_V
#define ERROR_SHORT_CIRCUIT_PHASES_U_V 0x2341
Short circuit phases U-V.
Definition at line 151 of file AX58400_MotorControl.h.
ERROR_SOFTWARE
#define ERROR_SOFTWARE 0xFF01
Definition at line 289 of file AX58400_MotorControl.h.
ERROR_SOFTWARE_RESET_WATCHDOG
#define ERROR_SOFTWARE_RESET_WATCHDOG 0x6010
Software reset (watchdog)
Definition at line 239 of file AX58400_MotorControl.h.
ERROR_SPEED
#define ERROR_SPEED 0x7310
Speed error.
Definition at line 261 of file AX58400_MotorControl.h.
ERROR_STANDSTILL_TORQUE
#define ERROR_STANDSTILL_TORQUE 0x8313
Standstill torque error.
Definition at line 271 of file AX58400_MotorControl.h.
ERROR_STROKE_OPERATION
#define ERROR_STROKE_OPERATION 0xF003
Stroke operation error.
Definition at line 285 of file AX58400_MotorControl.h.
ERROR_SUB_SYNCHRONOUS_RUN
#define ERROR_SUB_SYNCHRONOUS_RUN 0xF002
Sub-synchronous run error.
Definition at line 284 of file AX58400_MotorControl.h.
ERROR_SUPPLY_ERROR
#define ERROR_SUPPLY_ERROR 0x5100
Supply error.
Definition at line 199 of file AX58400_MotorControl.h.
ERROR_SUPPLY_INTERMEDIATE_CIRCUIT
#define ERROR_SUPPLY_INTERMEDIATE_CIRCUIT 0x5120
Supply intermediate circuit.
Definition at line 210 of file AX58400_MotorControl.h.
ERROR_SUPPLY_LOW_VOLTAGE
#define ERROR_SUPPLY_LOW_VOLTAGE 0x5110
Supply low voltage.
Definition at line 200 of file AX58400_MotorControl.h.
ERROR_SYNC_CONTROLLER
#define ERROR_SYNC_CONTROLLER 0x8700
Sync controller.
Definition at line 279 of file AX58400_MotorControl.h.
ERROR_TACHO_FAULT
#define ERROR_TACHO_FAULT 0x7301
Tacho fault.
Definition at line 254 of file AX58400_MotorControl.h.
ERROR_TACHO_WRONG_POLARITY
#define ERROR_TACHO_WRONG_POLARITY 0x7302
Tacho wrong polarity.
Definition at line 255 of file AX58400_MotorControl.h.
ERROR_TEMPERATURE_AIR_OUTLET
#define ERROR_TEMPERATURE_AIR_OUTLET 0x4140
Temperature air outlet.
Definition at line 190 of file AX58400_MotorControl.h.
ERROR_TEMPERATURE_DRIVE
#define ERROR_TEMPERATURE_DRIVE 0x4300
Temperature drive error.
Definition at line 193 of file AX58400_MotorControl.h.
ERROR_TEMPERATURE_SUPPLY
#define ERROR_TEMPERATURE_SUPPLY 0x4400
Temperature supply error.
Definition at line 196 of file AX58400_MotorControl.h.
ERROR_TEMPERATURE_SUPPLY_AIR
#define ERROR_TEMPERATURE_SUPPLY_AIR 0x4130
Temperature supply air.
Definition at line 189 of file AX58400_MotorControl.h.
ERROR_TOO_LOW_AMBIENT_TEMPERATURE
#define ERROR_TOO_LOW_AMBIENT_TEMPERATURE 0x4120
Too low ambient temperature.
Definition at line 188 of file AX58400_MotorControl.h.
ERROR_TOO_LOW_TEMPERATURE_DEVICE
#define ERROR_TOO_LOW_TEMPERATURE_DEVICE 0x4220
Too low temperature device.
Definition at line 192 of file AX58400_MotorControl.h.
ERROR_TOO_LOW_TEMPERATURE_DRIVE
#define ERROR_TOO_LOW_TEMPERATURE_DRIVE 0x4320
Too low temperature drive error.
Definition at line 195 of file AX58400_MotorControl.h.
ERROR_TOO_LOW_TEMPERATURE_SUPPLY
#define ERROR_TOO_LOW_TEMPERATURE_SUPPLY 0x4420
Too low temperature supply.
Definition at line 198 of file AX58400_MotorControl.h.
ERROR_TORQUE_CONTROL
#define ERROR_TORQUE_CONTROL 0x8300
Torque control error.
Definition at line 268 of file AX58400_MotorControl.h.
ERROR_TORQUE_FAULT
#define ERROR_TORQUE_FAULT 0x8331
Torque fault.
Definition at line 273 of file AX58400_MotorControl.h.
ERROR_U1_SUPPLY_15V
#define ERROR_U1_SUPPLY_15V 0x5111
U1 = supply +15V/-15V.
Definition at line 201 of file AX58400_MotorControl.h.
ERROR_U2_SUPPLY_24_V
#define ERROR_U2_SUPPLY_24_V 0x5112
U2 = supply +24 V.
Definition at line 202 of file AX58400_MotorControl.h.
ERROR_U3_SUPPLY_5_V
#define ERROR_U3_SUPPLY_5_V 0x5113
U3 = supply +5 V.
Definition at line 203 of file AX58400_MotorControl.h.
ERROR_U4_MANUFACTURER_SPECIFIC
#define ERROR_U4_MANUFACTURER_SPECIFIC 0x5114
U4 = manufacturer-specific error.
Definition at line 204 of file AX58400_MotorControl.h.
ERROR_U5_MANUFACTURER_SPECIFIC
#define ERROR_U5_MANUFACTURER_SPECIFIC 0x5115
U5 = manufacturer-specific error.
Definition at line 205 of file AX58400_MotorControl.h.
ERROR_U6_MANUFACTURER_SPECIFIC
#define ERROR_U6_MANUFACTURER_SPECIFIC 0x5116
U6 = manufacturer-specific error.
Definition at line 206 of file AX58400_MotorControl.h.
ERROR_U7_MANUFACTURER_SPECIFIC
#define ERROR_U7_MANUFACTURER_SPECIFIC 0x5117
U7 = manufacturer-specific error.
Definition at line 207 of file AX58400_MotorControl.h.
ERROR_U8_MANUFACTURER_SPECIFIC
#define ERROR_U8_MANUFACTURER_SPECIFIC 0x5118
U8 = manufacturer-specific error.
Definition at line 208 of file AX58400_MotorControl.h.
ERROR_U9_MANUFACTURER_SPECIFIC
#define ERROR_U9_MANUFACTURER_SPECIFIC 0x5119
U9 = manufacturer-specific error.
Definition at line 209 of file AX58400_MotorControl.h.
ERROR_UNDER_VOLTAGE_NO_1
#define ERROR_UNDER_VOLTAGE_NO_1 0x3221
Under-voltage no 1.
Definition at line 176 of file AX58400_MotorControl.h.
ERROR_UNDER_VOLTAGE_NO_2
#define ERROR_UNDER_VOLTAGE_NO_2 0x3222
Under-voltage no 2.
Definition at line 177 of file AX58400_MotorControl.h.
ERROR_UNKNOWN
#define ERROR_UNKNOWN 0xFFFF
Definition at line 290 of file AX58400_MotorControl.h.
ERROR_VELOCITY_SPEED_CONTROLLER
#define ERROR_VELOCITY_SPEED_CONTROLLER 0x8400
Velocity speed controller.
Definition at line 274 of file AX58400_MotorControl.h.
ERROR_WINDING_CONTROLLER
#define ERROR_WINDING_CONTROLLER 0x8800
Winding controller.
Definition at line 280 of file AX58400_MotorControl.h.
ESC_RD
#define ESC_RD 1
Definition at line 335 of file AX58400_MotorControl.h.
ESC_WR
#define ESC_WR 2
Definition at line 336 of file AX58400_MotorControl.h.
HOMING_MODE
#define HOMING_MODE 6
Homing mode.
Definition at line 112 of file AX58400_MotorControl.h.
INTERPOLATION_POSITION_MODE
#define INTERPOLATION_POSITION_MODE 7
Interpolation Position mode.
Definition at line 113 of file AX58400_MotorControl.h.
MAX_AXES
#define MAX_AXES 1
Number of supported axes.
Definition at line 318 of file AX58400_MotorControl.h.
MC_BREAK_IN
#define MC_BREAK_IN (uint16_t)(0x0040u)
Error: Emergency input (Over current).
Definition at line 49 of file AX58400_MotorControl.c.
MC_FOC_DURATION
#define MC_FOC_DURATION (uint16_t)(0x0001u)
Error: FOC rate to high.
Definition at line 43 of file AX58400_MotorControl.c.
MC_NO_ERROR
#define MC_NO_ERROR (uint16_t)(0x0000u)
No error.
Definition at line 41 of file AX58400_MotorControl.c.
MC_NO_FAULTS
#define MC_NO_FAULTS (uint16_t)(0x0000u)
No error.
Definition at line 42 of file AX58400_MotorControl.c.
MC_OVER_TEMP
#define MC_OVER_TEMP (uint16_t)(0x0008u)
Error: Software over temperature.
Definition at line 46 of file AX58400_MotorControl.c.
MC_OVER_VOLT
#define MC_OVER_VOLT (uint16_t)(0x0002u)
Error: Software over voltage.
Definition at line 44 of file AX58400_MotorControl.c.
MC_SPEED_FDBK
#define MC_SPEED_FDBK (uint16_t)(0x0020u)
Error: Speed feedback.
Definition at line 48 of file AX58400_MotorControl.c.
MC_START_UP
#define MC_START_UP (uint16_t)(0x0010u)
Error: Startup failed.
Definition at line 47 of file AX58400_MotorControl.c.
MC_SW_ERROR
#define MC_SW_ERROR (uint16_t)(0x0080u)
Software Error.
Definition at line 50 of file AX58400_MotorControl.c.
MC_UNDER_VOLT
#define MC_UNDER_VOLT (uint16_t)(0x0004u)
Error: Software under voltage.
Definition at line 45 of file AX58400_MotorControl.c.
NO_MODE
#define NO_MODE 0
No mode.
Definition at line 106 of file AX58400_MotorControl.h.
PROFILE_POSITION_MODE
#define PROFILE_POSITION_MODE 1
Position Profile mode.
Definition at line 107 of file AX58400_MotorControl.h.
PROFILE_TORQUE_MODE
#define PROFILE_TORQUE_MODE 4
Torque Profile mode.
Definition at line 110 of file AX58400_MotorControl.h.
PROFILE_VELOCITY_MOCE
#define PROFILE_VELOCITY_MOCE 3
Velocity Profile mode.
Definition at line 109 of file AX58400_MotorControl.h.
PROTO [1/2]
#define PROTO extern
Definition at line 509 of file AX58400_MotorControl.h.
PROTO [2/2]
#define PROTO extern
Definition at line 22 of file AX58400_MotorControlObjects.h.
QUICKSTOP_RAMP
#define QUICKSTOP_RAMP 2
Quick stop ramp (options: 0x605E)
Definition at line 301 of file AX58400_MotorControl.h.
QUICKSTOP_RAMP_NO_TRANSIT
#define QUICKSTOP_RAMP_NO_TRANSIT 6
Slow down on quick stop ramp and stay in Quick Stop Active.
Definition at line 312 of file AX58400_MotorControl.h.
SLOW_DOWN_RAMP
#define SLOW_DOWN_RAMP 1
Slow down ramp (options: 0x605B; 0x605C; 0x605E)
Definition at line 300 of file AX58400_MotorControl.h.
SLOWDOWN_RAMP_NO_TRANSIT
#define SLOWDOWN_RAMP_NO_TRANSIT 5
Slow down on slow down ramp and stay in Quick Stop Active.
Definition at line 311 of file AX58400_MotorControl.h.
STATE_FAULT
#define STATE_FAULT 0x0080
Fault state (mandatory)
Definition at line 99 of file AX58400_MotorControl.h.
STATE_FAULT_REACTION_ACTIVE
#define STATE_FAULT_REACTION_ACTIVE 0x0040
Fault reaction active (mandatory)
Definition at line 98 of file AX58400_MotorControl.h.
STATE_NOT_READY_TO_SWITCH_ON
#define STATE_NOT_READY_TO_SWITCH_ON 0x0001
Not ready to switch on (optional)
Definition at line 92 of file AX58400_MotorControl.h.
STATE_OPERATION_ENABLED
#define STATE_OPERATION_ENABLED 0x0010
Operation enabled (mandatory)
Definition at line 96 of file AX58400_MotorControl.h.
STATE_QUICK_STOP_ACTIVE
#define STATE_QUICK_STOP_ACTIVE 0x0020
Quick stop active (optional)
Definition at line 97 of file AX58400_MotorControl.h.
STATE_READY_TO_SWITCH_ON
#define STATE_READY_TO_SWITCH_ON 0x0004
Ready to switch on (mandatory)
Definition at line 94 of file AX58400_MotorControl.h.
STATE_SWITCH_ON_DISABLED
#define STATE_SWITCH_ON_DISABLED 0x0002
Switch on but disabled (optional)
Definition at line 93 of file AX58400_MotorControl.h.
STATE_SWITCHED_ON
#define STATE_SWITCHED_ON 0x0008
Switch on (mandatory)
Definition at line 95 of file AX58400_MotorControl.h.
STATUSWORD_DRIVE_FOLLOWS_COMMAND
#define STATUSWORD_DRIVE_FOLLOWS_COMMAND 0x1000
Drive follows command (used in cyclic synchronous modes)
Definition at line 73 of file AX58400_MotorControl.h.
STATUSWORD_INTERNAL_LIMIT
#define STATUSWORD_INTERNAL_LIMIT 0x0800
Internal limit.
Definition at line 69 of file AX58400_MotorControl.h.
STATUSWORD_INTERNALLIMITACTIVE
#define STATUSWORD_INTERNALLIMITACTIVE 0x0800
Internal limit active.
Definition at line 72 of file AX58400_MotorControl.h.
STATUSWORD_MANUFACTORSPECIFIC
#define STATUSWORD_MANUFACTORSPECIFIC 0x0100
Manufacturer specific.
Definition at line 68 of file AX58400_MotorControl.h.
STATUSWORD_REMOTE
#define STATUSWORD_REMOTE 0x0200
Set if the control word is processed.
Definition at line 70 of file AX58400_MotorControl.h.
STATUSWORD_STATE_FAULT
#define STATUSWORD_STATE_FAULT 0x0008
Fault state.
Definition at line 86 of file AX58400_MotorControl.h.
STATUSWORD_STATE_FAULTREACTIONACTIVE
#define STATUSWORD_STATE_FAULTREACTIONACTIVE 0x000F
Fault reaction active.
Definition at line 85 of file AX58400_MotorControl.h.
STATUSWORD_STATE_MASK
#define STATUSWORD_STATE_MASK 0x006F
State mask.
Definition at line 65 of file AX58400_MotorControl.h.
STATUSWORD_STATE_NOTREADYTOSWITCHON
#define STATUSWORD_STATE_NOTREADYTOSWITCHON 0x0000
Not ready to switch on.
Definition at line 79 of file AX58400_MotorControl.h.
STATUSWORD_STATE_OPERATIONENABLED
#define STATUSWORD_STATE_OPERATIONENABLED 0x0027
Operation enabled.
Definition at line 83 of file AX58400_MotorControl.h.
STATUSWORD_STATE_QUICKSTOPACTIVE
#define STATUSWORD_STATE_QUICKSTOPACTIVE 0x0007
Quickstop active.
Definition at line 84 of file AX58400_MotorControl.h.
STATUSWORD_STATE_READYTOSWITCHON
#define STATUSWORD_STATE_READYTOSWITCHON 0x0021
Ready to switch on.
Definition at line 81 of file AX58400_MotorControl.h.
STATUSWORD_STATE_SWITCHEDON
#define STATUSWORD_STATE_SWITCHEDON 0x0023
Switched on.
Definition at line 82 of file AX58400_MotorControl.h.
STATUSWORD_STATE_SWITCHEDONDISABLED
#define STATUSWORD_STATE_SWITCHEDONDISABLED 0x0040
Switched on but disabled.
Definition at line 80 of file AX58400_MotorControl.h.
STATUSWORD_TARGET_REACHED
#define STATUSWORD_TARGET_REACHED 0x0400
Target reached.
Definition at line 71 of file AX58400_MotorControl.h.
STATUSWORD_VOLTAGE_ENABLED
#define STATUSWORD_VOLTAGE_ENABLED 0x0010
Indicate high voltage enabled.
Definition at line 66 of file AX58400_MotorControl.h.
STATUSWORD_WARNING
#define STATUSWORD_WARNING 0x0080
Warning active.
Definition at line 67 of file AX58400_MotorControl.h.
STOP_ON_CURRENT_LIMIT
#define STOP_ON_CURRENT_LIMIT 3
Stop on current limit (options: 0x605E)
Definition at line 302 of file AX58400_MotorControl.h.
STOP_ON_VOLTAGE_LIMIT
#define STOP_ON_VOLTAGE_LIMIT 4
Stop on voltage limit (options: 0x605E)
Definition at line 303 of file AX58400_MotorControl.h.
VELOCITY_MODE
#define VELOCITY_MODE 2
Velocity mode.
Definition at line 108 of file AX58400_MotorControl.h.
VOLTAGE_LIMIT_NO_TRANSIT
#define VOLTAGE_LIMIT_NO_TRANSIT 8
Slow down on voltage limit and stay in Quick Stop Active.
Definition at line 314 of file AX58400_MotorControl.h.
Function Documentation
__attribute__()
__attribute__ ((section(".RAM_D3"))) volatile
This function initializes the Axes structures.
Returns
0 Init CiA402 device successful ALSTATUSCODE_XX Init CiA402 device failed
Definition at line 76 of file AX58400_MotorControl.c.
References TCiA402Axis::bAxisFunctionEnabled, TCiA402Axis::bAxisIsActive, TCiA402Axis::bBrakeApplied, TCiA402Axis::bConfigurationAllowed, TCiA402Axis::bHighLevelPowerApplied, TCiA402Axis::bLowLevelPowerApplied, Controlword0x6040, DigitalInputs0x60FD, DisableOperationOptionCode0x605C, ErrorCode0x603F, FaultReactionOptionCode0x605E, TCiA402Axis::fCurPosition, HomeOffset0x607C, HomingAcceleration0x609A, HomingMethod0x6098, HomingSpeed0x6099, TCiA402Axis::i16State, InterpolationTimePeriod0x60C2, MAX_AXES, ModesOfOperation0x6060, ModesOfOperationDisplay0x6061, ModularDeviceProfile0xF000, ModuleProfileList0xF010, TCiA402Axis::ObjDic, OBJ_STRUCT_PACKED_START::objDigitalInputs, OBJ_STRUCT_PACKED_START::objDisableOperationOptionCode, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::objFaultReactionCode, OBJ_STRUCT_PACKED_START::objHomingAcceleration, OBJ_STRUCT_PACKED_START::objHomingMethod, OBJ_STRUCT_PACKED_START::objInterpolationTimePeriod, OBJ_STRUCT_PACKED_START::objModesOfOperation, OBJ_STRUCT_PACKED_START::objQuickStopDeclaration, OBJ_STRUCT_PACKED_START::objQuickStopOptionCode, OBJ_STRUCT_PACKED_START::objShutdownOptionCode, OBJ_STRUCT_PACKED_START::objSoftwarePositionLimit, OBJ_STRUCT_PACKED_START::objSupportedDriveModes, OBJ_STRUCT_PACKED_START::objSupportedHomingMode, OBJ_STRUCT_PACKED_START::objTargetVelocity, OBJ_STRUCT_PACKED_START::objVlRampFunctionTime, pAPPL_MainLoop, OBJ_STRUCT_PACKED_START::pobjControlWord, OBJ_STRUCT_PACKED_START::pobjErrorCode, OBJ_STRUCT_PACKED_START::pobjHomeOffset, OBJ_STRUCT_PACKED_START::pobjHomingSpeed, OBJ_STRUCT_PACKED_START::pobjModesOfOperationDisplay, OBJ_STRUCT_PACKED_START::pobjPositionActualValue, OBJ_STRUCT_PACKED_START::pobjStatusWord, OBJ_STRUCT_PACKED_START::pobjTargetPosition, OBJ_STRUCT_PACKED_START::pobjTorqueActualValue, OBJ_STRUCT_PACKED_START::pobjVelocityActualValue, PositionActualValue0x6064, QuickStopDeceleration0x6085, QuickStopOptionCode0x605A, RxPdoMappingCsp0x1601, RxPdoMappingCspCsv0x1600, RxPdoMappingCsv0x1602, ShutdownOptionCode0x605B, SoftwarePositionLimit0x607D, sRxPDOassign, OBJ_STRUCT_PACKED_START::sRxPDOMap0, OBJ_STRUCT_PACKED_START::sRxPDOMap1, OBJ_STRUCT_PACKED_START::sRxPDOMap2, STATE_NOT_READY_TO_SWITCH_ON, Statusword0x6041, sTxPDOassign, OBJ_STRUCT_PACKED_START::sTxPDOMap0, OBJ_STRUCT_PACKED_START::sTxPDOMap1, OBJ_STRUCT_PACKED_START::sTxPDOMap2, SupportedDriveModes0x6502, SupportedHomingMethods0x60E3, TargetPosition0x607A, TargetVelocity0x60FF, TorqueActualValue0x6077, TxPdoMappingCsp0x1A01, TxPdoMappingCspCsv0x1A00, TxPdoMappingCsv0x1A02, TCiA402Axis::u16PendingOptionCode, TCiA402Axis::u32CycleTime, VelocityActualValue0x606C, and VLRampFunctionTime0x604F.
APPL_AckErrorInd()
PROTO void APPL_AckErrorInd (UINT16 stateTrans)
The function is called when an error state was acknowledged by the master.
Definition at line 852 of file AX58400_MotorControl.c.
Referenced by AL_ControlInd().
APPL_Application()
PROTO void APPL_Application (void)
This function will called from the synchronisation ISR or from the mainloop if no synchronisation is supported.
Definition at line 1434 of file AX58400_MotorControl.c.
References CiA402_Application(), CiA402_UpdateObjects(), and MAX_AXES.
Referenced by ECAT_Application().
APPL_GenerateMapping()
PROTO UINT16 APPL_GenerateMapping (UINT16 * pInputSize, UINT16 * pOutputSize)
This function calculates the process data sizes from the actual SM-PDO-Assign and PDO mapping.
Returns
0(ALSTATUSCODE_NOERROR), NOERROR_INWORK
Parameters
pInputSize pointer to save the input process data length
pOutputSize pointer to save the output process data length
Definition at line 1070 of file AX58400_MotorControl.c.
References OBJ_STRUCT_PACKED_START::aEntries, ALSTATUSCODE_NOERROR, ALSTATUSCODE_NOVALIDOUTPUTS, TCiA402Axis::bAxisIsActive, COE_AddObjectToDic(), COE_RemoveDicEntry(), MAX_AXES, TCiA402Axis::ObjDic, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::objSupportedDriveModes, sRxPDOassign, OBJ_STRUCT_PACKED_START::sRxPDOMap0, OBJ_STRUCT_PACKED_START::sRxPDOMap1, OBJ_STRUCT_PACKED_START::sRxPDOMap2, sTxPDOassign, OBJ_STRUCT_PACKED_START::sTxPDOMap0, OBJ_STRUCT_PACKED_START::sTxPDOMap1, OBJ_STRUCT_PACKED_START::sTxPDOMap2, and OBJ_STRUCT_PACKED_START::u16SubIndex0.
Referenced by AL_ControlInd().
APPL_InputMapping()
PROTO void APPL_InputMapping (UINT16 * pData)
This function will copies the inputs from the local memory to the ESC memory to the hardware.
Parameters
pData pointer to input process data
Definition at line 1311 of file AX58400_MotorControl.c.
References OBJ_STRUCT_PACKED_START::aEntries, STRUCT_PACKED_START::ObjModesOfOperationDisplay, STRUCT_PACKED_START::ObjPositionActualValue, STRUCT_PACKED_START::ObjStatusWord, STRUCT_PACKED_START::ObjVelocityActualValue, sTxPDOassign, SWAPDWORD, SWAPWORD, and OBJ_STRUCT_PACKED_START::u16SubIndex0.
Referenced by PDO_InputMapping().
APPL_MainLoop()
PROTO void APPL_MainLoop ()
Definition at line 631 of file AX58400_MotorControl.c.
APPL_OutputMapping()
PROTO void APPL_OutputMapping (UINT16 * pData)
This function will copies the outputs from the ESC memory to the local memory to the hardware.
Parameters
pData pointer to output process data
Definition at line 1374 of file AX58400_MotorControl.c.
References OBJ_STRUCT_PACKED_START::aEntries, STRUCT_PACKED_START::ObjControlWord, TCiA402Axis::Objects, STRUCT_PACKED_START::ObjModesOfOperation, OBJ_STRUCT_PACKED_START::objModesOfOperation, STRUCT_PACKED_START::ObjTargetPosition, STRUCT_PACKED_START::ObjTargetVelocity, OBJ_STRUCT_PACKED_START::objTargetVelocity, OBJ_STRUCT_PACKED_START::pobjControlWord, OBJ_STRUCT_PACKED_START::pobjTargetPosition, sRxPDOassign, SWAPDWORD, SWAPWORD, and OBJ_STRUCT_PACKED_START::u16SubIndex0.
Referenced by PDO_OutputMapping().
APPL_StartInputHandler()
PROTO UINT16 APPL_StartInputHandler (UINT16 * pIntMask)
The function is called in the state transition from PREOP to SAFEOP when all general settings were checked to start the input handler. This function informs the application about the state transition, the application can refuse the state transition when returning an AL Status error code. The return code NOERROR_INWORK can be used, if the application cannot confirm the state transition immediately, in that case the application need to be complete the transition by calling ECAT_StateChange.
Parameters
pIntMask pointer to the AL Event Mask which will be written to the AL event Mask register (0x204) when this function is succeeded. The event mask can be adapted in this function
Returns
AL Status Code (see ecatslv.h ALSTATUSCODE_....)
Definition at line 908 of file AX58400_MotorControl.c.
References OBJ_STRUCT_PACKED_START::aEntries, ALSTATUSCODE_NOERROR, bDcSyncActive, ConfiguredModuleIdentList0xF030, CSP_MODULE_ID, CSV_CSP_MODULE_ID, CSV_MODULE_ID, ESC_DC_SYNC0_CYCLETIME_OFFSET, MAX_AXES, ModuleDetectedList0xF050, ModuleProfileList0xF010, sRxPDOassign, SWAPDWORD, OBJ_STRUCT_PACKED_START::u16SubIndex0, and TCiA402Axis::u32CycleTime.
Referenced by AL_ControlInd(), and AL_ControlRes().
APPL_StartMailboxHandler()
PROTO UINT16 APPL_StartMailboxHandler (void)
The function is called in the state transition from INIT to PREOP when all general settings were checked to start the mailbox handler. This function informs the application about the state transition, the application can refuse the state transition when returning an AL Status error code. The return code NOERROR_INWORK can be used, if the application cannot confirm the state transition immediately, in that case the application need to be complete the transition by calling ECAT_StateChange.
Returns
AL Status Code (see ecatslv.h ALSTATUSCODE_....)
Definition at line 871 of file AX58400_MotorControl.c.
References ALSTATUSCODE_NOERROR.
Referenced by AL_ControlInd(), and AL_ControlRes().
APPL_StartOutputHandler()
PROTO UINT16 APPL_StartOutputHandler (void)
The function is called in the state transition from SAFEOP to OP when all general settings were checked to start the output handler. This function informs the application about the state transition, the application can refuse the state transition when returning an AL Status error code. The return code NOERROR_INWORK can be used, if the application cannot confirm the state transition immediately, in that case the application need to be complete the transition by calling ECAT_StateChange.
Returns
AL Status Code (see ecatslv.h ALSTATUSCODE_....)
Definition at line 994 of file AX58400_MotorControl.c.
References ALSTATUSCODE_NOERROR, TCiA402Axis::i16State, MAX_AXES, MC_NO_ERROR, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::pobjErrorCode, and STATE_SWITCH_ON_DISABLED.
Referenced by AL_ControlInd(), and AL_ControlRes().
APPL_StopInputHandler()
PROTO UINT16 APPL_StopInputHandler (void)
The function is called in the state transition from SAFEOP to PREEOP to stop the input handler. This functions informs the application about the state transition, the application cannot refuse the state transition.
Returns
0, NOERROR_INWORK
Definition at line 976 of file AX58400_MotorControl.c.
References ALSTATUSCODE_NOERROR.
Referenced by AL_ControlInd(), AL_ControlRes(), and ECAT_StateChange().
APPL_StopMailboxHandler()
PROTO UINT16 APPL_StopMailboxHandler (void)
The function is called in the state transition from PREEOP to INIT to stop the mailbox handler. This functions informs the application about the state transition, the application cannot refuse the state transition.
Returns
0, NOERROR_INWORK
Definition at line 887 of file AX58400_MotorControl.c.
References ALSTATUSCODE_NOERROR.
Referenced by AL_ControlInd(), AL_ControlRes(), and ECAT_StateChange().
APPL_StopOutputHandler()
PROTO UINT16 APPL_StopOutputHandler (void)
The function is called in the state transition from OP to SAFEOP to stop the output handler. This functions informs the application about the state transition, the application cannot refuse the state transition.
Returns
0, NOERROR_INWORK
Definition at line 1033 of file AX58400_MotorControl.c.
References ALSTATUSCODE_NOERROR, CiA402_LocalError(), ERROR_COMMUNICATION, and MAX_AXES.
Referenced by AL_ControlInd(), AL_ControlRes(), and ECAT_StateChange().
CiA402_Application()
void CiA402_Application (TCiA402Axis * pCiA402Axis)
CiA402-Application.
check if a state transition is pending and pass desired ramp-code to CiA402TransitionAction()
if this functions returns true the state transition is finished.
Definition at line 735 of file AX58400_MotorControl.c.
References bDcSyncActive, CiA402_TransitionAction(), CYCLIC_SYNC_POSITION_MODE, CYCLIC_SYNC_VELOCITY_MODE, HOMING_MODE, TCiA402Axis::i16State, OBJ_STRUCT_PACKED_START::objDisableOperationOptionCode, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::objFaultReactionCode, OBJ_STRUCT_PACKED_START::objModesOfOperation, OBJ_STRUCT_PACKED_START::objQuickStopOptionCode, OBJ_STRUCT_PACKED_START::objShutdownOptionCode, OBJ_STRUCT_PACKED_START::objSupportedDriveModes, OBJ_STRUCT_PACKED_START::pobjModesOfOperationDisplay, OBJ_STRUCT_PACKED_START::pobjStatusWord, STATE_FAULT, STATE_READY_TO_SWITCH_ON, STATE_SWITCH_ON_DISABLED, STATE_SWITCHED_ON, STATUSWORD_DRIVE_FOLLOWS_COMMAND, STATUSWORD_TARGET_REACHED, TCiA402Axis::u16PendingOptionCode, and TCiA402Axis::u32CycleTime.
Referenced by APPL_Application().
CiA402_ConfigureObjects()
int CiA402_ConfigureObjects (TCiA402Axis * pCiA402Axis)
CiA402_ConfigureObjects.
Definition at line 311 of file AX58400_MotorControl.c.
References TCiA402Axis::bConfigurationAllowed, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::objModesOfOperation, and OBJ_STRUCT_PACKED_START::pobjModesOfOperationDisplay.
Referenced by CiA402_StateMachine().
CiA402_DeallocateAxis()
void CiA402_DeallocateAxis (void)
CiA402_DeallocateAxis.
Remove all allocated axes resources
Definition at line 187 of file AX58400_MotorControl.c.
References COE_RemoveDicEntry(), MAX_AXES, nPdInputSize, nPdOutputSize, and TCiA402Axis::ObjDic.
CiA402_LocalError()
PROTO void CiA402_LocalError (UINT16 ErrorCode)
CiA402_LocalError.
Parameters
ErrorCode
this function is called if an error was detected
Definition at line 645 of file AX58400_MotorControl.c.
References TCiA402Axis::i16State, MAX_AXES, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::pobjErrorCode, and STATE_FAULT_REACTION_ACTIVE.
Referenced by APPL_StopOutputHandler(), and CiA402_UpdateObjects().
CiA402_StateMachine()
PROTO void CiA402_StateMachine (void)
CiA402-Statemachine This function handles the state machine for devices using the CiA402 profile. called cyclic from MainLoop() All described transition numbers are referring to the document "ETG Implementation Guideline for the CiA402 Axis Profile" located on the EtherCAT.org download section.
Definition at line 337 of file AX58400_MotorControl.c.
References TCiA402Axis::bAxisFunctionEnabled, TCiA402Axis::bBrakeApplied, TCiA402Axis::bConfigurationAllowed, TCiA402Axis::bHighLevelPowerApplied, CiA402_ConfigureObjects(), CONTROLWORD_COMMAND_DISABLEOPERATION, CONTROLWORD_COMMAND_DISABLEOPERATION_MASK, CONTROLWORD_COMMAND_DISABLEVOLTAGE, CONTROLWORD_COMMAND_DISABLEVOLTAGE_MASK, CONTROLWORD_COMMAND_ENABLEOPERATION, CONTROLWORD_COMMAND_ENABLEOPERATION_MASK, CONTROLWORD_COMMAND_FAULTRESET, CONTROLWORD_COMMAND_FAULTRESET_MASK, CONTROLWORD_COMMAND_QUICKSTOP, CONTROLWORD_COMMAND_QUICKSTOP_MASK, CONTROLWORD_COMMAND_SHUTDOWN, CONTROLWORD_COMMAND_SHUTDOWN_MASK, CONTROLWORD_COMMAND_SWITCHON, CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION, CONTROLWORD_COMMAND_SWITCHON_ENABLEOPERATION_MASK, CONTROLWORD_COMMAND_SWITCHON_MASK, DISABLE_DRIVE, HOMING_MODE, TCiA402Axis::i16State, MAX_AXES, nAlStatus, OBJ_STRUCT_PACKED_START::objDisableOperationOptionCode, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::objFaultReactionCode, OBJ_STRUCT_PACKED_START::objQuickStopOptionCode, OBJ_STRUCT_PACKED_START::objShutdownOptionCode, OBJ_STRUCT_PACKED_START::objStatusWord, OBJ_STRUCT_PACKED_START::pobjControlWord, OBJ_STRUCT_PACKED_START::pobjErrorCode, OBJ_STRUCT_PACKED_START::pobjModesOfOperationDisplay, OBJ_STRUCT_PACKED_START::pobjStatusWord, STATE_FAULT, STATE_FAULT_REACTION_ACTIVE, STATE_NOT_READY_TO_SWITCH_ON, STATE_OP, STATE_OPERATION_ENABLED, STATE_QUICK_STOP_ACTIVE, STATE_READY_TO_SWITCH_ON, STATE_SWITCH_ON_DISABLED, STATE_SWITCHED_ON, STATUSWORD_REMOTE, STATUSWORD_STATE_FAULT, STATUSWORD_STATE_FAULTREACTIONACTIVE, STATUSWORD_STATE_MASK, STATUSWORD_STATE_NOTREADYTOSWITCHON, STATUSWORD_STATE_OPERATIONENABLED, STATUSWORD_STATE_QUICKSTOPACTIVE, STATUSWORD_STATE_READYTOSWITCHON, STATUSWORD_STATE_SWITCHEDON, STATUSWORD_STATE_SWITCHEDONDISABLED, STATUSWORD_VOLTAGE_ENABLED, and TCiA402Axis::u16PendingOptionCode.
CiA402_TransitionAction()
BOOL CiA402_TransitionAction (INT16 Characteristic, TCiA402Axis * pCiA402Axis)
CiA402-TransitionAction.
Returns
TRUE if moving on predefined ramp is finished
this function shall calculate the desired Axis input values to move on a predefined ramp
if the ramp is finished return TRUE
Definition at line 666 of file AX58400_MotorControl.c.
References DISABLE_DRIVE, QUICKSTOP_RAMP, SLOW_DOWN_RAMP, STOP_ON_CURRENT_LIMIT, and STOP_ON_VOLTAGE_LIMIT.
Referenced by CiA402_Application().
CiA402_UpdateObjects()
int CiA402_UpdateObjects (TCiA402Axis * pCiA402Axis)
CiA402_UpdateObjects.
Definition at line 220 of file AX58400_MotorControl.c.
References CiA402_LocalError(), ERROR_DC_LINK_OVER_VOLTAGE, ERROR_DC_LINK_UNDER_VOLTAGE, ERROR_EMERGENCY_OCCUR, ERROR_EXCESS_TEMPERATURE_DRIVE, ERROR_MAINS_FREQUENCY_TOO_GREAT, ERROR_MOTOR_ERROR, ERROR_SPEED, MC_BREAK_IN, MC_FOC_DURATION, MC_NO_ERROR, MC_OVER_TEMP, MC_OVER_VOLT, MC_SPEED_FDBK, MC_START_UP, MC_SW_ERROR, MC_UNDER_VOLT, OBJ_STRUCT_PACKED_START::objDigitalInputs, TCiA402Axis::Objects, OBJ_STRUCT_PACKED_START::pobjErrorCode, OBJ_STRUCT_PACKED_START::pobjStatusWord, STATUSWORD_STATE_FAULT, STATUSWORD_STATE_FAULTREACTIONACTIVE, and STATUSWORD_STATE_MASK.
Referenced by APPL_Application().
Variable Documentation
LocalAxes
PROTO pTCiA402Axis LocalAxes
Definition at line 529 of file AX58400_MotorControl.h.